ACTS_CONFIG = {
    "act11": {
        "name": "Workforce Development and Green Jobs Act of 2026",
        "short_name": "WDGJA",
        "dir": "11-Workforce-Green-Jobs-Act",
        "funding": "$50 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, problem statement, program architecture, key provisions, economic projections, implementation timeline"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, national interest declarations, workforce crisis data, clean energy transition imperatives"},
            "03": {"name": "TITLE-I-APPRENTICESHIP-EXPANSION", "title": "Title I — Apprenticeship Expansion", "topic": "National Clean Energy Apprenticeship Corps, registered apprenticeship tax credits, pre-apprenticeship pipeline, completion incentives, industry-recognized standards"},
            "04": {"name": "TITLE-II-COMMUNITY-COLLEGE-MANUFACTURING-CENTERS", "title": "Title II — Community College Manufacturing Centers", "topic": "Clean Manufacturing Centers of Excellence, equipment modernization grants, industry partnership curriculum, faculty training exchange, credentialing alignment"},
            "05": {"name": "TITLE-III-VETERAN-TRANSITION", "title": "Title III — Veteran Transition Program", "topic": "Clean Energy Veterans Corps, GI Bill expansion, DOD SkillBridge partnerships, veteran-owned business grants, military base transition pilots"},
            "06": {"name": "TITLE-IV-FOSSIL-FUEL-WORKER-BRIDGE", "title": "Title IV — Fossil Fuel Worker Bridge Program", "topic": "Energy Transition Adjustment Assistance, wage insurance, Coal and Oil Community Reinvestment Fund, skills mapping, regional transition offices"},
            "07": {"name": "TITLE-V-K12-STEM-PIPELINE", "title": "Title V — K-12 STEM Pipeline Initiative", "topic": "Career Technical Education grants, STEM teacher training, high school pre-apprenticeship, Summer Youth Clean Energy Corps, maker spaces and labs"},
            "08": {"name": "TITLE-VI-NUCLEAR-WORKFORCE-PIPELINE", "title": "Title VI — Nuclear Workforce Pipeline", "topic": "Nuclear science scholarships, university reactor upgrades, fusion workforce development, technician certification, HALEU fuel cycle training"},
            "09": {"name": "TITLE-VII-SEMICONDUCTOR-WORKFORCE", "title": "Title VII — Semiconductor Workforce", "topic": "CHIPS Act coordination, technician fast-track training, advanced packaging workforce, microelectronics research hubs, equipment maintenance certification"},
            "10": {"name": "TITLE-VIII-CLEAN-ENERGY-CORPS", "title": "Title VIII — Clean Energy Corps", "topic": "Corps establishment, member recruitment and training, project portfolio, educational benefits, state and local partnerships"},
            "11": {"name": "TITLE-IX-GREEN-JOBS-TAX-CREDIT", "title": "Title IX — Green Jobs Tax Credit", "topic": "Employer hiring tax credit, worker relocation deduction, apprenticeship wage subsidy, small business transition credit, prevailing wage requirements"},
            "12": {"name": "TITLE-X-TRIBAL-WORKFORCE", "title": "Title X — Tribal Workforce Development", "topic": "Tribal training centers, tribal college partnerships, Native American employment preference, tribal energy sovereignty grants, cultural preservation integration"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, program evaluation metrics, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, labor standards, domestic hiring requirements, references and authorities, cost-benefit analysis"}
        }
    },
    "act12": {
        "name": "Energy Storage and Grid Flexibility Act of 2026",
        "short_name": "ESGFA",
        "dir": "12-Energy-Storage-Grid-Flexibility-Act",
        "funding": "$80 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, problem statement, program architecture, key provisions, economic projections, implementation timeline"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, national interest declarations, energy storage deficit data, grid flexibility imperatives"},
            "03": {"name": "TITLE-I-LONG-DURATION-STORAGE", "title": "Title I — Long-Duration Storage Deployment", "topic": "LDES deployment program, cost-reduction purchase commitments, iron-air battery initiative, flow battery scale-up, demonstration projects"},
            "04": {"name": "TITLE-II-SHORT-DURATION-BATTERY", "title": "Title II — Short-Duration Battery Manufacturing", "topic": "Domestic lithium-ion gigafactory program, solid-state battery initiative, zinc-based production tax credit, supply chain resilience, workforce training"},
            "05": {"name": "TITLE-III-THERMAL-STORAGE", "title": "Title III — Thermal Storage for Industry", "topic": "Industrial thermal storage deployment, thermal battery manufacturing credit, heat-as-a-service pilot, district energy systems, high-temperature research"},
            "06": {"name": "TITLE-IV-GRAVITY-PUMPED-STORAGE", "title": "Title IV — Gravity and Pumped Storage", "topic": "Pumped storage hydropower streamlining, gravity-based storage fund, underground pumped storage, mine-to-storage repurposing, water rights compliance"},
            "07": {"name": "TITLE-V-V2G-EV-INTEGRATION", "title": "Title V — V2G and EV Battery Integration", "topic": "Vehicle-to-grid infrastructure, EV battery second-life utilization, smart charging standards, school bus V2G pilot, battery recycling circular economy"},
            "08": {"name": "TITLE-VI-STORAGE-TAX-CREDIT", "title": "Title VI — Storage Tax Credit Extension", "topic": "Section 48 ITC modification, Section 45X expansion, long-duration production tax credit, storage-as-transmission classification, prevailing wage requirements"},
            "09": {"name": "TITLE-VII-STORAGE-R-AND-D", "title": "Title VII — Storage Research and Development", "topic": "Next-generation storage research, advanced battery materials hub, grid-scale testing, safety standards, duration benchmarking"},
            "10": {"name": "TITLE-VIII-GRID-FLEXIBILITY-MARKET", "title": "Title VIII — Grid Flexibility Market Design", "topic": "FERC Order 2222 implementation, DER aggregation standards, time-of-use pricing mandates, interconnection queue reform, regional market integration"},
            "11": {"name": "TITLE-IX-VIRTUAL-POWER-PLANT", "title": "Title IX — Virtual Power Plant Framework", "topic": "National VPP deployment program, aggregator certification, residential storage incentive, utility VPP procurement mandate, cybersecurity and data privacy"},
            "12": {"name": "TITLE-X-TRANSMISSION-STORAGE-COLOCATION", "title": "Title X — Transmission-Storage Co-Location", "topic": "Storage-as-transmission pilot, transmission congestion relief, co-located renewable-storage incentives, interconnection cost allocation reform, national planning"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, program evaluation metrics, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, grid reliability savings, domestic content requirements, references and authorities, cost-benefit analysis"}
        }
    },
    "act13": {
        "name": "Critical Minerals Security and Domestic Supply Chain Act of 2026",
        "short_name": "CMSDSCA",
        "dir": "13-Critical-Minerals-Security-Act",
        "funding": "$45 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, problem statement, program architecture, key provisions, economic projections, implementation timeline"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, national security imperatives, supply chain vulnerability data, foreign dependency risks"},
            "03": {"name": "TITLE-I-DOMESTIC-MINING-EXPANSION", "title": "Title I — Domestic Mining Expansion", "topic": "critical minerals mining permits, federal land access, mining workforce development, environmental standards modernization, tribal consultation"},
            "04": {"name": "TITLE-II-PROCESSING-REFINING-CAPACITY", "title": "Title II — Processing and Refining Capacity", "topic": "domestic lithium processing, rare earth element separation, cobalt refining, nickel processing, uranium conversion facilities"},
            "05": {"name": "TITLE-III-RECYCLING-CIRCULAR-ECONOMY", "title": "Title III — Recycling and Circular Economy", "topic": "battery recycling infrastructure, rare earth recovery, e-waste processing, urban mining incentives, circular supply chain standards"},
            "06": {"name": "TITLE-IV-STRATEGIC-STOCKPILE", "title": "Title IV — Strategic Stockpile Modernization", "topic": "National Defense Stockpile expansion, critical minerals reserve, rotation and maintenance protocols, international stockpile coordination"},
            "07": {"name": "TITLE-V-ALLIED-SUPPLY-CHAIN-PARTNERSHIPS", "title": "Title V — Allied Supply Chain Partnerships", "topic": "mineral security partnerships, friend-shoring agreements, international processing standards, allied stockpile sharing, diplomatic frameworks"},
            "08": {"name": "TITLE-VI-RESEARCH-ALTERNATIVES", "title": "Title VI — Research into Material Alternatives", "topic": "substitution research, sodium-ion battery development, rare earth-free magnets, advanced composites, computational materials discovery"},
            "09": {"name": "TITLE-VII-PERMITTING-REFORM", "title": "Title VII — Permitting Reform for Critical Minerals", "topic": "NEPA streamlining for critical minerals, federal permitting timelines, state-federal coordination, environmental review efficiency"},
            "10": {"name": "TITLE-VIII-WORKFORCE-DEVELOPMENT", "title": "Title VIII — Critical Minerals Workforce Development", "topic": "mining engineering scholarships, geologist training programs, metallurgical technician certification, community college mining programs"},
            "11": {"name": "TITLE-IX-MAPPING-EXPLORATION", "title": "Title IX — Geological Mapping and Exploration", "topic": "USGS critical minerals mapping, advanced exploration technologies, domestic resource assessment, international geological surveys"},
            "12": {"name": "TITLE-X-NATIONAL-SECURITY-OVERSIGHT", "title": "Title X — National Security Oversight", "topic": "Committee on Foreign Investment review, export controls on critical minerals, supply chain risk assessments, defense production act authorities"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, program evaluation metrics, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, national security benefits, domestic content requirements, references and authorities, cost-benefit analysis"}
        }
    },
    "act14": {
        "name": "National Cybersecurity and Digital Infrastructure Protection Act of 2026",
        "short_name": "NCDIPA",
        "dir": "14-Cybersecurity-Digital-Infrastructure-Act",
        "funding": "$65 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, threat landscape analysis, program architecture, key provisions, economic projections, implementation timeline"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, national security imperatives, cyber threat data, critical digital infrastructure vulnerabilities"},
            "03": {"name": "TITLE-I-CRITICAL-INFRASTRUCTURE-CYBERSECURITY", "title": "Title I — Critical Infrastructure Cybersecurity", "topic": "energy sector cybersecurity, water system protection, transportation network defense, healthcare infrastructure security, financial system resilience"},
            "04": {"name": "TITLE-II-ZERO-TRUST-ARCHITECTURE-MANDATE", "title": "Title II — Zero Trust Architecture Mandate", "topic": "federal zero trust implementation, continuous verification protocols, micro-segmentation standards, identity and access management, device trust verification"},
            "05": {"name": "TITLE-III-SUPPLY-CHAIN-CYBERSECURITY", "title": "Title III — Supply Chain Cybersecurity", "topic": "software bill of materials requirements, hardware provenance verification, third-party risk management, vendor security assessments, open source security"},
            "06": {"name": "TITLE-IV-NATIONAL-CYBERSECURITY-WORKFORCE", "title": "Title IV — National Cybersecurity Workforce", "topic": "cybersecurity education grants, workforce training programs, certification standards, community college cyber programs, veteran transition programs"},
            "07": {"name": "TITLE-V-THREAT-INTELLIGENCE-SHARING", "title": "Title V — Threat Intelligence Sharing", "topic": "ISAC expansion, public-private threat sharing, automated indicator sharing, classified threat briefing programs, international cyber threat cooperation"},
            "08": {"name": "TITLE-VI-QUANTUM-RESISTANT-CRYPTOGRAPHY", "title": "Title VI — Quantum Resistant Cryptography", "topic": "post-quantum cryptography migration, NIST algorithm implementation, quantum key distribution, cryptographic inventory requirements, transition timeline"},
            "09": {"name": "TITLE-VII-AI-CYBERSECURITY-DEFENSE", "title": "Title VII — AI-Powered Cybersecurity Defense", "topic": "AI threat detection systems, automated incident response, machine learning for anomaly detection, adversarial AI defense, AI security standards"},
            "10": {"name": "TITLE-VIII-INCIDENT-RESPONSE-REQUIREMENTS", "title": "Title VIII — Incident Response and Reporting Requirements", "topic": "mandatory incident reporting, CIRCIA implementation, critical incident response teams, forensic investigation standards, recovery requirements"},
            "11": {"name": "TITLE-IX-CYBER-INSURANCE-INCENTIVES", "title": "Title IX — Cyber Insurance and Risk Management Incentives", "topic": "cyber insurance tax incentives, risk assessment frameworks, security control premium reductions, small business cyber insurance, federal backstop program"},
            "12": {"name": "TITLE-X-INTERNATIONAL-CYBER-DIPLOMACY", "title": "Title X — International Cyber Diplomacy and Norms", "topic": "cyber norms development, attribution frameworks, capacity building programs, cyber sanctions authorities, international cooperation agreements"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, program evaluation metrics, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, cybersecurity benefits quantification, domestic content requirements, references and authorities, cost-benefit analysis"}
        }
    },
    "act15": {
        "name": "Clean Hydrogen Economy and Industrial Decarbonization Act of 2026",
        "short_name": "CHEDIA",
        "dir": "15-Clean-Hydrogen-Economy-Act",
        "funding": "$55 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, hydrogen economy potential, program architecture, key provisions, economic projections, implementation timeline"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, hydrogen as industrial feedstock, decarbonization imperatives, global hydrogen competition"},
            "03": {"name": "TITLE-I-HYDROGEN-PRODUCTION-HUBS", "title": "Title I — Hydrogen Production Hubs", "topic": "regional hydrogen hubs, electrolyzer deployment, green hydrogen production, blue hydrogen with carbon capture, hydrogen production tax credits"},
            "04": {"name": "TITLE-II-HYDROGEN-INFRASTRUCTURE", "title": "Title II — Hydrogen Infrastructure and Distribution", "topic": "hydrogen pipeline network, storage facilities, liquefaction plants, transport corridors, port hydrogen terminals"},
            "05": {"name": "TITLE-III-INDUSTRIAL-HYDROGEN-APPLICATIONS", "title": "Title III — Industrial Hydrogen Applications", "topic": "steel industry hydrogen direct reduction, ammonia production, petroleum refining, chemical manufacturing, cement industry hydrogen firing"},
            "06": {"name": "TITLE-IV-HYDROGEN-TRANSPORTATION", "title": "Title IV — Hydrogen Transportation and Mobility", "topic": "fuel cell electric vehicles, hydrogen refueling stations, heavy-duty trucking, rail applications, maritime hydrogen fuel"},
            "07": {"name": "TITLE-V-HYDROGEN-WORKFORCE", "title": "Title V — Hydrogen Workforce Development", "topic": "hydrogen safety training, technician certification, engineering programs, community college partnerships, apprenticeship programs"},
            "08": {"name": "TITLE-VI-HYDROGEN-EXPORT-STRATEGY", "title": "Title VI — Hydrogen Export and International Markets", "topic": "hydrogen export terminals, international partnerships, ammonia as hydrogen carrier, global hydrogen trading framework"},
            "09": {"name": "TITLE-VII-HYDROGEN-SAFETY-STANDARDS", "title": "Title VII — Hydrogen Safety and Standards Development", "topic": "hydrogen safety codes, leakage detection, materials compatibility, fire protection standards, regulatory harmonization"},
            "10": {"name": "TITLE-VIII-HYDROGEN-RESEARCH", "title": "Title VIII — Hydrogen Research and Development", "topic": "advanced electrolysis, hydrogen storage materials, fuel cell durability, hydrogen embrittlement, next-generation production technologies"},
            "11": {"name": "TITLE-IX-HYDROGEN-ENVIRONMENTAL", "title": "Title IX — Hydrogen Environmental and Siting Requirements", "topic": "water use for electrolysis, land use for production hubs, environmental justice considerations, lifecycle analysis, sustainability certification"},
            "12": {"name": "TITLE-X-HYDROGEN-FINANCE", "title": "Title X — Hydrogen Finance and Risk Mitigation", "topic": "loan guarantee programs, hydrogen price insurance, offtake agreement frameworks, green hydrogen certification, market development"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, program evaluation metrics, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, hydrogen market projections, domestic content requirements, references and authorities, cost-benefit analysis"}
        }
    },
    "act16": {
        "name": "Sustainable Aviation and Alternative Fuels Act of 2026",
        "short_name": "SAAFA",
        "dir": "16-Sustainable-Aviation-Fuels-Act",
        "funding": "$40 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, aviation emissions challenge, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, aviation sector emissions data, sustainable fuel potential, global competition"},
            "03": {"name": "TITLE-I-SAF-PRODUCTION-SCALE-UP", "title": "Title I — Sustainable Aviation Fuel Production Scale-Up", "topic": "SAF refinery construction, feedstock development, alcohol-to-jet pathways, power-to-liquid fuels, production tax credits"},
            "04": {"name": "TITLE-II-AIRPORT-INFRASTRUCTURE", "title": "Title II — Airport Alternative Fuel Infrastructure", "topic": "SAF blending facilities, hydrogen aircraft infrastructure, electric aircraft charging, fuel distribution systems"},
            "05": {"name": "TITLE-III-AIRCRAFT-ELECTRIFICATION", "title": "Title III — Aircraft Electrification and Hybrid Systems", "topic": "electric regional aircraft, hybrid-electric propulsion, battery technology requirements, certification standards"},
            "06": {"name": "TITLE-IV-HYDROGEN-AVIATION", "title": "Title IV — Hydrogen-Powered Aviation", "topic": "hydrogen combustion aircraft, fuel cell propulsion, liquid hydrogen storage, airport hydrogen systems"},
            "07": {"name": "TITLE-V-AVIATION-WORKFORCE", "title": "Title V — Aviation Clean Energy Workforce", "topic": "SAF plant operators, aircraft mechanics retraining, hydrogen handling certification, engineering programs"},
            "08": {"name": "TITLE-VI-INTERMODAL-CONNECTIVITY", "title": "Title VI — Intermodal Clean Transportation Connectivity", "topic": "airport-rail links, electric ground transport, multimodal freight hubs, last-mile delivery electrification"},
            "09": {"name": "TITLE-VII-NOISE-COMMUNITY-IMPACT", "title": "Title VII — Noise Reduction and Community Impact", "topic": "quiet aircraft technology, noise abatement procedures, community engagement, environmental justice"},
            "10": {"name": "TITLE-VIII-INTERNATIONAL-AVIATION-AGREEMENTS", "title": "Title VIII — International Aviation Climate Agreements", "topic": "ICAO CORSIA implementation, bilateral SAF agreements, carbon offset standards, global aviation emissions framework"},
            "11": {"name": "TITLE-IX-AVIATION-R-AND-D", "title": "Title IX — Aviation Research and Development", "topic": "advanced propulsion research, lightweight materials, aerodynamic efficiency, alternative fuel testing facilities"},
            "12": {"name": "TITLE-X-AVIATION-FINANCE", "title": "Title X — Aviation Finance and Incentive Programs", "topic": "SAF price support mechanisms, loan guarantees for production facilities, green bonds, insurance products"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, aviation sector transformation, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act17": {
        "name": "National Water Recycling and Desalination Resilience Act of 2026",
        "short_name": "NWRDRA",
        "dir": "17-Water-Recycling-Desalination-Act",
        "funding": "$35 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, water scarcity challenge, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, drought data, water infrastructure deficit, climate change impacts on water supply"},
            "03": {"name": "TITLE-I-MUNICIPAL-WATER-RECYCLING", "title": "Title I — Municipal Water Recycling Programs", "topic": "direct potable reuse, greywater systems, industrial water recycling, decentralized treatment, water quality standards"},
            "04": {"name": "TITLE-II-DESALINATION-DEPLOYMENT", "title": "Title II — Desalination Plant Deployment", "topic": "seawater reverse osmosis, brackish water desalination, renewable-powered desalination, brine management"},
            "05": {"name": "TITLE-III-WATER-INFRASTRUCTURE-MODERNIZATION", "title": "Title III — Water Infrastructure Modernization", "topic": "pipe replacement, leak detection, smart water meters, stormwater capture, aquifer recharge"},
            "06": {"name": "TITLE-IV-AGRICULTURAL-WATER-EFFICIENCY", "title": "Title IV — Agricultural Water Efficiency", "topic": "precision irrigation, drought-resistant crops, soil moisture monitoring, agricultural water recycling"},
            "07": {"name": "TITLE-V-INDUSTRIAL-WATER-REUSE", "title": "Title V — Industrial Water Reuse Requirements", "topic": "cooling water recycling, process water treatment, zero liquid discharge, industrial water intensity standards"},
            "08": {"name": "TITLE-VI-WATER-WORKFORCE", "title": "Title VI — Water Sector Workforce Development", "topic": "water treatment operator training, desalination technician certification, engineering scholarships, apprenticeship programs"},
            "09": {"name": "TITLE-VII-WATER-DATA-MANAGEMENT", "title": "Title VII — Water Data and Smart Management Systems", "topic": "national water data platform, satellite monitoring, predictive analytics, drought early warning systems"},
            "10": {"name": "TITLE-VIII-TRIBAL-WATER-ACCESS", "title": "Title VIII — Tribal Water Access and Sovereignty", "topic": "tribal water rights, reservation water infrastructure, tribal utility authority, cultural water practices"},
            "11": {"name": "TITLE-IX-WATER-FINANCE-INNOVATION", "title": "Title IX — Water Finance and Innovation Programs", "topic": "water infrastructure bank, green bonds for water, public-private partnerships, water affordability programs"},
            "12": {"name": "TITLE-X-TRANSBOUNDARY-WATER-AGREEMENTS", "title": "Title X — Transboundary Water Cooperation", "topic": "Colorado River Compact, Great Lakes agreements, international water treaties, groundwater governance"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, water security benefits, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act18": {
        "name": "National Broadband and Digital Equity Act of 2026",
        "short_name": "NBDEA",
        "dir": "18-Broadband-Digital-Equity-Act",
        "funding": "$60 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, digital divide data, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, broadband access gaps, digital equity imperatives, economic impact of connectivity"},
            "03": {"name": "TITLE-I-BROADBAND-DEPLOYMENT", "title": "Title I — Universal Broadband Deployment", "topic": "fiber optic expansion, rural broadband, 5G fixed wireless, satellite broadband subsidies, middle mile infrastructure"},
            "04": {"name": "TITLE-II-DIGITAL-EQUITY-PROGRAMS", "title": "Title II — Digital Equity and Literacy Programs", "topic": "device subsidies, digital skills training, community technology centers, multilingual digital literacy, senior digital inclusion"},
            "05": {"name": "TITLE-III-TRIBAL-BROADBAND", "title": "Title III — Tribal Broadband Connectivity", "topic": "tribal broadband deployment, spectrum for tribal nations, tribal digital sovereignty, Indigenous data governance"},
            "06": {"name": "TITLE-IV-AFFORDABILITY-PROGRAMS", "title": "Title IV — Broadband Affordability Programs", "topic": "affordable connectivity program expansion, low-cost broadband plans, lifeline broadband, affordability benchmarks"},
            "07": {"name": "TITLE-V-PUBLIC-SAFETY-COMMUNICATIONS", "title": "Title V — Public Safety Communications Infrastructure", "topic": "FirstNet expansion, emergency communications, interoperable radio systems, disaster-resilient networks"},
            "08": {"name": "TITLE-VI-OPEN-INTERNET-STANDARDS", "title": "Title VI — Open Internet and Net Neutrality Standards", "topic": "net neutrality protections, transparency requirements, anti-throttling rules, paid prioritization ban, edge provider access"},
            "09": {"name": "TITLE-VII-BROADBAND-WORKFORCE", "title": "Title VII — Telecommunications Workforce Development", "topic": "fiber technician training, tower technician certification, engineering scholarships, apprenticeship programs"},
            "10": {"name": "TITLE-VIII-SMART-COMMUNITIES", "title": "Title VIII — Smart Communities and IoT Deployment", "topic": "smart city infrastructure, IoT sensor networks, intelligent transportation systems, connected healthcare systems"},
            "11": {"name": "TITLE-IX-SPECTRUM-MANAGEMENT", "title": "Title IX — Spectrum Management and Innovation", "topic": "spectrum auction reform, shared spectrum frameworks, 6G research, millimeter wave deployment, spectrum repurposing"},
            "12": {"name": "TITLE-X-CYBERSECURITY-BROADBAND", "title": "Title X — Broadband Network Cybersecurity Standards", "topic": "network security requirements, encryption standards, critical infrastructure protection, supply chain security"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, connectivity benefits, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act19": {
        "name": "Carbon Capture and Sequestration Deployment Act of 2026",
        "short_name": "CCSDA",
        "dir": "19-Carbon-Capture-Sequestration-Act",
        "funding": "$70 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, climate mitigation challenge, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, atmospheric CO2 data, carbon removal imperatives, climate targets"},
            "03": {"name": "TITLE-I-DIRECT-AIR-CAPTURE", "title": "Title I — Direct Air Capture Hubs", "topic": "DAC facility deployment, hub program, sorbent technology, renewable energy integration, cost reduction targets"},
            "04": {"name": "TITLE-II-POINT-SOURCE-CAPTURE", "title": "Title II — Point Source Carbon Capture", "topic": "industrial capture systems, cement plant capture, steel mill capture, refinery capture, power plant retrofit"},
            "05": {"name": "TITLE-III-CARBON-TRANSPORT-INFRASTRUCTURE", "title": "Title III — Carbon Transport Infrastructure", "topic": "CO2 pipeline networks, rail transport, ship transport, pipeline safety standards, hub interconnection"},
            "06": {"name": "TITLE-IV-GEOLOGICAL-STORAGE", "title": "Title IV — Geological Storage and Sequestration", "topic": "saline formation storage, depleted oil field storage, Class VI well program, monitoring requirements, liability framework"},
            "07": {"name": "TITLE-V-CARBON-UTILIZATION", "title": "Title V — Carbon Utilization and Products", "topic": "CO2-to-concrete, synthetic fuels, chemical feedstocks, mineralization, carbon product standards"},
            "08": {"name": "TITLE-VI-NATURE-BASED-SOLUTIONS", "title": "Title VI — Nature-Based Carbon Removal", "topic": "reforestation programs, soil carbon sequestration, blue carbon ecosystems, coastal wetland restoration, biochar"},
            "09": {"name": "TITLE-VII-OCEAN-CARBON-REMOVAL", "title": "Title VII — Ocean-Based Carbon Removal", "topic": "ocean alkalinity enhancement, seaweed cultivation, ocean fertilization research, marine carbon monitoring"},
            "10": {"name": "TITLE-VIII-CARBON-ACCOUNTING", "title": "Title VIII — Carbon Accounting and Verification", "topic": "MRV protocols, lifecycle analysis, carbon credit standards, registry systems, third-party verification"},
            "11": {"name": "TITLE-IX-ENVIRONMENTAL-JUSTICE", "title": "Title IX — Environmental Justice and Community Benefits", "topic": "community benefit agreements, environmental monitoring, just transition for workers, tribal consultation"},
            "12": {"name": "TITLE-X-CARBON-CAPTURE-WORKFORCE", "title": "Title X — Carbon Capture Workforce Development", "topic": "engineering scholarships, technician certification, geologist training, community college programs"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, climate benefits quantification, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act20": {
        "name": "National Electric Vehicle Charging Infrastructure Act of 2026",
        "short_name": "NEVCIA",
        "dir": "20-EV-Charging-Infrastructure-Act",
        "funding": "$30 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, EV adoption challenge, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, transportation emissions data, EV market growth, charging infrastructure gap"},
            "03": {"name": "TITLE-I-NATIONAL-CHARGING-NETWORK", "title": "Title I — National EV Charging Network", "topic": "highway charging corridors, urban charging hubs, rural charging deployment, fast charging standards"},
            "04": {"name": "TITLE-II-RESIDENTIAL-CHARGING", "title": "Title II — Residential and Multi-Unit Dwelling Charging", "topic": "home charging incentives, apartment charging solutions, workplace charging, retrofit requirements"},
            "05": {"name": "TITLE-III-FLEET-ELECTRIFICATION", "title": "Title III — Fleet Electrification Program", "topic": "federal fleet electrification, postal service EVs, transit bus electrification, school bus electrification, delivery fleet conversion"},
            "06": {"name": "TITLE-IV-HEAVY-DUTY-EV-CHARGING", "title": "Title IV — Heavy-Duty and Commercial EV Charging", "topic": "truck stop charging, megawatt charging system, freight corridor infrastructure, depot charging systems"},
            "07": {"name": "TITLE-V-GRID-INTEGRATION", "title": "Title V — Grid Integration and Smart Charging", "topic": "V2G technology, smart charging standards, grid load management, renewable energy integration"},
            "08": {"name": "TITLE-VI-EV-WORKFORCE", "title": "Title VI — EV Infrastructure Workforce Development", "topic": "electrician training, charging station maintenance, EV technician certification, engineering programs"},
            "09": {"name": "TITLE-VII-EQUITY-ACCESS", "title": "Title VII — EV Equity and Access Programs", "topic": "disadvantaged community charging, used EV incentives, EV carshare programs, rural EV access"},
            "10": {"name": "TITLE-VIII-DOMESTIC-MANUFACTURING", "title": "Title VIII — Domestic Charger Manufacturing", "topic": "charger manufacturing incentives, Buy American requirements, supply chain resilience, export promotion"},
            "11": {"name": "TITLE-IX-STANDARDS-INTEROPERABILITY", "title": "Title IX — Charging Standards and Interoperability", "topic": "connector standards, payment system interoperability, open access requirements, reliability standards"},
            "12": {"name": "TITLE-X-ENVIRONMENTAL-ASSESSMENT", "title": "Title X — Environmental Review and Siting", "topic": "NEPA streamlining for charging stations, brownfish redevelopment, utility coordination, permitting efficiency"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, EV market projections, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act21": {
        "name": "National Climate Resilience and Adaptation Act of 2026",
        "short_name": "NCRAA",
        "dir": "21-Climate-Resilience-Adaptation-Act",
        "funding": "$90 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, climate risk assessment, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, climate disaster data, resilience gap analysis, future risk projections"},
            "03": {"name": "TITLE-I-COMMUNITY-RESILIENCE-GRANTS", "title": "Title I — Community Resilience Grants", "topic": "local resilience planning, community resilience centers, vulnerable population protection, heat mitigation"},
            "04": {"name": "TITLE-II-FLOOD-RESILIENCE", "title": "Title II — Flood Resilience and Stormwater Management", "topic": "flood control infrastructure, stormwater systems, levees and dams, floodplain restoration"},
            "05": {"name": "TITLE-III-WILDFIRE-RESILIENCE", "title": "Title III — Wildfire Resilience and Management", "topic": "forest management, defensible space programs, fire-resistant construction, early detection systems"},
            "06": {"name": "TITLE-IV-COMMUNITY-RELOCATION", "title": "Title IV — Managed Retreat and Community Relocation", "topic": "voluntary buyout programs, community relocation assistance, land use planning, displacement prevention"},
            "07": {"name": "TITLE-V-AGRICULTURE-RESILIENCE", "title": "Title V — Agricultural Climate Resilience", "topic": "drought-resistant farming, soil health programs, water-efficient agriculture, crop insurance reform"},
            "08": {"name": "TITLE-VI-HEAT-RESILIENCE", "title": "Title VI — Extreme Heat Resilience", "topic": "cooling centers, urban heat island mitigation, heat health warning systems, cool roof programs"},
            "09": {"name": "TITLE-VII-CLIMATE-DATA-SYSTEMS", "title": "Title VII — Climate Data and Prediction Systems", "topic": "national climate monitoring, predictive modeling, early warning systems, data sharing platforms"},
            "10": {"name": "TITLE-VIII-TRIBAL-RESILIENCE", "title": "Title VIII — Tribal Climate Resilience", "topic": "tribal relocation assistance, traditional ecological knowledge, tribal resilience planning, cultural site protection"},
            "11": {"name": "TITLE-IX-RESILIENCE-FINANCE", "title": "Title IX — Resilience Finance and Insurance", "topic": "resilience bonds, catastrophe reserves, insurance incentives, risk transfer mechanisms"},
            "12": {"name": "TITLE-X-CLIMATE-REFUGEE-PROGRAMS", "title": "Title X — Climate Displacement and Refugee Programs", "topic": "internal displacement assistance, climate refugee framework, cross-border cooperation, resettlement support"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, avoided damage benefits, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act22": {
        "name": "National Sustainable Buildings and Green Construction Act of 2026",
        "short_name": "NSBGCA",
        "dir": "22-Sustainable-Buildings-Green-Construction-Act",
        "funding": "$75 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, building emissions challenge, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, building sector emissions data, energy efficiency potential, green construction opportunity"},
            "03": {"name": "TITLE-I-BUILDING-ENERGY-CODES", "title": "Title I — National Building Energy Codes", "topic": "model energy code updates, net-zero ready buildings, code adoption incentives, building performance standards"},
            "04": {"name": "TITLE-II-EXISTING-BUILDING-RETROFIT", "title": "Title II — Existing Building Deep Retrofit Program", "topic": "residential retrofits, commercial building upgrades, heat pump deployment, workforce training for retrofits"},
            "05": {"name": "TITLE-III-FEDERAL-BUILDINGS", "title": "Title III — Federal Building Decarbonization", "topic": "federal building emissions targets, GSA net-zero portfolio, military installation efficiency, federal procurement standards"},
            "06": {"name": "TITLE-IV-GREEN-PUBLIC-HOUSING", "title": "Title IV — Green Public Housing Transformation", "topic": "PHA deep retrofits, affordable housing electrification, community solar for housing authorities, healthy homes standards"},
            "07": {"name": "TITLE-V-SCHOOL-BUILDINGS", "title": "Title V — Healthy Green Schools Program", "topic": "HVAC upgrades, indoor air quality, net-zero schools, student environmental health, school infrastructure funding"},
            "08": {"name": "TITLE-VI-SUSTAINABLE-MATERIALS", "title": "Title VI — Sustainable Construction Materials", "topic": "low-carbon concrete, mass timber construction, recycled content requirements, embodied carbon standards, Buy Clean procurement"},
            "09": {"name": "TITLE-VII-BUILDING-WORKFORCE", "title": "Title VII — Green Building Workforce Development", "topic": "energy auditor certification, heat pump installer training, building operator programs, construction skills upgrading"},
            "10": {"name": "TITLE-VIII-BUILDING-ELECTRIFICATION", "title": "Title VIII — Building Electrification Program", "topic": "all-electric new construction, gas system transition, electric-ready requirements, appliance efficiency standards"},
            "11": {"name": "TITLE-IX-SMART-BUILDINGS", "title": "Title IX — Smart Building and Grid Integration", "topic": "building automation, demand response, thermal energy storage, smart grid integration, building-to-grid services"},
            "12": {"name": "TITLE-X-ENVIRONMENTAL-JUSTICE", "title": "Title X — Environmental Justice and Healthy Communities", "topic": "lead paint abatement, asbestos removal, healthy housing standards, community health improvements, environmental justice mapping"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, energy savings benefits, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act23": {
        "name": "National Grid Modernization and Resilience Act of 2026",
        "short_name": "NGMRA",
        "dir": "23-Grid-Modernization-Resilience-Act",
        "funding": "$100 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, grid infrastructure challenge, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, grid reliability data, aging infrastructure, renewable integration requirements"},
            "03": {"name": "TITLE-I-TRANSMISSION-EXPANSION", "title": "Title I — National Transmission Expansion Program", "topic": "interregional transmission lines, transmission planning, rights-of-way, national interest electric transmission corridors"},
            "04": {"name": "TITLE-II-SMART-GRID-DEPLOYMENT", "title": "Title II — Smart Grid Technology Deployment", "topic": "advanced metering infrastructure, distribution automation, grid sensors, digital substations, grid management software"},
            "05": {"name": "TITLE-III-GRID-HARDENING", "title": "Title III — Grid Hardening and Weatherization", "topic": "wildfire mitigation, storm hardening, undergrounding, vegetation management, flood protection"},
            "06": {"name": "TITLE-IV-MICROGRIDS-ISLANDED-SYSTEMS", "title": "Title IV — Microgrid and Islanded Systems Program", "topic": "community microgrids, campus microgrids, critical facility resilience, tribal microgrids, military microgrids"},
            "07": {"name": "TITLE-V-GRID-INVERTER-STANDARDS", "title": "Title V — Grid Inverter and Interconnection Standards", "topic": "smart inverter requirements, interconnection reform, distributed energy resource integration, grid support functions"},
            "08": {"name": "TITLE-VI-DISTRIBUTION-GRID-MODERNIZATION", "title": "Title VI — Distribution Grid Modernization", "topic": "distribution system upgrades, voltage optimization, power quality, outage management, fault detection"},
            "09": {"name": "TITLE-VII-GRID-CYBERSECURITY", "title": "Title VII — Grid Cybersecurity and Physical Security", "topic": "SCADA security, supply chain security, physical security standards, incident response, security operations centers"},
            "10": {"name": "TITLE-VIII-GRID-WORKFORCE", "title": "Title VIII — Grid Workforce Development", "topic": "lineworker training, substation technician certification, grid engineer programs, cybersecurity workforce, apprenticeship programs"},
            "11": {"name": "TITLE-IX-RENEWABLE-INTEGRATION", "title": "Title IX — Renewable Energy Grid Integration", "topic": "variable generation management, curtailment reduction, forecasting systems, grid-forming inverters, renewable zones"},
            "12": {"name": "TITLE-X-GRID-FINANCE-INNOVATION", "title": "Title X — Grid Finance and Cost Allocation Reform", "topic": "transmission cost allocation, benefit-cost analysis frameworks, grid investment recovery, innovative rate design"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, reliability benefits, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act24": {
        "name": "National Advanced Manufacturing and Industrial Innovation Act of 2026",
        "short_name": "NAMIIA",
        "dir": "24-Advanced-Manufacturing-Industrial-Innovation-Act",
        "funding": "$85 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, manufacturing competitiveness challenge, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, manufacturing job loss data, innovation gap, global competition analysis"},
            "03": {"name": "TITLE-I-MANUFACTURING-USA-HUBS", "title": "Title I — Manufacturing USA Innovation Hubs", "topic": "regional manufacturing hubs, industry-university partnerships, technology transition, collaborative R&D facilities"},
            "04": {"name": "TITLE-II-ADVANCED-INDUSTRIAL-EQUIPMENT", "title": "Title II — Advanced Industrial Equipment Program", "topic": "smart factory deployment, industrial robotics, digital twin manufacturing, AI-driven process optimization"},
            "05": {"name": "TITLE-III-SUPPLY-CHAIN-RESILIENCE", "title": "Title III — Manufacturing Supply Chain Resilience", "topic": "critical supply chain mapping, domestic sourcing incentives, supplier diversification, reshoring programs"},
            "06": {"name": "TITLE-IV-INDUSTRIAL-ENERGY-EFFICIENCY", "title": "Title IV — Industrial Energy Efficiency Program", "topic": "waste heat recovery, industrial electrification, process optimization, energy management systems, CHP deployment"},
            "07": {"name": "TITLE-V-MANUFACTURING-WORKFORCE", "title": "Title V — Advanced Manufacturing Workforce", "topic": "industrial technician training, CNC operator certification, mechatronics programs, digital manufacturing skills"},
            "08": {"name": "TITLE-VI-ADDITIVE-MANUFACTURING", "title": "Title VI — Additive Manufacturing Initiative", "topic": "3D printing standards, metal additive manufacturing, aerospace applications, medical device printing, materials development"},
            "09": {"name": "TITLE-VII-BIOMANUFACTURING", "title": "Title VII — Biomanufacturing and Bioeconomy", "topic": "biopharmaceutical manufacturing, synthetic biology, bio-based chemicals, fermentation scale-up, bioprocessing workforce"},
            "10": {"name": "TITLE-VIII-SEMICONDUCTOR-MANUFACTURING", "title": "Title VIII — Semiconductor Manufacturing Expansion", "topic": "CHIPS Act implementation, fabrication facility construction, packaging and testing, equipment manufacturing, materials supply"},
            "11": {"name": "TITLE-IX-INDUSTRIAL-CYBERSECURITY", "title": "Title IX — Industrial Control Systems Cybersecurity", "topic": "ICS security standards, manufacturing system protection, threat intelligence sharing, incident response, supply chain security"},
            "12": {"name": "TITLE-X-SMALL-MANUFACTURER-TECH", "title": "Title X — Small Manufacturer Technology Extension", "topic": "MEP center expansion, technology adoption assistance, lean manufacturing consulting, digital transformation support"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, manufacturing output benefits, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act25": {
        "name": "National Environmental Remediation and Brownfield Redevelopment Act of 2026",
        "short_name": "NERBRA",
        "dir": "25-Environmental-Remediation-Brownfield-Redevelopment-Act",
        "funding": "$50 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, contamination challenge, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, superfund site data, brownfield inventory, environmental justice implications"},
            "03": {"name": "TITLE-I-SUPERFUND-ACCELERATION", "title": "Title I — Superfund Site Cleanup Acceleration", "topic": "site remediation technology, responsible party enforcement, orphan share funding, cleanup standards modernization"},
            "04": {"name": "TITLE-II-BROWNFIELD-REDEVELOPMENT", "title": "Title II — Brownfield Assessment and Redevelopment", "topic": "site assessment grants, cleanup revolving loan fund, redevelopment planning, liability protections, area-wide planning"},
            "05": {"name": "TITLE-III-ABANDONED-MINE-RECLAMATION", "title": "Title III — Abandoned Mine Land Reclamation", "topic": "mine reclamation technology, acid mine drainage treatment, land restoration, community economic transition"},
            "06": {"name": "TITLE-IV-PETROLEUM-BROWNFIELDS", "title": "Title IV — Petroleum Brownfield Cleanup", "topic": "underground storage tank sites, gas station redevelopment, petroleum contamination remediation, state cost-share programs"},
            "07": {"name": "TITLE-V-HEAVY-METALS-REMEDIATION", "title": "Title V — Heavy Metals and Emerging Contaminants", "topic": "lead contamination cleanup, PFAS remediation, mercury contamination, emerging contaminant research, health monitoring"},
            "08": {"name": "TITLE-VI-REMEDIATION-TECHNOLOGY", "title": "Title VI — Remediation Technology Development", "topic": "in-situ remediation, bioremediation, phytoremediation, nanoremediation, long-term monitoring technologies"},
            "09": {"name": "TITLE-VII-ENVIRONMENTAL-JUSTICE", "title": "Title VII — Environmental Justice Community Remediation", "topic": "overburdened community prioritization, cumulative impact assessment, community engagement, health-protective standards"},
            "10": {"name": "TITLE-VIII-REMEDIATION-WORKFORCE", "title": "Title VIII — Environmental Remediation Workforce", "topic": "remediation technician training, environmental scientist programs, community worker development, certification standards"},
            "11": {"name": "TITLE-IX-REDEVELOPMENT-FINANCE", "title": "Title IX — Redevelopment Finance and Incentives", "topic": "tax increment financing, new markets tax credits, opportunity zones, green infrastructure incentives, public-private partnerships"},
            "12": {"name": "TITLE-X-LAND-REUSE-STANDARDS", "title": "Title X — Land Reuse and Institutional Controls", "topic": "revitalization standards, institutional controls, long-term stewardship, beneficial reuse of remediated land"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, property value benefits, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act26": {
        "name": "National Offshore Wind and Marine Energy Act of 2026",
        "short_name": "NOWMEA",
        "dir": "26-Offshore-Wind-Marine-Energy-Act",
        "funding": "$45 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, offshore wind potential, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, offshore wind resource assessment, marine energy potential, economic opportunity"},
            "03": {"name": "TITLE-I-OFFSHORE-WIND-LEASING", "title": "Title I — Offshore Wind Leasing and Development", "topic": "BOEM lease auctions, wind energy areas, floating wind technology, lease stipulations, revenue sharing"},
            "04": {"name": "TITLE-II-OFFSHORE-WIND-PORTS", "title": "Title II — Offshore Wind Port Infrastructure", "topic": "staging ports, manufacturing ports, operations and maintenance ports, port workforce development"},
            "05": {"name": "TITLE-III-OFFSHORE-WIND-TRANSMISSION", "title": "Title III — Offshore Wind Transmission", "topic": "offshore transmission backbone, grid interconnection, HVDC transmission, state coordination"},
            "06": {"name": "TITLE-IV-WIND-WORKFORCE", "title": "Title IV — Offshore Wind Workforce Development", "topic": "mariner training, offshore safety certification, turbine technician programs, union partnerships"},
            "07": {"name": "TITLE-V-MARINE-ENERGY", "title": "Title V — Marine and Hydrokinetic Energy", "topic": "wave energy, tidal energy, ocean thermal energy, demonstration projects, technology testing"},
            "08": {"name": "TITLE-VI-ENVIRONMENTAL-PROTECTION", "title": "Title VI — Marine Environmental Protection", "topic": "marine mammal protection, fisheries coexistence, benthic habitat mitigation, environmental monitoring"},
            "09": {"name": "TITLE-VII-DOMESTIC-SUPPLY-CHAIN", "title": "Title VII — Domestic Wind Supply Chain", "topic": "turbine manufacturing, blade production, tower fabrication, nacelle assembly, installation vessels"},
            "10": {"name": "TITLE-VIII-STATE-REVENUE-SHARING", "title": "Title VIII — State Revenue Sharing and Cooperation", "topic": "coastal state revenue sharing, state energy planning, regional coordination, community benefit agreements"},
            "11": {"name": "TITLE-IX-INTERAGENCY-COORDINATION", "title": "Title IX — Interagency Coordination and Permitting", "topic": "BOEM-NOAA-DOD coordination, permitting timelines, environmental review efficiency, stakeholder engagement"},
            "12": {"name": "TITLE-X-RESEARCH-DEVELOPMENT", "title": "Title X — Offshore Wind Research and Development", "topic": "next-generation turbines, floating platform technology, corrosion protection, predictive maintenance"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, energy output benefits, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act27": {
        "name": "National Public Transit and Rail Modernization Act of 2026",
        "short_name": "NPTRMA",
        "dir": "27-Public-Transit-Rail-Modernization-Act",
        "funding": "$95 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, transit infrastructure deficit, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, transit ridership data, rail infrastructure condition, state of good repair backlog"},
            "03": {"name": "TITLE-I-BUS-RAPID-TRANSIT", "title": "Title I — Bus Rapid Transit Expansion", "topic": "BRT corridor development, dedicated lanes, station infrastructure, fleet electrification, signal priority"},
            "04": {"name": "TITLE-II-LIGHT-RAIL-EXPANSION", "title": "Title II — Light Rail and Streetcar Expansion", "topic": "new light rail lines, streetcar systems, vehicle procurement, track infrastructure, systems integration"},
            "05": {"name": "TITLE-III-COMMUTER-RAIL", "title": "Title III — Commuter Rail Modernization", "topic": "fleet replacement, station upgrades, signal modernization, electrification, service frequency improvements"},
            "06": {"name": "TITLE-IV-HIGH-SPEED-RAIL", "title": "Title IV — High-Speed Rail Development", "topic": "corridor planning, dedicated track construction, trainset procurement, station development, environmental review"},
            "07": {"name": "TITLE-V-AMTRAK-NETWORK", "title": "Title V — Amtrak National Network", "topic": "long-distance route restoration, Northeast Corridor modernization, fleet renewal, station accessibility"},
            "08": {"name": "TITLE-VI-TRANSIT-ORIENTED-DEVELOPMENT", "title": "Title VI — Transit-Oriented Development", "topic": "station area planning, affordable housing near transit, joint development, value capture financing"},
            "09": {"name": "TITLE-VII-ZERO-EMISSSION-BUSES", "title": "Title VII — Zero-Emission Bus Fleet Transition", "topic": "electric bus procurement, hydrogen fuel cell buses, charging infrastructure, depot upgrades"},
            "10": {"name": "TITLE-VIII-TRANSIT-SAFETY", "title": "Title VIII — Transit Safety and Security", "topic": "positive train control, bus operator safety, station security, emergency preparedness, cybersecurity"},
            "11": {"name": "TITLE-IX-TRANSIT-WORKFORCE", "title": "Title IX — Transit Workforce Development", "topic": "operator training, mechanic certification, engineer programs, apprenticeship programs, workforce retention"},
            "12": {"name": "TITLE-X-RURAL-TRANSIT", "title": "Title X — Rural and Small Community Transit", "topic": "demand-response systems, intercity bus service, mobility as a service, rural transit funding formulas"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, mobility benefits, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act28": {
        "name": "National Solar Energy and Distributed Generation Act of 2026",
        "short_name": "NSEDGA",
        "dir": "28-Solar-Energy-Distributed-Generation-Act",
        "funding": "$55 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, solar energy potential, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, solar resource data, distributed generation benefits, cost reduction trajectory"},
            "03": {"name": "TITLE-I-UTILITY-SCALE-SOLAR", "title": "Title I — Utility-Scale Solar Deployment", "topic": "large-scale solar farms, solar energy zones, transmission access, power purchase agreements, permitting reform"},
            "04": {"name": "TITLE-II-RESIDENTIAL-SOLAR", "title": "Title II — Residential and Community Solar", "topic": "rooftop solar incentives, community solar gardens, low-income solar, solarize campaigns, net metering standards"},
            "05": {"name": "TITLE-III-SOLAR-MANUFACTURING", "title": "Title III — Domestic Solar Manufacturing", "topic": "solar cell production, module assembly, inverter manufacturing, polysilicon production, supply chain resilience"},
            "06": {"name": "TITLE-IV-SOLAR-WORKFORCE", "title": "Title IV — Solar Energy Workforce Development", "topic": "solar installer certification, electrician training, engineering programs, apprenticeship standards"},
            "07": {"name": "TITLE-V-SOLAR-RECYCLING", "title": "Title V — Solar Panel Recycling and End-of-Life", "topic": "panel recycling requirements, material recovery, extended producer responsibility, recycling infrastructure"},
            "08": {"name": "TITLE-VI-AGRIVOLTAICS", "title": "Title VI — Agrivoltaics and Land Use", "topic": "dual-use solar farming, grazing compatibility, crop production under panels, land use planning"},
            "09": {"name": "TITLE-VII-SOLAR-GRID-INTEGRATION", "title": "Title VII — Solar Grid Integration and Forecasting", "topic": "solar forecasting systems, grid flexibility, curtailment reduction, inverter standards, ride-through requirements"},
            "10": {"name": "TITLE-VIII-FLOATING-SOLAR", "title": "Title VIII — Floating and Novel Solar Applications", "topic": "floatovoltaics, building-integrated solar, solar canopies, space-based solar research"},
            "11": {"name": "TITLE-IX-SOLAR-RESEARCH", "title": "Title IX — Next-Generation Solar Research", "topic": "perovskite cells, tandem cells, concentrated solar power, solar fuels, efficiency records"},
            "12": {"name": "TITLE-X-ENVIRONMENTAL-REVIEW", "title": "Title X — Solar Permitting and Environmental Review", "topic": "NEPA categorical exclusions, environmental review timelines, wildlife considerations, desert solar guidelines"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, energy cost savings, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act29": {
        "name": "National Nuclear Waste Management and Advanced Reactor Fuel Act of 2026",
        "short_name": "NNWMA",
        "dir": "29-Nuclear-Waste-Advanced-Reactor-Fuel-Act",
        "funding": "$40 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, nuclear waste challenge, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressorial findings, spent fuel inventory, repository program status, advanced fuel cycle potential"},
            "03": {"name": "TITLE-I-CONSENT-BASED-SITING", "title": "Title I — Consent-Based Siting for Waste Facilities", "topic": "community engagement, consent agreements, economic incentives, tribal consultation, siting process"},
            "04": {"name": "TITLE-II-INTERIM-STORAGE", "title": "Title II — Interim Storage Facilities", "topic": "consolidated interim storage, transportation requirements, security standards, emergency preparedness"},
            "05": {"name": "TITLE-III-PERMANENT-REPOSITORY", "title": "Title III — Permanent Geological Repository", "topic": "Yucca Mountain alternative, deep geological disposal, waste package design, closure planning"},
            "06": {"name": "TITLE-IV-ADVANCED-FUEL-CYCLE", "title": "Title IV — Advanced Fuel Cycle and Recycling", "topic": "spent fuel reprocessing, fast reactor fuel, closed fuel cycle, transmutation research, waste reduction"},
            "07": {"name": "TITLE-V-TRANSPORTATION-SAFETY", "title": "Title V — Nuclear Waste Transportation Safety", "topic": "transport cask standards, route planning, emergency response, security requirements, NRC certification"},
            "08": {"name": "TITLE-VI-WASTE-WORKFORCE", "title": "Title VI — Nuclear Waste Management Workforce", "topic": "radiological technician training, transportation specialists, repository engineers, health physics programs"},
            "09": {"name": "TITLE-VII-ENVIRONMENTAL-REMEDIATION", "title": "Title VII — Legacy Site Environmental Remediation", "topic": "Manhattan Project sites, uranium mill tailings, groundwater remediation, long-term stewardship"},
            "10": {"name": "TITLE-VIII-ADVANCED-REACTOR-FUEL", "title": "Title VIII — Advanced Reactor Fuel Development", "topic": "HALEU production, TRISO fuel, accident tolerant fuels, fuel qualification, enrichment capability"},
            "11": {"name": "TITLE-IX-INTERNATIONAL-COOPERATION", "title": "Title IX — International Nuclear Waste Cooperation", "topic": "bilateral agreements, technology exchange, non-proliferation, international repository concepts"},
            "12": {"name": "TITLE-X-PUBLIC-ENGAGEMENT", "title": "Title X — Public Engagement and Stakeholder Involvement", "topic": "public comment processes, advisory committees, tribal nations engagement, environmental justice"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, waste management benefits, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act30": {
        "name": "National Precision Agriculture and Food Security Act of 2026",
        "short_name": "NPAFSA",
        "dir": "30-Precision-Agriculture-Food-Security-Act",
        "funding": "$35 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, food security challenge, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, agricultural productivity data, food supply chain vulnerabilities, climate impacts on agriculture"},
            "03": {"name": "TITLE-I-PRECISION-AGRICULTURE-TECHNOLOGY", "title": "Title I — Precision Agriculture Technology Deployment", "topic": "GPS-guided equipment, drone crop monitoring, variable rate technology, soil sensors, automated irrigation systems"},
            "04": {"name": "TITLE-II-VERTICAL-FARMING", "title": "Title II — Vertical and Controlled Environment Agriculture", "topic": "indoor farming facilities, hydroponics, aeroponics, aquaponics, urban food production, energy-efficient lighting"},
            "05": {"name": "TITLE-III-AGRICULTURAL-BIOTECHNOLOGY", "title": "Title III — Agricultural Biotechnology and Crop Science", "topic": "drought-resistant crops, gene editing, soil microbiome research, pest-resistant varieties, yield optimization"},
            "06": {"name": "TITLE-IV-FOOD-PROCESSING-TECHNOLOGY", "title": "Title IV — Food Processing and Reduction Technology", "topic": "food waste reduction, cold chain logistics, processing automation, packaging innovation, shelf-life extension"},
            "07": {"name": "TITLE-V-RURAL-BROADBAND-AGRICULTURE", "title": "Title V — Rural Broadband for Agricultural Applications", "topic": "farm connectivity, IoT livestock monitoring, telemedicine for rural areas, agricultural data platforms"},
            "08": {"name": "TITLE-VI-AGRICULTURAL-WORKFORCE", "title": "Title VI — Agricultural Technology Workforce", "topic": "precision ag technician training, drone operator certification, agricultural data scientists, farm management software specialists"},
            "09": {"name": "TITLE-VII-FOOD-SECURITY-RESILIENCE", "title": "Title VII — Domestic Food Supply Chain Resilience", "topic": "strategic food reserves, domestic production capacity, supply chain mapping, emergency food distribution"},
            "10": {"name": "TITLE-VIII-INTERNATIONAL-AGRICULTURAL-TRADE", "title": "Title VIII — International Agricultural Trade and Standards", "topic": "export promotion, sanitary standards, trade agreement compliance, foreign market development"},
            "11": {"name": "TITLE-IX-AGRICULTURAL-RESEARCH", "title": "Title IX — Agricultural Research and Development", "topic": "USDA research stations, university partnerships, climate adaptation research, crop breeding programs"},
            "12": {"name": "TITLE-X-TRIBAL-AGRICULTURE", "title": "Title X — Tribal Agriculture and Food Sovereignty", "topic": "tribal farming programs, traditional food systems, reservation food access, tribal agricultural research"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, food security benefits, domestic content requirements, cost-benefit analysis"}
        }
    },
    "act31": {
        "name": "National Ocean Resources and Marine Economy Act of 2026",
        "short_name": "NOMEA",
        "dir": "31-Ocean-Resources-Marine-Economy-Act",
        "funding": "$40 billion",
        "funding_period": "Fiscal Years 2027-2036",
        "sections": {
            "00": {"name": "BILL-TITLE-AND-NUMBER", "title": "Bill Title and Number", "topic": "legislative identification, short title, table of contents, congressional session details"},
            "01": {"name": "EXECUTIVE-SUMMARY", "title": "Executive Summary", "topic": "overview, blue economy potential, program architecture, key provisions, economic projections"},
            "02": {"name": "FINDINGS-AND-DECLARATIONS", "title": "Findings and Declarations", "topic": "congressional findings, ocean resource data, marine economy potential, coastal community needs"},
            "03": {"name": "TITLE-I-MARINE-RENEWABLE-ENERGY", "title": "Title I — Marine Renewable Energy Development", "topic": "tidal energy, wave energy, ocean current power, offshore solar, marine energy testing facilities"},
            "04": {"name": "TITLE-II-SUSTAINABLE-FISHERIES", "title": "Title II — Sustainable Fisheries and Aquaculture", "topic": "fish stock restoration, sustainable aquaculture, fishing gear innovation, marine habitat protection"},
            "05": {"name": "TITLE-III-MARINE-BIOTECHNOLOGY", "title": "Title III — Marine Biotechnology and Pharmaceuticals", "topic": "marine-derived pharmaceuticals, ocean biomaterials, marine organism research, blue biotechnology"},
            "06": {"name": "TITLE-IV-OCEAN-MINING-RESOURCES", "title": "Title IV — Deep Sea Mineral Resources", "topic": "polymetallic nodules, seafloor massive sulfides, cobalt-rich crusts, environmental safeguards, international seabed authority"},
            "07": {"name": "TITLE-V-COASTAL-INFRASTRUCTURE", "title": "Title V — Coastal Resilience Infrastructure", "topic": "living shorelines, coral reef restoration, coastal erosion protection, storm surge barriers"},
            "08": {"name": "TITLE-VI-MARINE-WORKFORCE", "title": "Title VI — Marine Industry Workforce Development", "topic": "maritime training, offshore safety certification, marine biologist programs, ocean engineering education"},
            "09": {"name": "TITLE-VII-OCEAN-DATA-SYSTEMS", "title": "Title VII — Ocean Observation and Data Systems", "topic": "ocean monitoring networks, satellite oceanography, data sharing platforms, predictive modeling"},
            "10": {"name": "TITLE-VIII-MARITIME-TRANSPORTATION", "title": "Title VIII — Sustainable Maritime Transportation", "topic": "green shipping, port electrification, alternative marine fuels, vessel efficiency standards"},
            "11": {"name": "TITLE-IX-OCEAN-CONSERVATION", "title": "Title IX — Marine Conservation and Protected Areas", "topic": "marine protected areas, habitat restoration, species protection, ocean acidification mitigation"},
            "12": {"name": "TITLE-X-TRIBAL-MARINE-RESOURCES", "title": "Title X — Tribal Marine Resource Rights", "topic": "tribal fishing rights, coastal tribal access, traditional marine knowledge, tribal conservation areas"},
            "13": {"name": "FUNDING-AND-IMPLEMENTATION", "title": "Title XI — Funding and Implementation", "topic": "Authorization of appropriations, allocation among programs, oversight and GAO audit, implementation schedule"},
            "14": {"name": "ECONOMIC-IMPACT-AND-REFERENCES", "title": "Title XII — Economic Impact and References", "topic": "Economic impact projections, blue economy benefits, domestic content requirements, cost-benefit analysis"}
        }
    }
}