#!/usr/bin/env bash
# ─── VOICE RECOGNITION COMMAND VALIDATOR ───────────────────────────────────
# Prevents nonsensical commands from voice recognition errors
# Checks input against valid command dictionary with fuzzy matching
# ════════════════════════════════════════════════════════════════════════════

# ─── VALID COMMAND DICTIONARY ──────────────────────────────────────────────
# Format: "canonical_command|alias1|alias2|..."
# All entries use double quotes; internal single quotes are escaped
VOICE_VALID_COMMANDS=(
    "git|jit|guit|gat|get"
    "git status|git stat|git stats"
    "git log|git login|git blog"
    "git add|git at|git as"
    "git commit|git comit|git come it"
    "git push|git pulled|git bush"
    "git pull|git pool|git bull"
    "git checkout|git check out"
    "git branch|git ranch"
    "git merge|git marge"
    "git diff|git stiff|git if"
    "git clone|git clown|git alone"
    "git stash|git stash"
    "git rebase|git base"
    "git reset|git reset"
    "git remote|git mote"
    "git fetch|git fetch"
    "git init|git unit"
    "git tag|git tab"
    "ls|ell ess|ellis|aless|list"
    "cd|see dee|seed"
    "cat|kat|cut"
    "rm|are em|remove|are move"
    "mv|em vee|move"
    "cp|see pee|copy"
    "mkdir|make dir|make direct"
    "pwd|print working"
    "echo|eko"
    "grep|grip|group"
    "find|fine|fined"
    "chmod|mod"
    "chown|own"
    "sudo|pseudo|sue doo"
    "apt|at|a pt"
    "npm|en pea em|npm install"
    "node|not|no"
    "python|pie tone|piton"
    "pip|pee eye pee"
    "docker|dock|docker"
    "zip|zipp"
    "unzip|un zipp"
    "tar|star"
    "wget|w get"
    "curl|see url|coal|girl"
    "ssh|ess ess aich"
    "scp|ess see pee"
    "ping|pink"
    "ps|pee ess"
    "kill|keel"
    "top|tap"
    "df|dee eff|disk free"
    "du|dee you|disk usage"
    "free|tree"
    "man|manual"
    "vim|vi im"
    "nano|nano"
    "code|vs code"
    "exit|ex it|quit"
    "help|hell|helm"
    "clear|clean|claire"
    "history|histo"
    "alias|alias"
    "source|surge"
    "export|experts"
    "env|environment"
    "which|witch"
    "whoami|who am i"
    "date|day"
    "time|tyme"
    "sleep|sleep"
    "yes|yea|yas"
    "no|nope|nah"
    "all|awl"
    "run|ran|runner"
    "start|starters|starter"
    "stop|stap"
    "restart|re start"
    "status|stat"
    "create|crate|krait"
    "delete|deletes|d lee"
    "update|updates|up date"
    "verify|verifies|very"
    "organize|organise|org an ize"
    "concat|con cat|concatenate"
    "clean|cleanse"
    "commit|comit|subit"
    "push|pull"
    "merge|merges"
    "branch|branches"
    "clone|clones"
    "article|artickle|artical"
    "piece|peace|peel"
    "chapter|chaptr"
    "section|secton"
    "document|docment|dock"
    "research|re search|reaserch"
    "prime|primes|pryme"
    "electron|electrons|elec"
    "holographic|holo|holgraphic"
    "universe|univers|univers"
    "subatomic|sub atom|subatom"
    "physics|physiks|physic"
    "quantum|quntum|quantom"
    "theory|theroy|theorey"
    "framework|frame work"
    "analysis|analisis|analsis"
    "synthesis|sythsis"
    "methodology|methodolgy"
    "foundation|foun dation"
    "infrastructure|infrastrcure"
    "deployment|deploy"
    "execution|exectuion"
    "validation|valdaton"
    "verification|verificaton"
    "optimization|optimizaton"
    "configuration|config"
    "initialization|init"
    "orchestration|orchestraton"
    "heartbeat|heart beat"
    "session|seshun|sessn"
    "workspace|work space"
    "directory|directry|directoy"
    "folder|foler|foder"
    "file|fill|fiel"
    "content|contnt"
    "progress|progres"
    "complete|compleat|complt"
    "pending|pendng"
    "active|actve"
    "priority|priorty"
    "target|targt"
    "metric|metrc"
    "dashboard|dash board"
    "inventory|invntory"
    "manifest|manfest"
    "log|logue"
    "record|recrd"
    "report|reprt"
    "summary|summry"
    "detail|detal"
    "overview|overvew"
    "outline|outln"
    "index|indx"
    "reference|refrnce"
    "appendix|appendx"
    "glossary|gossary"
    "bibliography|bibligraphy"
    "citation|citaion"
    "footnote|footnot"
    "header|heder"
    "footer|foter"
    "margin|mrgin"
    "paragraph|paragaph"
    "sentence|sentnce"
    "keyword|key word"
    "metadata|metdata"
    "template|templet"
    "pattern|pttern"
    "structure|structre"
    "function|functon"
    "variable|varable"
    "parameter|paramter"
    "argument|argumnt"
    "return|retrn"
    "boolean|boolen"
    "integer|intger"
    "string|strng"
    "array|aray"
    "object|objct"
    "class|clss"
    "method|methd"
    "property|proprty"
    "interface|interfce"
    "module|modle"
    "package|packge"
    "library|libary"
    "platform|platfrm"
    "environment|envirnmt"
    "instance|instnce"
    "service|servce"
    "endpoint|endpont"
    "request|requst"
    "response|responce"
    "connection|conncton"
    "database|datbase"
    "query|querry"
    "result|reslt"
    "error|eror"
    "warning|warnng"
    "exception|excepion"
    "debug|debu"
    "trace|trce"
    "profile|profil"
    "benchmark|benchmrk"
    "performance|prfrmnce"
    "latency|lateny"
    "throughput|thrughput"
    "bandwidth|bandwdth"
    "storage|storag"
    "memory|memry"
    "processor|procesor"
    "network|netwrk"
    "security|securty"
    "authentication|auth"
    "authorization|authz"
    "encryption|encrypton"
    "decryption|decrypton"
    "compression|compresson"
    "decompression|decompresson"
    "upload|upld"
    "download|downld"
    "transfer|transfr"
    "sync|snyc"
    "backup|bakup"
    "restore|restor"
    "archive|archve"
    "extract|extrct"
    "import|imprt"
    "export|exprt"
    "convert|convrt"
    "transform|transfrm"
    "generate|genrate"
    "calculate|calc"
    "evaluate|eval"
    "measure|measre"
    "compare|compar"
    "sort|srt"
    "filter|flter"
    "search|serch"
    "replace|replce"
    "insert|insrt"
    "append|apend"
    "prepend|prepend"
    "remove|rmove"
    "rename|renme"
    "copy|cpy"
    "move|mve"
    "paste|pste"
    "undo|undoo"
    "redo|redoo"
    "save|sv"
    "load|lod"
    "open|opn"
    "close|clse"
    "new|nu"
    "old|ol"
    "first|frst"
    "last|lst"
    "next|nxt"
    "previous|prev"
    "current|currnt"
    "total|totl"
    "average|avg"
    "minimum|min"
    "maximum|max"
    "sum|sm"
    "count|cnt"
    "percentage|pct"
    "ratio|rat"
    "proportion|proportn"
    "frequency|freq"
    "distribution|dist"
    "probability|prob"
    "statistics|stats"
    "correlation|corr"
    "regression|regress"
    "variance|var"
    "deviation|dev"
    "accuracy|acc"
    "precision|prec"
    "recall|rec"
    "score|scr"
    "rank|rnk"
    "grade|grde"
    "level|lvl"
    "tier|ter"
    "category|cat"
    "type|typ"
    "kind|knd"
    "class|cls"
    "group|grp"
    "set|st"
    "list|lst"
    "map|mp"
    "dict|dct"
    "tuple|tple"
    "enum|enm"
    "union|unin"
    "struct|strct"
    "field|fld"
    "record|rec"
    "row|rw"
    "column|col"
    "table|tbl"
    "index|idx"
    "key|ky"
    "value|val"
    "pair|pr"
    "range|rng"
    "interval|intvl"
    "period|prd"
    "duration|duratn"
    "timestamp|ts"
    "timezone|tz"
    "calendar|cal"
    "schedule|sched"
    "deadline|deadln"
    "milestone|ms"
    "deliverable|dlvrbl"
    "requirement|req"
    "specification|spec"
    "constraint|constrn"
    "assumption|assump"
    "dependency|dep"
    "prerequisite|preq"
    "postcondition|post"
    "precondition|pre"
    "invariant|invrnt"
    "assertion|assert"
    "guarantee|guar"
    "promise|prom"
    "commitment|cmtmt"
    "obligation|oblig"
    "responsibility|resp"
    "accountability|acct"
    "transparency|trans"
    "integrity|integ"
    "authenticity|authn"
    "confidentiality|conf"
    "availability|avail"
    "reliability|reliab"
    "maintenance|maint"
    "support|supprt"
    "documentation|doc"
    "instruction|instr"
    "guideline|guide"
    "standard|std"
    "convention|conv"
    "protocol|proto"
    "procedure|proc"
    "process|procs"
    "workflow|wf"
    "pipeline|pipe"
    "lifecycle|lc"
    "iteration|iter"
    "sprint|sprnt"
    "release|rls"
    "version|ver"
    "edition|ed"
    "revision|rev"
    "patch|pch"
    "update|upd"
    "upgrade|upg"
    "migration|migr"
    "transition|trans"
    "transformation|transfm"
    "evolution|evol"
    "revolution|revol"
    "innovation|innov"
    "improvement|imprv"
    "enhancement|enhnc"
    "optim|optim"
    "refactoring|refact"
    "restructuring|restr"
    "reorganization|reorg"
    "consolidation|consol"
    "integration|integr"
    "separation|sep"
    "combination|comb"
    "merging|mrg"
    "splitting|split"
    "dividing|div"
    "multiplying|mult"
    "adding|add"
    "subtracting|sub"
    "modulo|mod"
    "division|div"
    "exponent|exp"
    "logarithm|log"
    "root|rt"
    "power|pow"
    "base|bs"
    "factor|fctr"
    "multiple|multpl"
    "divisor|divs"
    "quotient|quot"
    "remainder|rem"
    "fraction|frac"
    "decimal|dec"
    "hexadecimal|hex"
    "binary|bin"
    "octal|oct"
    "ascii|asc"
    "unicode|uni"
    "utf|utf"
    "encoding|enc"
    "decoding|dec"
    "serialization|ser"
    "deserialization|deser"
    "marshalling|marsh"
    "unmarshalling|unmarsh"
    "parsing|parse"
    "formatting|fmt"
    "printing|print"
    "displaying|disp"
    "rendering|render"
    "drawing|draw"
    "painting|paint"
    "sketching|sketch"
    "drafting|draft"
    "writing|write"
    "reading|read"
    "editing|edit"
    "deleting|delete"
    "inserting|insert"
    "updating|update"
    "querying|query"
    "fetching|fetch"
    "retrieving|retrieve"
    "storing|store"
    "caching|cache"
    "buffering|buf"
    "queuing|queue"
    "stacking|stack"
    "linking|link"
    "chaining|chain"
    "nesting|nest"
    "embedding|embed"
    "wrapping|wrap"
    "unwrapping|unwrap"
    "packing|pack"
    "unpacking|unpack"
    "compressing|compress"
    "depressing|decompress"
    "encrypting|encrypt"
    "decrypting|decrypt"
    "hashing|hash"
    "signing|sign"
    "verifying|verify"
    "validating|validate"
    "authenticating|auth"
    "authorizing|authorize"
    "permitting|permit"
    "denying|deny"
    "rejecting|reject"
    "accepting|accept"
    "approving|approve"
    "confirming|confirm"
    "acknowledging|ack"
    "responding|respond"
    "requesting|request"
    "polling|poll"
    "subscribing|sub"
    "publishing|pub"
    "broadcasting|broadcast"
    "multicasting|multicast"
    "unicast|unicast"
    "anycast|anycast"
    "streaming|stream"
    "recording|record"
    "capturing|capture"
    "sampling|sample"
    "measuring|measure"
    "weighing|weigh"
    "counting|count"
    "calculating|calc"
    "estimating|est"
    "predicting|predict"
    "forecasting|forecast"
    "projecting|project"
    "planning|plan"
    "scheduling|schedule"
    "allocating|allocate"
    "assigning|assign"
    "distributing|distribute"
    "balancing|balance"
    "scaling|scale"
    "resizing|resize"
    "cropping|crop"
    "trimming|trim"
    "padding|pad"
    "aligning|align"
    "centering|center"
    "justifying|justify"
    "formatting|format"
    "styling|style"
    "theming|theme"
    "coloring|color"
    "shading|shade"
    "lighting|light"
    "shadowing|shadow"
    "blending|blend"
    "mixing|mix"
    "composing|compose"
    "arranging|arrange"
    "ordering|order"
    "sequencing|sequence"
    "ranking|rank"
    "prioritizing|prioritize"
    "weighting|weight"
    "scoring|score"
    "grading|grade"
    "marking|mark"
    "tagging|tag"
    "labeling|label"
    "naming|name"
    "titling|title"
    "heading|head"
    "subheading|subhead"
    "caption|cap"
    "legend|legend"
    "annotation|anno"
    "comment|cmt"
    "note|nte"
    "remark|rmk"
    "observation|obs"
    "finding|fnd"
    "discovery|disc"
    "insight|ins"
    "conclusion|conc"
    "recommendation|rec"
    "suggestion|sugg"
    "proposal|prop"
    "offer|off"
    "bid|bd"
    "tender|tndr"
    "quote|qt"
    "estimate|est"
    "budget|bud"
    "cost|cst"
    "price|prc"
    "value|val"
    "worth|wrth"
    "benefit|bene"
    "advantage|adv"
    "disadvantage|disadv"
    "risk|rsk"
    "threat|thrt"
    "opportunity|opp"
    "challenge|chal"
    "problem|prob"
    "issue|iss"
    "bug|bg"
    "defect|def"
    "flaw|flw"
    "mistake|mstk"
    "fault|flt"
    "failure|fail"
    "success|succ"
    "achievement|ach"
    "accomplishment|acmp"
    "goal|gl"
    "objective|obj"
    "aim|am"
    "purpose|purp"
    "intent|int"
    "mission|msn"
    "vision|vsn"
    "strategy|strat"
    "tactic|tact"
    "approach|app"
    "technique|tech"
    "practice|prac"
    "exercise|exer"
    "example|ex"
    "sample|smp"
    "instance|inst"
    "case|cse"
    "scenario|scen"
    "situation|sit"
    "condition|cond"
    "state|st"
    "phase|ph"
    "stage|stg"
    "step|stp"
    "layer|lyr"
    "stratum|strat"
    "dimension|dim"
    "aspect|asp"
    "facet|fct"
    "element|elem"
    "component|comp"
    "part|prt"
    "section|sec"
    "segment|seg"
    "fragment|frag"
    "portion|port"
    "share|shr"
    "slice|slc"
    "chunk|chk"
    "block|blk"
    "unit|unt"
    "package|pkg"
    "bundle|bndl"
    "collection|coll"
    "batch|btch"
    "cluster|clst"
    "series|ser"
    "sequence|seq"
    "chain|chn"
    "string|str"
    "matrix|mat"
    "vector|vec"
    "tensor|tens"
    "scalar|scal"
    "point|pt"
    "line|ln"
    "curve|crv"
    "surface|surf"
    "volume|vol"
    "area|ar"
    "length|len"
    "width|wid"
    "height|hgt"
    "depth|dep"
    "radius|rad"
    "diameter|dia"
    "circumference|circ"
    "angle|ang"
    "degree|deg"
    "radian|rad"
    "gradient|grad"
    "slope|slp"
    "intercept|int"
    "origin|org"
    "axis|ax"
    "plane|pln"
    "box|box"
    "sphere|sph"
    "capsule|cap"
    "cylinder|cyl"
    "cone|cone"
    "torus|tor"
    "grid|grid"
    "lattice|lat"
    "crystal|cry"
    "atom|atom"
    "molecule|mol"
    "compound|comp"
    "mixture|mix"
    "solution|sol"
    "suspension|susp"
    "emulsion|emul"
    "colloid|col"
    "gel|gel"
    "foam|foam"
    "aerosol|aero"
    "plasma|plas"
    "gas|gas"
    "liquid|liq"
    "solid|sol"
    "fluid|flu"
    "vapor|vap"
    "steam|stm"
    "smoke|smk"
    "dust|dst"
    "particle|part"
    "grain|grn"
    "powder|pdr"
    "fiber|fbr"
    "film|flm"
    "sheet|sht"
    "plate|plt"
    "rod|rod"
    "bar|bar"
    "tube|tube"
    "pipe|pipe"
    "wire|wire"
    "cable|cbl"
    "cord|crd"
    "rope|rope"
    "belt|belt"
    "strap|strp"
    "tape|tape"
    "glue|glue"
    "cement|cem"
    "adhesive|adh"
    "sealant|seal"
    "coating|coat"
    "paint|paint"
    "varnish|var"
    "lacquer|lac"
    "finish|fin"
    "polish|pol"
    "wax|wax"
    "oil|oil"
    "grease|grease"
    "lubricant|lub"
    "fuel|fuel"
    "energy|enrgy"
    "power|pwr"
    "force|force"
    "torque|torq"
    "pressure|pres"
    "stress|strs"
    "strain|strn"
    "tension|tens"
    "shear|shr"
    "bending|bend"
    "torsion|tors"
    "fatigue|fat"
    "fracture|frac"
    "creep|creep"
    "wear|wear"
    "corrosion|corr"
    "erosion|ero"
    "oxidation|oxi"
    "reduction|red"
    "reaction|rxn"
    "catalyst|cat"
    "enzyme|enz"
    "hormone|hor"
    "protein|prot"
    "amino|aa"
    "acid|acid"
    "base|base"
    "salt|salt"
    "ion|ion"
    "proton|prot"
    "neutron|neut"
    "photon|phot"
    "boson|bos"
    "fermion|ferm"
    "quark|quark"
    "lepton|lept"
    "gluon|glu"
    "graviton|grav"
    "higgs|higgs"
    "neutrino|neut"
)

# ─── FUZZY MATCHING ENGINE ─────────────────────────────────────────────────
levenshtein() {
    local s1="$1"
    local s2="$2"
    local len1=${#s1}
    local len2=${#s2}

    [[ "$s1" == "$s2" ]] && echo 0 && return
    [[ $len1 -eq 0 ]] && echo $len2 && return
    [[ $len2 -eq 0 ]] && echo $len1 && return

    if [[ $len1 -eq $len2 ]]; then
        local diffs=0
        for (( i=0; i<len1; i++ )); do
            [[ "${s1:$i:1}" != "${s2:$i:1}" ]] && ((diffs++))
        done
        echo $diffs
        return
    fi

    local diff=$((len1 > len2 ? len1 - len2 : len2 - len1))
    echo $((diff + 1))
}

# ─── COMMAND VALIDATOR ──────────────────────────────────────────────────────
validate_voice_command() {
    local input="$1"
    local input_lower
    input_lower=$(echo "$input" | tr '[:upper:]' '[:lower:]' | sed "s/[^a-z0-9 ]//g" | sed "s/^ *//;s/ *$//")

    [[ -z "$input_lower" ]] && echo "EMPTY" && return 1

    for cmd_entry in "${VOICE_VALID_COMMANDS[@]}"; do
        IFS='|' read -ra parts <<< "$cmd_entry"
        for part in "${parts[@]}"; do
            local part_lower
            part_lower=$(echo "$part" | tr '[:upper:]' '[:lower:]' | sed "s/^ *//;s/ *$//")
            if [[ "$input_lower" == "$part_lower" ]]; then
                echo "VALID:${parts[0]}"
                return 0
            fi
        done
    done

    local best_match=""
    local best_score=999
    local threshold=3

    for cmd_entry in "${VOICE_VALID_COMMANDS[@]}"; do
        IFS='|' read -ra parts <<< "$cmd_entry"
        for part in "${parts[@]}"; do
            local part_lower
            part_lower=$(echo "$part" | tr '[:upper:]' '[:lower:]' | sed "s/^ *//;s/ *$//")
            local score
            score=$(levenshtein "$input_lower" "$part_lower")
            if [[ $score -lt $best_score && $score -le $threshold ]]; then
                best_score=$score
                best_match="${parts[0]}"
            fi
        done
    done

    if [[ -n "$best_match" ]]; then
        echo "SUGGEST:$best_match"
        return 2
    fi

    echo "INVALID"
    return 1
}

# ─── BATCH VALIDATOR ────────────────────────────────────────────────────────
validate_command_list() {
    local commands=("$@")
    local valid_count=0
    local suggest_count=0
    local invalid_count=0

    echo "═══════════════════════════════════════════════════"
    echo "  VOICE COMMAND VALIDATION REPORT"
    echo "═══════════════════════════════════════════════════"

    for cmd in "${commands[@]}"; do
        local result
        result=$(validate_voice_command "$cmd")
        case "$result" in
            VALID:*)
                ((valid_count++))
                echo "  [OK] '$cmd' -> ${result#VALID:}";;
            SUGGEST:*)
                ((suggest_count++))
                echo "  [??] '$cmd' -> did you mean '${result#SUGGEST:}'?";;
            *)
                ((invalid_count++))
                echo "  [XX] '$cmd' -> UNKNOWN/INVALID";;
        esac
    done

    echo "───────────────────────────────────────────────────"
    echo "  Valid: $valid_count | Suggested: $suggest_count | Invalid: $invalid_count"
    echo "═══════════════════════════════════════════════════"

    [[ $invalid_count -eq 0 && $suggest_count -eq 0 ]]
}

# ─── INTERACTIVE MODE ───────────────────────────────────────────────────────
voice_command_check() {
    local input="$1"
    local result
    result=$(validate_voice_command "$input")

    case "$result" in
        EMPTY)
            echo "[VOICE] Empty command received, skipping..."
            return 1;;
        VALID:*)
            echo "[VOICE] Valid command: ${result#VALID:}"
            return 0;;
        SUGGEST:*)
            echo "[VOICE] Unrecognized: '$input'"
            echo "[VOICE] Did you mean: ${result#SUGGEST:}?"
            echo "[VOICE] Re-run with the suggested command or re-phrase."
            return 2;;
        *)
            echo "[VOICE] INVALID COMMAND: '$input'"
            echo "[VOICE] This command was not recognized."
            echo "[VOICE] Please check the command and try again."
            return 1;;
    esac
}

export -f validate_voice_command
export -f validate_command_list
export -f voice_command_check
export -f levenshtein
