#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# FREENEMO — Nemotron 3 Ultra Unified Orchestration Launcher (CONCATENATED)
# Auto-generated by concat.sh — DO NOT EDIT DIRECTLY
# Edit modules in freenemo_modules/ then re-run concat.sh
# ════════════════════════════════════════════════════════════════════════════

set -euo pipefail

# ═══ MODULE: 00_core_config.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 00: Core Configuration, Colors, Logging, Environment Variables
# ════════════════════════════════════════════════════════════════════════════

# ─── GLOBAL CONFIG ──────────────────────────────────────────────────────────
export FREENEMO_VERSION="1.0.0"
export FREENEMO_START_TIME=$(date -u +%s)
export FREENEMO_TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)
export FREENEMO_SESSION_ID="${KILO_SESSION_ID:-$(basename "$(pwd)" | sed 's/^agent_//')}"
export FREENEMO_AGENT_ID="${KILO_AGENT_ID:-${FREENEMO_SESSION_ID}}"

# Repo & Git
export REPO_URL="${KILO_REPO_URL:-https://github.com/PrimeCarrPod/SEED.git}"
export REPO_ROOT="${KILO_REPO_ROOT:-}"
export BRANCH_NAME="session/agent_${FREENEMO_SESSION_ID}_${FREENEMO_TIMESTAMP}"

# Nemotron 3 Ultra API
export NEMOTRON_API_ENDPOINT="${NVIDIA_API_URL:-https://openrouter.ai/api/v1/chat/completions}"
export NEMOTRON_API_KEY="${NVIDIA_API_KEY:-${OPENROUTER_API_KEY:-}}"
export NEMOTRON_MODEL="${NVIDIA_MODEL_NAME:-nvidia/nemotron-3-ultra-550b-a55b:free}"

# Nemotron Payload Defaults (optimized for 55B active / 1M context)
export NEMOTRON_THINKING_MODE="${NEMOTRON_THINKING_MODE:-true}"
export NEMOTRON_REASONING_EFFORT="${NEMOTRON_REASONING_EFFORT:-medium}"
export NEMOTRON_THINKING_BUDGET="${NEMOTRON_THINKING_BUDGET:-1024}"
export NEMOTRON_MAX_TOKENS="${NEMOTRON_MAX_TOKENS:-4096}"
export NEMOTRON_FORCE_NON_EMPTY="${NEMOTRON_FORCE_NON_EMPTY:-true}"
export NEMOTRON_RESPONSE_FORMAT='{"type": "json_object"}'

# Heartbeat & Earthbeat
export HEARTBEAT_INTERVAL="${HEARTBEAT_INTERVAL:-3}"
export HEARTBEAT_CHARS="${HEARTBEAT_CHARS:-♥♦♣♠}"
export EARTHBEAT_MODE="${EARTHBEAT_MODE:-chamber}"
export EARTHBEAT_COUNT="${EARTHBEAT_COUNT:-4}"

# SDK Forge
export ANDROID_HOME="${ANDROID_HOME:-$(pwd)/.sdk/android-sdk}"
export BUILD_TOOLS_VERSION="${BUILD_TOOLS_VERSION:-33.0.1}"
export COMPILE_SDK="${COMPILE_SDK:-33}"

# Logging Structure: CSMLogs/Sessions/Session'Date-Time'/
export CSM_LOGS_ROOT="${CSM_LOGS_ROOT:-CSMLogs}"
export SESSION_LOG_DIR="${CSM_LOGS_ROOT}/Sessions/Session${FREENEMO_TIMESTAMP}"
export HEARTBEAT_LOG_DIR="${SESSION_LOG_DIR}/heartbeats"
export GIT_STATS_LOG_DIR="${SESSION_LOG_DIR}/gitstats"
export ERROR_LOG_DIR="${SESSION_LOG_DIR}/errors"
export PERF_LOG_DIR="${SESSION_LOG_DIR}/performance"

mkdir -p "${SESSION_LOG_DIR}" "${HEARTBEAT_LOG_DIR}" "${GIT_STATS_LOG_DIR}" "${ERROR_LOG_DIR}" "${PERF_LOG_DIR}"

# ─── COLORS ──────────────────────────────────────────────────────────────────
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[1;33m'
export BLUE='\033[0;34m'
export MAGENTA='\033[0;35m'
export CYAN='\033[0;36m'
export BOLD='\033[1m'
export DIM='\033[2m'
export NC='\033[0m'

# ─── LOGGING FUNCTIONS ───────────────────────────────────────────────────────
freenemo_log()    { echo -e "${CYAN}[FREENEMO]${NC} $*" | tee -a "${SESSION_LOG_DIR}/freenemo.log"; }
freenemo_success() { echo -e "${GREEN}[✓]${NC} $*" | tee -a "${SESSION_LOG_DIR}/freenemo.log"; }
freenemo_warn()   { echo -e "${YELLOW}[!]${NC} $*" | tee -a "${SESSION_LOG_DIR}/freenemo.log"; }
freenemo_error()  { echo -e "${RED}[✗]${NC} $*" | tee -a "${SESSION_LOG_DIR}/freenemo.log"; }
freenemo_banner() { echo -e "\n${MAGENTA}${BOLD}$*${NC}\n" | tee -a "${SESSION_LOG_DIR}/freenemo.log"; }

# ─── RETRY UTILITY (exponential backoff) ────────────────────────────────────
freenemo_retry() {
    local max_attempts=$1 delay=$2; shift 2
    local attempt=1
    while true; do
        if "$@"; then return 0; fi
        if [[ $attempt -ge $max_attempts ]]; then
            freenemo_error "Command failed after $max_attempts attempts: $*"
            return 1
        fi
        freenemo_warn "Attempt $attempt/$max_attempts failed. Retrying in ${delay}s..."
        sleep "$delay"
        delay=$((delay * 2))
        attempt=$((attempt + 1))
    done
}

# ─── GIT UTILITIES ──────────────────────────────────────────────────────────
freenemo_git_discover_repo() {
    if [[ -n "$REPO_ROOT" && -d "$REPO_ROOT/.git" ]]; then return 0; fi
    if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        REPO_ROOT=$(git rev-parse --show-toplevel)
        return 0
    fi
    local dir="$(pwd)"
    while [[ "$dir" != "/" ]]; do
        if [[ -d "$dir/.git" ]]; then REPO_ROOT="$dir"; return 0; fi
        dir="$(dirname "$dir")"
    done
    return 1
}

freenemo_git_ensure_origin() {
    cd "$REPO_ROOT"
    if ! git remote get-url origin >/dev/null 2>&1; then
        git remote add origin "$REPO_URL"
    fi
}
# ═══ MODULE: 01a_nemotron_payload_core.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 01A: Nemotron 3 Ultra API Payload — Core Build Functions
# Dual-stream SSE, reasoning budgets, MTP optimization
# ════════════════════════════════════════════════════════════════════════════

# ─── BUILD OPTIMIZED PAYLOAD ────────────────────────────────────────────────
# Uses: enable_thinking, reasoning_effort, thinking_token_budget, force_nonempty_content
# Optimized for Nemotron 3 Ultra: 55B active, 1M context, MTP 5-token draft
nemotron_build_payload() {
    local prompt="$1"
    local thinking="${2:-${NEMOTRON_THINKING_MODE}}"
    local effort="${3:-${NEMOTRON_REASONING_EFFORT}}"
    local budget="${4:-${NEMOTRON_THINKING_BUDGET}}"
    local max_tokens="${5:-${NEMOTRON_MAX_TOKENS}}"
    local force_nonempty="${6:-${NEMOTRON_FORCE_NON_EMPTY}}"
    local response_format="${7:-${NEMOTRON_RESPONSE_FORMAT}}"
    local stream="${8:-true}"

    jq -n \
        --arg model "${NEMOTRON_MODEL}" \
        --arg prompt "${prompt}" \
        --argjson max_tokens "${max_tokens}" \
        --argjson thinking "${thinking}" \
        --arg effort "${effort}" \
        --argjson budget "${budget}" \
        --argjson force_nonempty "${force_nonempty}" \
        --argjson stream "${stream}" \
        --argjson response_format "${response_format}" \
    '{
        model: $model,
        messages: [
            {
                role: "system",
                content: "You are an expert autonomous Linux infrastructure engineer. Emit precise, optimized, syntactically valid bash shell commands without conversational prose. Use Reasoning Sandwich: PLAN → ACTION → VERIFICATION."
            },
            {
                role: "user",
                content: $prompt
            }
        ],
        stream: $stream,
        max_tokens: $max_tokens,
        response_format: $response_format,
        extra_body: {
            chat_template_kwargs: {
                enable_thinking: $thinking,
                reasoning_effort: $effort,
                force_nonempty_content: $force_nonempty
            },
            thinking_token_budget: $budget
        }
    }'
}

# ─── DUAL-STREAM SSE READER ─────────────────────────────────────────────────
# Parses reasoning_content (dimmed) and content (bold) in real-time
nemotron_stream_reader() {
    local payload="$1"
    local timeout="${2:-300}"

    curl -N -s -X POST "${NEMOTRON_API_ENDPOINT}" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${NEMOTRON_API_KEY}" \
        -H "HTTP-Referer: https://kilo.ai" \
        -H "X-Title: FreeNemo-Orchestrator" \
        --connect-timeout 5 \
        --keepalive-time 60 \
        --max-time "${timeout}" \
        -d "${payload}" | while IFS= read -r line; do
            clean_line="${line#data: }"
            [[ -z "${clean_line}" ]] && continue
            [[ "${clean_line}" == "[DONE]" ]] && break

            # reasoning_content → dimmed gray (ANSI 2;37m)
            reasoning=$(echo "${clean_line}" | jq -r '.choices[0].delta.reasoning_content // .choices[0].delta.reasoning // empty' 2>/dev/null || true)
            if [[ -n "${reasoning}" ]]; then
                printf "\e[2;37m%s\e[0m" "${reasoning}"
            fi

            # content → bold green (ANSI 1;32m)
            content=$(echo "${clean_line}" | jq -r '.choices[0].delta.content // empty' 2>/dev/null || true)
            if [[ -n "${content}" ]]; then
                printf "\e[1;32m%s\e[0m" "${content}"
            fi
        done
    printf "\n"
}
# ═══ MODULE: 01b_nemotron_payload_advanced.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 01B: Nemotron 3 Ultra API Payload — Advanced Functions
# Headless mode, quick commands, reasoning sandwich prompt builder
# ════════════════════════════════════════════════════════════════════════════

# ─── HEADLESS NON-STREAM (for patching/diagnostics) ─────────────────────────
nemotron_headless() {
    local prompt="$1"
    local max_tokens="${2:-8192}"
    local budget="${3:-2048}"

    local payload=$(nemotron_build_payload "${prompt}" true "medium" "${budget}" "${max_tokens}" true '{"type": "json_object"}' false)

    local response
    response=$(curl -s -X POST "${NEMOTRON_API_ENDPOINT}" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${NEMOTRON_API_KEY}" \
        -H "HTTP-Referer: https://kilo.ai" \
        --connect-timeout 5 \
        --max-time 180 \
        -d "${payload}")

    echo "${response}" | jq -r '.choices[0].message.content // empty'
}

# ─── QUICK COMMAND (bypass thinking for trivial tasks) ──────────────────────
nemotron_quick() {
    local prompt="$1"
    local payload=$(nemotron_build_payload "${prompt}" false "low" 256 1024 true '{}' true)
    nemotron_stream_reader "${payload}" 60
}

# ─── REASONING SANDWICH PROMPT BUILDER ──────────────────────────────────────
# Enforces: PLAN → ACTION → VERIFICATION structure
nemotron_sandwich_prompt() {
    local target_file="$1"
    local error_log="$2"
    local context="${3:-}"

    cat <<EOF
Perform autonomous diagnosis and remediation using Reasoning Sandwich Pattern:
1. PLAN: Isolate root cause from error log trace.
2. ACTION: Emit clean POSIX unified diff (diff -u) to patch target file.
3. VERIFICATION: Detail explicit assertion checks to validate the patch.

[TARGET_FILE: ${target_file}]
\`\`\`
$(cat "${target_file}")
\`\`\`

[ERROR_LOGS]
\`\`\`
$(tail -n 250 "${error_log}")
\`\`\`

${context}
EOF
}
# ═══ MODULE: 02_transport_hardening.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 02: Transport Layer Hardening — TCP/BBR, SSH Multiplexing, cURL Timeouts
# Optimized for trans-oceanic links (Costa Rica → US East Coast: 45-65ms RTT)
# ════════════════════════════════════════════════════════════════════════════

# ─── KERNEL TCP TUNING (requires root) ──────────────────────────────────────
# Expands buffers to 16MB for BDP over ARCOS-1/MAYA-1 submarine cables
# Enables BBR congestion control for bandwidth-modeling over loss-based
transport_tune_kernel() {
    if [[ $EUID -ne 0 ]]; then
        freenemo_warn "Kernel tuning requires root. Skipping (run with sudo for full optimization)."
        return 0
    fi

    freenemo_log "Applying TCP/IP kernel optimizations for LLM streaming..."

    sysctl -w net.ipv4.tcp_rmem="4096 87380 16777216" >/dev/null
    sysctl -w net.ipv4.tcp_wmem="4096 65536 16777216" >/dev/null
    sysctl -w net.ipv4.tcp_congestion_control="bbr" >/dev/null
    sysctl -w net.ipv4.tcp_timestamps=1 >/dev/null

    # Persist across reboots
    cat > /etc/sysctl.d/99-freenemo-llm.conf <<'EOF'
# FreeNemo LLM Streaming Optimizations
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_timestamps = 1
EOF

    freenemo_success "Kernel TCP tuning applied (BBR + 16MB buffers)"
}

# ─── SSH MULTIPLEXING CONFIG ────────────────────────────────────────────────
# Eliminates 200-300ms handshake overhead per command over 65ms links
transport_setup_ssh_multiplexing() {
    local ssh_config="${HOME}/.ssh/config"
    mkdir -p "${HOME}/.ssh/sockets"

    if ! grep -q "ControlMaster auto" "${ssh_config}" 2>/dev/null; then
        cat >> "${ssh_config}" <<'EOF'

# FreeNemo SSH Multiplexing for LLM API Tunnels
Host *
    ControlMaster auto
    ControlPath ~/.ssh/sockets/%r@%h-%p
    ControlPersist 10m
    Ciphers aes128-ctr
    Compression yes
    ServerAliveInterval 30
    ServerAliveCountMax 3
EOF
        freenemo_success "SSH multiplexing configured (~/.ssh/config)"
    else
        freenemo_log "SSH multiplexing already configured"
    fi
}

# ─── CURL TRANSPORT DEFAULTS ────────────────────────────────────────────────
# Layered timeout strategy: fast failover + keepalive + wall-clock bound
export FREENEMO_CURL_OPTS=(
    "--connect-timeout" "5"       # Fail fast if handshake stalls
    "--keepalive-time" "60"       # TCP probes during long reasoning
    "--max-time" "300"            # 5-min absolute wall-clock limit
    "-H" "HTTP-Referer: https://kilo.ai"
    "-H" "X-Title: FreeNemo-Orchestrator"
)

# ─── RESILIENT CURL WRAPPER ─────────────────────────────────────────────────
# Adds retry logic with exponential backoff for transient failures
freenemo_curl() {
    local max_retries=3
    local retry_delay=2
    local attempt=1

    while true; do
        if curl "${FREENEMO_CURL_OPTS[@]}" "$@"; then
            return 0
        fi
        local exit_code=$?
        if [[ $attempt -ge $max_retries ]]; then
            freenemo_error "curl failed after $max_retries attempts (exit: $exit_code)"
            return $exit_code
        fi
        freenemo_warn "curl attempt $attempt/$max_retries failed. Retrying in ${retry_delay}s..."
        sleep "$retry_delay"
        retry_delay=$((retry_delay * 2))
        attempt=$((attempt + 1))
    done
}

# ─── NETWORK HEALTH CHECK ───────────────────────────────────────────────────
transport_check_connectivity() {
    local endpoint="${1:-${NEMOTRON_API_ENDPOINT}}"
    freenemo_log "Checking connectivity to ${endpoint}..."

    if freenemo_curl -s -o /dev/null -w "%{http_code}" --max-time 10 "${endpoint}" | grep -q "^2"; then
        freenemo_success "Endpoint reachable"
        return 0
    else
        freenemo_error "Endpoint unreachable"
        return 1
    fi
}
# ═══ MODULE: 03a_github_handler_core.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 03A: GitHub Handler — Core Config, Difficulty Assessment, Logging
# 3-13 strategies based on file size, auto-split/join, merge queue, success tracking
# ════════════════════════════════════════════════════════════════════════════

# ─── CONFIG ──────────────────────────────────────────────────────────────────
GH_LOG_DIR="${REPO_ROOT}/.github_handler"
GH_DIFFICULTY_LOG="${GH_LOG_DIR}/difficulty_log.json"
GH_METHODS_LOG="${GH_LOG_DIR}/methods_log.json"
GH_MERGE_QUEUE="${GH_LOG_DIR}/merge_queue.json"
GH_SPLIT_DIR="${GH_LOG_DIR}/splits"

EASY_THRESHOLD=100
MEDIUM_THRESHOLD=500
HARD_THRESHOLD=2000
EXTREME_THRESHOLD=5000

EASY_STRATS=3
MEDIUM_STRATS=6
HARD_STRATS=9
EXTREME_STRATS=13

# ─── INIT ────────────────────────────────────────────────────────────────────
gh_init() {
    mkdir -p "${GH_LOG_DIR}" "${GH_SPLIT_DIR}"
    [[ -f "${GH_DIFFICULTY_LOG}" ]] || echo '{"files":{}}' > "${GH_DIFFICULTY_LOG}"
    [[ -f "${GH_METHODS_LOG}" ]] || echo '{"methods":[]}' > "${GH_METHODS_LOG}"
    [[ -f "${GH_MERGE_QUEUE}" ]] || echo '{"queue":[]}' > "${GH_MERGE_QUEUE}"
}

# ─── DIFFICULTY ASSESSMENT ──────────────────────────────────────────────────
gh_assess_difficulty() {
    local file="$1" lines=0
    [[ -f "$file" ]] && lines=$(wc -l < "$file")
    if (( lines <= EASY_THRESHOLD )); then echo "easy"
    elif (( lines <= MEDIUM_THRESHOLD )); then echo "medium"
    elif (( lines <= HARD_THRESHOLD )); then echo "hard"
    else echo "extreme"; fi
}

gh_strategy_count() {
    case "$1" in
        easy) echo $EASY_STRATS ;;
        medium) echo $MEDIUM_STRATS ;;
        hard) echo $HARD_STRATS ;;
        *) echo $EXTREME_STRATS ;;
    esac
}

# ─── LOGGING ─────────────────────────────────────────────────────────────────
gh_log_difficulty() {
    local file="$1" diff="$2" lines="$3" strats="$4"
    local entry=$(jq -n --arg f "$file" --arg d "$diff" --arg l "$lines" --arg s "$strats" --arg t "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
        '{file: $f, difficulty: $d, lines: ($l|tonumber), strategies: ($s|tonumber), timestamp: $t}')
    jq --argjson e "$entry" --arg f "$file" '.files[$f] = $e' "${GH_DIFFICULTY_LOG}" > "${GH_DIFFICULTY_LOG}.tmp" && mv "${GH_DIFFICULTY_LOG}.tmp" "${GH_DIFFICULTY_LOG}"
}

gh_log_method() {
    local file="$1" method="$2" success="$3" diff="$4"
    local entry=$(jq -n --arg f "$file" --arg m "$method" --arg s "$success" --arg d "$diff" --arg t "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
        '{file: $f, method: $m, success: ($s=="true"), difficulty: $d, timestamp: $t}')
    jq --argjson e "$entry" '.methods += [$e]' "${GH_METHODS_LOG}" > "${GH_METHODS_LOG}.tmp" && mv "${GH_METHODS_LOG}.tmp" "${GH_METHODS_LOG}"
}

# ─── SPLIT/JOIN ──────────────────────────────────────────────────────────────
gh_split_file() {
    local file="$1" max_lines="${2:-500}"
    local base=$(basename "$file" .md)
    local prefix="${GH_SPLIT_DIR}/${base}_part"
    mkdir -p "${GH_SPLIT_DIR}"
    split -l "$max_lines" -d --additional-suffix=.md "$file" "$prefix"
    local parts=($(ls "${prefix}"* 2>/dev/null | sort))
    jq -n --arg o "$file" --argjson p "$(printf '%s\n' "${parts[@]}" | jq -R . | jq -s .)" '{original:$o,parts:$p,created:now|todateiso8601}' > "${GH_SPLIT_DIR}/${base}_manifest.json"
    printf '%s\n' "${parts[@]}"
}

gh_join_files() {
    local manifest="$1" output="$2"
    local parts=$(jq -r '.parts[]' "$manifest")
    cat $parts > "$output"
}
# ═══ MODULE: 03b_github_handler_strategies.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 03B: GitHub Handler — Strategies (1-13) & Main Save Function
# Multi-strategy save with auto-split for large files, merge queue processor
# ════════════════════════════════════════════════════════════════════════════

# ─── STRATEGIES (1-13) ──────────────────────────────────────────────────────
gh_strat_1_direct() { local f="$1" m="$2" b="$3"; cd "$REPO_ROOT"; git add "$f"; git commit -m "$m"; git -c http.sslVerify=false push origin "$b"; }
gh_strat_2_staged() { local f="$1" m="$2" b="$3"; cd "$REPO_ROOT"; git add -A; git commit -m "$m"; git -c http.sslVerify=false push origin "$b"; }
gh_strat_3_force()  { local f="$1" m="$2" b="$3"; cd "$REPO_ROOT"; git add "$f"; git commit -m "$m"; git -c http.sslVerify=false push --force-with-lease origin "$b"; }
gh_strat_4_pr()     { local f="$1" m="$2" b="$3"; local br="auto-save-$(date +%s)-$(basename "$f"|tr '.' '-')"; cd "$REPO_ROOT"; git checkout -b "$br" "$b"; git add "$f"; git commit -m "$m"; git -c http.sslVerify=false push origin "$br"; command -v gh >/dev/null && gh pr create --base "$b" --head "$br" --title "Auto-save: $f" --body "$m"; git checkout "$b"; }
gh_strat_5_rebase() { local f="$1" m="$2" b="$3"; cd "$REPO_ROOT"; git -c http.sslVerify=false fetch origin "$b"; git rebase "origin/$b" || { git rebase --abort; return 1; }; git add "$f"; git commit -m "$m"; git -c http.sslVerify=false push origin "$b"; }
gh_strat_6_ours()   { local f="$1" m="$2" b="$3"; cd "$REPO_ROOT"; git -c http.sslVerify=false fetch origin "$b"; git merge -s ours "origin/$b" -m "$m"; git add "$f"; git commit --amend --no-edit; git -c http.sslVerify=false push origin "$b"; }
gh_strat_7_cherry() { local f="$1" m="$2" b="$3"; cd "$REPO_ROOT"; local tb="temp-cherry-$(date +%s)"; git checkout -b "$tb"; git add "$f"; git commit -m "$m"; local h=$(git rev-parse HEAD); git checkout "$b"; git cherry-pick "$h" || { git cherry-pick --abort; return 1; }; git -c http.sslVerify=false push origin "$b"; git branch -D "$tb"; }
gh_strat_8_subtree(){ local f="$1" m="$2" b="$3"; local td=$(mktemp -d); cd "$REPO_ROOT"; git clone --branch "$b" --single-branch "$REPO_ROOT" "$td/repo"; cp "$f" "$td/repo/"; cd "$td/repo"; git add "$(basename "$f")"; git commit -m "$m"; git -c http.sslVerify=false push origin "$b"; rm -rf "$td"; }
gh_strat_9_worktree(){ local f="$1" m="$2" b="$3"; cd "$REPO_ROOT"; local wt="${REPO_ROOT}/.git/worktrees/gh-$(date +%s)"; git worktree add "$wt" "$b"; cp "$f" "$wt/"; cd "$wt"; git add "$(basename "$f")"; git commit -m "$m"; git -c http.sslVerify=false push origin "$b"; cd "$REPO_ROOT"; git worktree remove "$wt"; }
gh_strat_10_patch() { local f="$1" m="$2" b="$3"; cd "$REPO_ROOT"; local pf="${GH_LOG_DIR}/$(basename "$f").patch"; git diff HEAD -- "$f" > "$pf"; git apply "$pf"; git add "$f"; git commit -m "$m"; git push origin "$b"; }
gh_strat_11_api()   { [[ -z "${GITHUB_TOKEN:-}" ]] && return 1; return 1; }  # Placeholder
gh_strat_12_lfs()   { command -v git-lfs >/dev/null || return 1; cd "$REPO_ROOT"; git lfs track "$(basename "$1")"; git add "$1" .gitattributes; git commit -m "$2"; git push origin "$3"; }
gh_strat_13_manual(){ local f="$1" m="$2" b="$3"; local e=$(jq -n --arg f "$f" --arg m "$m" --arg b "$b" --arg t "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "{file:\$f,message:\$m,branch:\$b,timestamp:\$t,status:\"pending\"}"); jq --argjson e "$e" ".queue+=[\$e]" "${GH_MERGE_QUEUE}" > "${GH_MERGE_QUEUE}.tmp" && mv "${GH_MERGE_QUEUE}.tmp" "${GH_MERGE_QUEUE}"; return 0; }

# ─── MAIN SAVE FUNCTION ──────────────────────────────────────────────────────
gh_save_file() {
    local file="$1" msg="${2:-Auto-save: $file}" branch="${3:-$(cd "$REPO_ROOT" && git branch --show-current)}"
    [[ ! -f "$file" ]] && { freenemo_error "File not found: $file"; return 1; }
    file=$(realpath "$file")

    gh_init
    local lines=$(wc -l < "$file")
    local diff=$(gh_assess_difficulty "$file")
    local count=$(gh_strategy_count "$diff")

    freenemo_log "Saving $file ($lines lines, $diff, $count strategies)"
    gh_log_difficulty "$file" "$diff" "$lines" "$count"

    if (( lines > HARD_THRESHOLD )); then
        freenemo_warn "Large file ($lines lines), splitting..."
        local parts=($(gh_split_file "$file" 500))
        local all_ok=true
        for p in "${parts[@]}"; do gh_save_file "$p" "Part: $msg" "$branch" || all_ok=false; done
        $all_ok && return 0 || return 1
    fi

    local strategies=(gh_strat_1_direct gh_strat_2_staged gh_strat_3_force gh_strat_4_pr gh_strat_5_rebase gh_strat_6_ours gh_strat_7_cherry gh_strat_8_subtree gh_strat_9_worktree gh_strat_10_patch gh_strat_11_api gh_strat_12_lfs gh_strat_13_manual)
    for ((i=0; i<count; i++)); do
        local strat="${strategies[$i]}"
        freenemo_log "Strategy $((i+1))/$count: $strat"
        if $strat "$file" "$msg" "$branch"; then
            freenemo_success "$strat succeeded"
            gh_log_method "$file" "$strat" "true" "$diff"
            local entry=$(jq -n --arg f "$file" --arg d "$diff" --arg l "$lines" --arg s "$count" --arg t "$(date -u +%Y-%m-%dT%H:%M:%SZ)" --arg m "$strat" "{file:\$f,difficulty:\$d,lines:(\$l|tonumber),strategies:(\$s|tonumber),timestamp:\$t,success_method:\$m}")
            jq --argjson e "$entry" ".files[\$f]=\$e" "${GH_DIFFICULTY_LOG}" > "${GH_DIFFICULTY_LOG}.tmp" && mv "${GH_DIFFICULTY_LOG}.tmp" "${GH_DIFFICULTY_LOG}"
            return 0
        else
            freenemo_warn "$strat failed"
            gh_log_method "$file" "$strat" "false" "$diff"
        fi
    done
    freenemo_error "All $count strategies failed"
    return 1
}

# ─── MERGE QUEUE ─────────────────────────────────────────────────────────────
gh_process_queue() {
    freenemo_log "Processing merge queue..."
    local len=$(jq ".queue|length" "${GH_MERGE_QUEUE}")
    (( len == 0 )) && { freenemo_log "Queue empty"; return 0; }
    for ((i=0; i<len; i++)); do
        local e=$(jq ".queue[$i]" "${GH_MERGE_QUEUE}")
        local f=$(echo "$e" | jq -r ".file")
        local m=$(echo "$e" | jq -r ".message")
        local b=$(echo "$e" | jq -r ".branch")
        local s=$(echo "$e" | jq -r ".status")
        [[ "$s" == "pending" ]] || continue
        freenemo_log "Processing: $f"
        if gh_save_file "$f" "$m" "$b"; then
            jq --argjson i "$i" ".queue[\$i].status=\"completed\"|\.queue[\$i].completed=now|todateiso8601" "${GH_MERGE_QUEUE}" > "${GH_MERGE_QUEUE}.tmp" && mv "${GH_MERGE_QUEUE}.tmp" "${GH_MERGE_QUEUE}"
            freenemo_success "Queue item done: $f"
        else
            jq --argjson i "$i" ".queue[\$i].status=\"failed\"|\.queue[\$i].attempts+=1" "${GH_MERGE_QUEUE}" > "${GH_MERGE_QUEUE}.tmp" && mv "${GH_MERGE_QUEUE}.tmp" "${GH_MERGE_QUEUE}"
            freenemo_error "Queue item failed: $f"
        fi
    done
}
# ═══ MODULE: 04a_earthbeat_chambers_core.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 04A: Earthbeat v3 — Core Generators & Chamber Runners
# Chamber 1: Schumann (3s) | Chamber 2: Geomag (5s) | Chamber 3: Solar (7s) | Chamber 4: Integration (10s)
# ════════════════════════════════════════════════════════════════════════════

# ─── CONFIG ──────────────────────────────────────────────────────────────────
EB_DATA_DIR="${REPO_ROOT}/CSMScripts/earthbeatv3-data"
EB_SCHUMANN_LOG="${EB_DATA_DIR}/schumann.log"
EB_GEOMAG_LOG="${EB_DATA_DIR}/geomag.log"
EB_SOLAR_LOG="${EB_DATA_DIR}/solar.log"
EB_VITALS_LOG="${EB_DATA_DIR}/vitals.log"
EB_CHAMBER_LOG="${EB_DATA_DIR}/chambers.log"
EB_TOKEN_DIR="${REPO_ROOT}/CSMScripts/.tokenringv3"

declare -A CHAMBER_FOCUS=( [1]="SCHUMANN" [2]="GEOMAG" [3]="SOLAR" [4]="INTEGRATION" )
declare -A CHAMBER_INTERVAL=( [1]=3 [2]=5 [3]=7 [4]=10 )
declare -A CHAMBER_CHARS=( [1]="♥" [2]="♦" [3]="♣" [4]="♠" )
declare -A CHAMBER_PIDS=()

mkdir -p "${EB_DATA_DIR}" "${EB_TOKEN_DIR}"

# ─── VITAL SIGN GENERATORS ──────────────────────────────────────────────────
eb_gen_schumann() {
    local base=7.83 var=$(awk -v s="$RANDOM" 'BEGIN{srand(s);print (rand()-0.5)*0.3}')
    local freq=$(awk "BEGIN{print $base+$var}")
    local amp=$(awk -v s="$RANDOM" 'BEGIN{srand(s);print 0.5+rand()*2.0}')
    local q=$(awk -v s="$RANDOM" 'BEGIN{srand(s);print 3+rand()*4}')
    echo "$freq,$amp,$q"
}

eb_gen_geomag() {
    local x=$(awk -v s="$RANDOM" 'BEGIN{srand(s);print 20000+(rand()-0.5)*500}')
    local y=$(awk -v s="$RANDOM" 'BEGIN{srand(s);print -5000+(rand()-0.5)*200}')
    local z=$(awk -v s="$RANDOM" 'BEGIN{srand(s);print 45000+(rand()-0.5)*300}')
    local f=$(awk "BEGIN{print sqrt($x^2+$y^2+$z^2)}")
    local d=$(awk "BEGIN{print atan2($y,$x)*180/3.14159}")
    local i=$(awk "BEGIN{print atan2($z,sqrt($x^2+$y^2))*180/3.14159}")
    echo "$x,$y,$z,$f,$d,$i"
}

eb_gen_solar() {
    local sp=$(awk -v s="$RANDOM" 'BEGIN{srand(s);print 300+rand()*500}')
    local de=$(awk -v s="$RANDOM" 'BEGIN{srand(s);print 1+rand()*20}')
    local bz=$(awk -v s="$RANDOM" 'BEGIN{srand(s);print (rand()-0.5)*20}')
    local bt=$(awk -v s="$RANDOM" 'BEGIN{srand(s);print 1+rand()*15}')
    local te=$(awk -v s="$RANDOM" 'BEGIN{srand(s);print 50000+rand()*200000}')
    echo "$sp,$de,$bz,$bt,$te"
}

eb_calc_kp() { local s="$1"; local bz=$(echo "$s"|cut -d, -f3); local sp=$(echo "$s"|cut -d, -f1); local bt=$(echo "$s"|cut -d, -f4); local vb=$(awk "BEGIN{print $sp*$bt}"); local kp=$(awk "BEGIN{print int(0.5+0.001*$vb+0.1*sqrt($bt))}"); ((kp>9))&&kp=9; ((kp<0))&&kp=0; echo "$kp"; }
eb_calc_gic()  { local g="$1" s="$2"; local db=$(awk -v s="$RANDOM" 'BEGIN{srand(s);print rand()*5000}'); local ef=$(awk "BEGIN{print $db*1000/(2*3.14159*6371000)*0.01}"); local r="LOW"; (( $(awk "BEGIN{print($ef>1)}") ))&&r="MODERATE"; (( $(awk "BEGIN{print($ef>5)}") ))&&r="HIGH"; (( $(awk "BEGIN{print($ef>20)}") ))&&r="EXTREME"; echo "$ef,$r"; }
eb_calc_coupling() { local s="$1"; local f=$(echo "$s"|cut -d, -f1); local a=$(echo "$s"|cut -d, -f2); local al=$(awk "BEGIN{print exp(-(($f-7.83)^2)/0.5)*$a/2.0}"); local be=$(awk "BEGIN{print (exp(-(($f-14.3)^2)/1.0)+exp(-(($f-20.8)^2)/1.0))*$a/3.0}"); local ca=$(awk "BEGIN{print exp(-(($f/4-1.5)^2)/0.25)*$a/5.0}"); echo "$al,$be,$ca"; }

# ─── CHAMBER RUNNERS ────────────────────────────────────────────────────────
eb_run_chamber() {
    local id=$1 interval=${CHAMBER_INTERVAL[$id]} char=${CHAMBER_CHARS[$id]} focus=${CHAMBER_FOCUS[$id]}
    local log="${EB_DATA_DIR}/chamber-${id}.log" pidf="${REPO_ROOT}/CSMScripts/earthbeatv3-chamber-${id}.pid"
    echo $$ > "$pidf"
    echo "[CHAMBER-$id] Started $(date -u) | $focus | ${interval}s" >> "$log"
    trap "echo '[CHAMBER-$id] Stopping $(date -u)'>>$log; rm -f $pidf; exit 0" SIGTERM SIGINT EXIT

    local cycle=0
    while true; do
        cycle=$((cycle+1))
        local sch=$(eb_gen_schumann) geo=$(eb_gen_geomag) sol=$(eb_gen_solar)
        local ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        local freq=$(echo "$sch"|cut -d, -f1) amp=$(echo "$sch"|cut -d, -f2) q=$(echo "$sch"|cut -d, -f3)

        case $id in
            1) echo "$ts,$sch" >> "$EB_SCHUMANN_LOG"; echo "$ts,chamber=$id,focus=$focus,freq=$freq,amp=$amp,q=$q" >> "$EB_CHAMBER_LOG" ;;
            2) echo "$ts,$geo" >> "$EB_GEOMAG_LOG"; local x=$(echo "$geo"|cut -d, -f1) y=$(echo "$geo"|cut -d, -f2) z=$(echo "$geo"|cut -d, -f3) f=$(echo "$geo"|cut -d, -f4); echo "$ts,chamber=$id,focus=$focus,X=$x,Y=$y,Z=$z,F=$f" >> "$EB_CHAMBER_LOG" ;;
            3) echo "$ts,$sol" >> "$EB_SOLAR_LOG"; local sp=$(echo "$sol"|cut -d, -f1) de=$(echo "$sol"|cut -d, -f2) bz=$(echo "$sol"|cut -d, -f3) bt=$(echo "$sol"|cut -d, -f4); echo "$ts,chamber=$id,focus=$focus,speed=$sp,density=$de,bz=$bz,bt=$bt" >> "$EB_CHAMBER_LOG" ;;
            4) local kp=$(eb_calc_kp "$sol") gic=$(eb_calc_gic "$geo" "$sol") coup=$(eb_calc_coupling "$sch"); local ef=$(echo "$gic"|cut -d, -f1) risk=$(echo "$gic"|cut -d, -f2); echo "$ts,sch=$sch,geo=$geo,sol=$sol,kp=$kp,gic=$gic,coup=$coup" >> "$EB_VITALS_LOG"; echo "$ts,chamber=$id,focus=$focus,kp=$kp,ef=$ef,risk=$risk" >> "$EB_CHAMBER_LOG"; [[ "$risk" == "EXTREME" || $kp -ge 7 ]] && echo "CARRINGTON_ALERT:Kp=$kp:Efield=$ef:Risk=$risk:$(date -u +%s)" > "${REPO_ROOT}/CSMScripts/.carrington-alert" ;;
        esac

        printf "%s" "$char" >&2

        if (( id==1 && cycle%20==0 )) || (( id==2 && cycle%12==0 )) || (( id==3 && cycle%8==0 )) || (( id==4 && cycle%6==0 )); then
            case $id in
                1) local coup=$(eb_calc_coupling "$sch"); echo "[CHAMBER-$id] $(date -u) Cycle:$cycle Freq:${freq}Hz Amp:${amp}pT Q:$q Coup:$coup" >> "$log" ;;
                2) echo "[CHAMBER-$id] $(date -u) Cycle:$cycle X:${x}nT Y:${y}nT Z:${z}nT F:${f}nT" >> "$log" ;;
                3) local kp=$(eb_calc_kp "$sol"); echo "[CHAMBER-$id] $(date -u) Cycle:$cycle Speed:${sp}km/s Den:${de}p/cm³ Bz:${bz}nT Bt:${bt}nT Kp:$kp" >> "$log" ;;
                4) echo "[CHAMBER-$id] $(date -u) Cycle:$cycle Kp:$kp E-field:${ef}V/km Risk:$risk Coup:$coup" >> "$log" ;;
            esac
        fi
        sleep "$interval"
    done
}
# ═══ MODULE: 04b_earthbeat_chambers_modes.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 04B: Earthbeat v3 — Token Ring & Parallel/Tokenring Modes
# Token ring support, cross-chamber monitoring, Carrington-class alerts
# ════════════════════════════════════════════════════════════════════════════

# ─── TOKEN RING ──────────────────────────────────────────────────────────────
eb_init_token_ring() { local n=$1; mkdir -p "$EB_TOKEN_DIR"; for i in $(seq 0 $((n-1))); do echo 0 > "$EB_TOKEN_DIR/token_$i"; done; echo 1 > "$EB_TOKEN_DIR/token_0"; freenemo_log "Token ring init: $n nodes"; }
eb_pass_token() { local id=$1 n=$2 tf="$EB_TOKEN_DIR/token_$id" nt="$EB_TOKEN_DIR/token_$(( (id+1)%n ))"; while [[ "$(cat "$tf" 2>/dev/null || echo 0)" != "1" ]]; do sleep 0.1; done; echo 0 > "$tf"; echo 1 > "$nt"; }

# ─── GENERIC INSTANCE (parallel/tokenring modes) ────────────────────────────
eb_run_instance() {
    local id=$1 count=$2 mode=$3 interval=${4:-6}
    local log="${EB_DATA_DIR}/instance-${id}.log" pidf="${REPO_ROOT}/CSMScripts/earthbeatv3-instance-${id}.pid"
    echo $$ > "$pidf"; trap "rm -f $pidf; exit 0" SIGTERM SIGINT EXIT
    local cycle=0 chars="♥♦♣♠"
    while true; do
        cycle=$((cycle+1))
        [[ "$mode" == "tokenring" ]] && eb_pass_token "$id" "$count"
        local sch=$(eb_gen_schumann) geo=$(eb_gen_geomag) sol=$(eb_gen_solar)
        local kp=$(eb_calc_kp "$sol") gic=$(eb_calc_gic "$geo" "$sol") coup=$(eb_calc_coupling "$sch")
        local ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        echo "$ts,$sch,$coup" >> "$EB_SCHUMANN_LOG"
        echo "$ts,$geo,$kp" >> "$EB_GEOMAG_LOG"
        echo "$ts,$sol" >> "$EB_SOLAR_LOG"
        echo "$ts,sch=$sch,geo=$geo,sol=$sol,kp=$kp,gic=$gic,coup=$coup" >> "$EB_VITALS_LOG"
        printf "%s" "${chars:$((cycle%4)):1}" >&2
        local ef=$(echo "$gic"|cut -d, -f1) risk=$(echo "$gic"|cut -d, -f2)
        (( cycle%10==0 )) && echo "[INSTANCE-$id] $(date -u) Cycle:$cycle Kp:$kp Risk:$risk" >> "$log"
        [[ "$risk" == "EXTREME" || $kp -ge 7 ]] && echo "CARRINGTON_ALERT:Kp=$kp:Efield=$ef:Risk=$risk:$(date -u +%s)" > "${REPO_ROOT}/CSMScripts/.carrington-alert"
        sleep "$interval"
    done
}

# ─── CHAMBER MODE (4 specialized) ───────────────────────────────────────────
eb_run_chamber_mode() {
    freenemo_banner "🌍 EARTHBEAT v3 — Chamber Mode (4 specialized)"
    freenemo_log "Chambers: Schumann(3s)♥ Geomag(5s)♦ Solar(7s)♣ Integration(10s)♠"
    eb_run_chamber 1 & CHAMBER_PIDS[1]=$!; freenemo_log "Chamber 1 PID: $!"
    eb_run_chamber 2 & CHAMBER_PIDS[2]=$!; freenemo_log "Chamber 2 PID: $!"
    eb_run_chamber 3 & CHAMBER_PIDS[3]=$!; freenemo_log "Chamber 3 PID: $!"
    eb_run_chamber 4 & CHAMBER_PIDS[4]=$!; freenemo_log "Chamber 4 PID: $!"
    freenemo_log "All 4 chambers running. Heartbeat: ♥=Schumann ♦=Geomag ♣=Solar ♠=Integration"
    wait
}

# ─── PARALLEL/TOKENRING MODES ───────────────────────────────────────────────
eb_run_parallel() {
    local mode=$1 count=$2
    [[ "$mode" == "tokenring" ]] && eb_init_token_ring "$count"
    freenemo_banner "🌍 EARTHBEAT v3 — $mode mode ($count instances)"
    for i in $(seq 0 $((count-1))); do
        eb_run_instance "$i" "$count" "$mode" &
        CHAMBER_PIDS+=($!)
        freenemo_log "Instance $i PID: $!"
        sleep 0.2
    done
    freenemo_log "All $count instances running. Ctrl+C to stop."
    wait
}
# ═══ MODULE: 05a_sdk_forge_core.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 05A: SDK Forge — Core Config, Helpers, Export, Verify
# Java 17, cmdline-tools, platform android-33, build-tools 33.0.1, verified pairs
# ════════════════════════════════════════════════════════════════════════════

# ─── CONFIG ──────────────────────────────────────────────────────────────────
SF_SDK_BASE="${ANDROID_HOME:-$(pwd)/.sdk/android-sdk}"
SF_CMDTOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
SF_PLATFORM_URL="https://dl.google.com/android/repository/platform-33_r02.zip"
SF_BT_URL="https://dl.google.com/android/repository/build-tools_r33.0.1-linux.zip"
SF_BT_FALLBACK="https://dl.google.com/android/repository/build-tools_r34.0.0-linux.zip"
SF_BUILD_TOOLS_VER="33.0.1"
SF_COMPILE_SDK="33"
SF_TIMEOUT=300
SF_QUIET=false
SF_VERIFY_ONLY=false
SF_EXPORT_ENV=false

# ─── HELPERS ─────────────────────────────────────────────────────────────────
sf_msg()  { [[ "$SF_QUIET" != "true" ]] && echo -e "${GREEN}[SDKForge]${NC} $1" || true; }
sf_warn() { [[ "$SF_QUIET" != "true" ]] && echo -e "${YELLOW}[SDKForge]${NC} $1" || true; }
sf_err()  { [[ "$SF_QUIET" != "true" ]] && echo -e "${RED}[SDKForge]${NC} $1" || true; }

sf_banner() {
    [[ "$SF_QUIET" != "true" ]] && {
        echo ""; echo -e "${CYAN}╔═══════════════════════════════════════════════════════════╗${NC}"
        echo -e "${CYAN}║${NC}       ${GREEN}SDKForge — CarrPod Cloud Toolchain${NC}        ${CYAN}║${NC}"
        echo -e "${CYAN}║${NC}  Build Tools: ${YELLOW}${SF_BUILD_TOOLS_VER}${NC} | Platform: ${YELLOW}android-${SF_COMPILE_SDK}${NC}     ${CYAN}║${NC}"
        echo -e "${CYAN}║${NC}  Target: ${CYAN}${SF_SDK_BASE}${NC}                          ${CYAN}║${NC}"
        echo -e "${CYAN}╚═══════════════════════════════════════════════════════════╝${NC}"; echo ""
    } || true
}

# ─── EXPORT ENV ──────────────────────────────────────────────────────────────
sf_export_env() {
    local bt_dir="${SF_SDK_BASE}/build-tools/${SF_BUILD_TOOLS_VER}"
    echo "export ANDROID_HOME=${SF_SDK_BASE}"
    echo "export BUILD_TOOLS_VERSION=${SF_BUILD_TOOLS_VER}"
    echo "export COMPILE_SDK=${SF_COMPILE_SDK}"
    echo "export PATH=\"${bt_dir}:\$PATH\""
}

# ─── VERIFY ONLY ─────────────────────────────────────────────────────────────
sf_verify() {
    sf_msg "Verify-only mode..."
    local bt_dir="${SF_SDK_BASE}/build-tools/${SF_BUILD_TOOLS_VER}"
    local plat_dir="${SF_SDK_BASE}/platforms/android-${SF_COMPILE_SDK}"
    local fail=0
    for t in aapt2 d8 zipalign apksigner; do
        [[ -f "${bt_dir}/${t}" ]] && echo "  ${GREEN}✓${NC} $t" || { echo "  ${RED}✗${NC} $t MISSING"; fail=1; }
    done
    [[ -f "${plat_dir}/android.jar" ]] && echo "  ${GREEN}✓${NC} android.jar" || { echo "  ${RED}✗${NC} android.jar MISSING"; fail=1; }
    java -version >/dev/null 2>&1 && echo "  ${GREEN}✓${NC} java" || { echo "  ${RED}✗${NC} java MISSING"; fail=1; }
    [[ $fail -eq 1 ]] && { sf_err "Tools missing — run without --verify-only"; return 1; }
    sf_msg "All tools present. Toolchain ready."
    return 0
}
# ═══ MODULE: 05b_sdk_forge_install.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 05B: SDK Forge — Main Install & Entry Point
# Android build toolchain bootstrap for CarrPod cloud environments
# ════════════════════════════════════════════════════════════════════════════

# ─── MAIN INSTALL ────────────────────────────────────────────────────────────
sf_install() {
    sf_banner

    # Step 1: System packages
    sf_msg "[1/5] Installing system packages (Java 17, zip, unzip, bc)..."
    apt-get update -qq 2>/dev/null || true
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq openjdk-17-jdk-headless zip unzip bc 2>/dev/null || true
    java -version 2>&1 | head -1
    sf_msg "System packages ready."

    # Step 2: cmdline-tools
    sf_msg "[2/5] Downloading Android cmdline-tools..."
    mkdir -p "${SF_SDK_BASE}/cmdline-tools"
    if [[ ! -f "${SF_SDK_BASE}/cmdline-tools/latest/bin/sdkmanager" ]]; then
        local zip="${SF_SDK_BASE}/../cmdline-tools.zip"
        curl -k -sL "$SF_CMDTOOLS_URL" -o "$zip" 2>&1
        local size=$(stat --printf="%s" "$zip" 2>/dev/null || echo 0)
        (( size < 100000 )) && { sf_err "Download failed (size: $size)"; return 1; }
        sf_msg "  Downloaded: $size bytes"
        rm -rf "${SF_SDK_BASE}/tmp-extract"
        mkdir -p "${SF_SDK_BASE}/tmp-extract"
        unzip -qo "$zip" -d "${SF_SDK_BASE}/tmp-extract"
        rm -rf "${SF_SDK_BASE}/cmdline-tools/latest"
        mv "${SF_SDK_BASE}/tmp-extract/cmdline-tools" "${SF_SDK_BASE}/cmdline-tools/latest"
        rm -rf "${SF_SDK_BASE}/tmp-extract"
        sf_msg "  cmdline-tools installed."
    else
        sf_msg "  cmdline-tools already present."
    fi

    # Step 3: Platform
    sf_msg "[3/5] Downloading platform android-${SF_COMPILE_SDK}..."
    local plat_dir="${SF_SDK_BASE}/platforms/android-${SF_COMPILE_SDK}"
    if [[ ! -f "${plat_dir}/android.jar" ]]; then
        local zip="${SF_SDK_BASE}/../platform-${SF_COMPILE_SDK}.zip"
        curl -k -sL "$SF_PLATFORM_URL" -o "$zip" 2>&1
        local size=$(stat --printf="%s" "$zip" 2>/dev/null || echo 0)
        (( size < 100000 )) && { sf_err "Platform download failed"; return 1; }
        mkdir -p "${SF_SDK_BASE}/platforms"
        unzip -qo "$zip" -d "${SF_SDK_BASE}/platforms"
        [[ -d "${SF_SDK_BASE}/platforms/android-13" ]] && mv "${SF_SDK_BASE}/platforms/android-13" "$plat_dir" 2>/dev/null || true
        sf_msg "  Platform android-${SF_COMPILE_SDK} installed."
    else
        sf_msg "  Platform already present."
    fi

    # Step 4: Build Tools
    sf_msg "[4/5] Downloading build-tools ${SF_BUILD_TOOLS_VER}..."
    local bt_dir="${SF_SDK_BASE}/build-tools/${SF_BUILD_TOOLS_VER}"
    if [[ ! -f "${bt_dir}/aapt2" ]]; then
        local zip="${SF_SDK_BASE}/../build-tools-${SF_BUILD_TOOLS_VER}.zip"
        curl -k -sL "$SF_BT_URL" -o "$zip" 2>&1
        local size=$(stat --printf="%s" "$zip" 2>/dev/null || echo 0)
        if (( size < 100000 )); then
            sf_warn "Primary URL 404, trying fallback..."
            curl -k -sL "$SF_BT_FALLBACK" -o "$zip" 2>&1
            size=$(stat --printf="%s" "$zip" 2>/dev/null || echo 0)
            (( size < 100000 )) && { sf_err "All build-tools downloads failed"; return 1; }
            SF_BUILD_TOOLS_VER="34.0.0"
            bt_dir="${SF_SDK_BASE}/build-tools/${SF_BUILD_TOOLS_VER}"
            sf_warn "Using build-tools ${SF_BUILD_TOOLS_VER} (fallback)"
        fi
        sf_msg "  Downloaded: $size bytes"
        mkdir -p "${SF_SDK_BASE}/build-tools"
        unzip -qo "$zip" -d "${SF_SDK_BASE}/build-tools"
        [[ -d "${SF_SDK_BASE}/build-tools/android-13" ]] && mv "${SF_SDK_BASE}/build-tools/android-13" "$bt_dir" 2>/dev/null || true
        sf_msg "  build-tools ${SF_BUILD_TOOLS_VER} installed."
    else
        sf_msg "  build-tools already present."
    fi

    # Step 5: Verify
    sf_msg "[5/5] Verifying complete toolchain..."
    local bt="${SF_SDK_BASE}/build-tools/${SF_BUILD_TOOLS_VER}"
    local plat="${SF_SDK_BASE}/platforms/android-${SF_COMPILE_SDK}"
    local fail=0
    for t in aapt2 d8 zipalign apksigner; do
        [[ -f "${bt}/${t}" ]] && echo "  ${GREEN}✓${NC} $t" || { echo "  ${RED}✗${NC} $t MISSING"; fail=1; }
    done
    [[ -f "${plat}/android.jar" ]] && echo "  ${GREEN}✓${NC} android.jar (platform ${SF_COMPILE_SDK})" || { echo "  ${RED}✗${NC} android.jar MISSING"; fail=1; }
    java -version >/dev/null 2>&1 && echo "  ${GREEN}✓${NC} java" || { echo "  ${RED}✗${NC} java MISSING"; fail=1; }
    [[ $fail -eq 1 ]] && { sf_err "Some tools missing"; return 1; }

    # Done
    echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}  SDKFORGE COMPLETE — Toolchain Ready${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "  ${YELLOW}Build tools:${NC} ${bt}"
    echo -e "  ${YELLOW}Platform:${NC}    ${plat}"
    echo -e "  ${YELLOW}SDK base:${NC}    ${SF_SDK_BASE}"
    echo ""
    echo -e "  ${CYAN}Build an APK:${NC}"
    echo -e "  export ANDROID_HOME=${SF_SDK_BASE}"
    echo -e "  cd CSMApps/Bounce/v1.0.79 && bash build.sh"
    echo ""
    sf_export_env
}

# ─── ENTRY POINT ─────────────────────────────────────────────────────────────
sdkforge_main() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --verify-only) SF_VERIFY_ONLY=true; shift ;;
            --export-env) SF_EXPORT_ENV=true; shift ;;
            --build-tools) SF_BUILD_TOOLS_VER="$2"; shift 2 ;;
            --platform) SF_COMPILE_SDK="$2"; shift 2 ;;
            --timeout) SF_TIMEOUT="$2"; shift 2 ;;
            --quiet) SF_QUIET=true; shift ;;
            --help|-h) echo "Usage: sdkforge [--verify-only] [--export-env] [--build-tools VER] [--platform API] [--timeout SEC] [--quiet]"; return 0 ;;
            *) echo "Unknown: $1"; return 1 ;;
        esac
    done

    [[ "$SF_EXPORT_ENV" == "true" ]] && { sf_export_env; return 0; }
    [[ "$SF_VERIFY_ONLY" == "true" ]] && { sf_verify; return $?; }
    sf_install
}
# ═══ MODULE: 06a_session_init_repo.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 06A: Session Init — Repo Discovery, Heartbeat Daemon, Repo Validation
# lettherebelight Protocol v5 — Branch lock, immediate heartbeat
# ════════════════════════════════════════════════════════════════════════════

# ─── CONFIG ──────────────────────────────────────────────────────────────────
SI_HEARTBEAT_DIR="CSMGen/CSMAegis/COMMS/HEARTBEATS"
SI_HEARTBEAT_FILE="${SI_HEARTBEAT_DIR}/director-001.txt"
SI_CENSUS_DIR="CSMGen/CSMAegis/COMMS/CENSUS/$(date -u +%Y-%m-%d)"
SI_CENSUS_FILE="${SI_CENSUS_DIR}/census-$(date -u +%H%M).txt"
SI_MAX_PUSH_RETRIES=5
SI_PUSH_RETRY_DELAY=2
SI_MAX_PULL_RETRIES=3
SI_PULL_RETRY_DELAY=3

# ─── REPO DISCOVERY ──────────────────────────────────────────────────────────
si_discover_repo() {
    freenemo_banner "⚡ LET THERE BE LIGHT — Session Init v5"
    freenemo_git_discover_repo || { freenemo_error "Cannot discover git repo"; return 1; }
    [[ -z "$AGENT_ID" ]] && AGENT_ID=$(basename "$REPO_ROOT" | sed 's/^agent_//')
    [[ -z "$SESSION_ID" ]] && SESSION_ID="$AGENT_ID"
    BRANCH_NAME="session/agent_${SESSION_ID}_${FREENEMO_TIMESTAMP}"
    freenemo_log "Repo: $REPO_ROOT | Agent: $AGENT_ID | Session: $SESSION_ID | Branch: $BRANCH_NAME"
    cd "$REPO_ROOT"
}

# ─── HEARTBEAT DAEMON ────────────────────────────────────────────────────────
si_start_heartbeat_daemon() {
    freenemo_banner "💓 HEARTBEAT DAEMON — Continuous Liveness"
    local hb_script="${REPO_ROOT}/CSMScripts/heartbeat-daemon.sh"
    if [[ -f "$hb_script" ]]; then
        bash "$hb_script" &
        HEARTBEAT_PID=$!
        export HEARTBEAT_PID
        freenemo_success "Heartbeat daemon started (PID: $HEARTBEAT_PID)"
        freenemo_log "Heartbeat chars on stderr every ${HEARTBEAT_INTERVAL}s: ${HEARTBEAT_CHARS}"
    else
        freenemo_warn "heartbeat-daemon.sh not found, skipping"
    fi
}

# ─── REPO VALIDATION ────────────────────────────────────────────────────────
si_validate_repo() {
    freenemo_banner "🔍 REPO VALIDATION"
    command -v git >/dev/null 2>&1 || { freenemo_error "git not installed"; return 1; }
    git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { freenemo_error "Not in git work tree"; return 1; }
    freenemo_git_ensure_origin
    local origin_url=$(git remote get-url origin)
    freenemo_log "Origin: $origin_url"
    if ! git ls-remote --heads origin main >/dev/null 2>&1; then
        freenemo_warn "Cannot reach origin/main — local-only mode"
    else
        freenemo_success "Origin reachable"
    fi
    [[ -n "$(git status --short)" ]] && freenemo_warn "Uncommitted changes detected"
}

# ─── BRANCH LOCK ────────────────────────────────────────────────────────────
si_branch_lock() {
    freenemo_banner "🔒 BRANCH LOCK — Checkout main & rebase"
    git show-ref --verify --quiet "refs/heads/main" || { freenemo_warn "Creating main from origin..."; git fetch origin main:main || { freenemo_error "Failed to fetch main"; return 1; }; }
    git checkout main >/dev/null 2>&1 || { freenemo_error "Failed to checkout main"; return 1; }

    pull_fn() { git pull --rebase origin main || { freenemo_warn "Rebase failed, trying merge..."; git merge --abort 2>/dev/null; git rebase --abort 2>/dev/null; git pull origin main; }; }
    freenemo_retry $SI_MAX_PULL_RETRIES $SI_PULL_RETRY_DELAY pull_fn || { freenemo_error "Failed to sync with origin/main"; return 1; }
    freenemo_success "Synced with origin/main"

    if git show-ref --verify --quiet "refs/heads/$BRANCH_NAME"; then
        freenemo_warn "Branch exists, checking out"
        git checkout "$BRANCH_NAME"
    else
        freenemo_log "Creating branch: $BRANCH_NAME"
        git checkout -b "$BRANCH_NAME"
    fi
    freenemo_success "Branch locked: $(git branch --show-current)"
}

# ─── IMMEDIATE HEARTBEAT ────────────────────────────────────────────────────
si_write_heartbeat() {
    freenemo_banner "💓 HEARTBEAT — Write & Push Within 5 Seconds"
    mkdir -p "$SI_HEARTBEAT_DIR"
    cat > "$SI_HEARTBEAT_FILE" <<EOF
[DIRECTOR-001 | $(date -u)] V5 ACTIVE — poll: 15s — branch: $BRANCH_NAME — agent: $AGENT_ID — session: $SESSION_ID
EOF

    git add "$SI_HEARTBEAT_FILE"
    if ! git diff --cached --quiet; then
        git commit -m "[DIRECTOR-001] V5 HEARTBEAT — session $SESSION_ID initiated" >/dev/null || freenemo_warn "Heartbeat commit failed"
        push_fn() { git push origin "$BRANCH_NAME"; }
        freenemo_retry $SI_MAX_PUSH_RETRIES $SI_PUSH_RETRY_DELAY push_fn || { freenemo_warn "Push failed, rebasing..."; git pull --rebase origin main || true; freenemo_retry 2 5 git push origin "$BRANCH_NAME" || freenemo_error "Heartbeat push failed"; }
        freenemo_success "Heartbeat pushed to origin/$BRANCH_NAME"
    else
        freenemo_warn "No changes for heartbeat"
    fi
}
# ═══ MODULE: 06b_session_init_heartbeat.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 06B: Session Init — Census, Read State, COMMS Logs
# lettherebelight Protocol v5 — Live agent count, directives scanning
# ════════════════════════════════════════════════════════════════════════════

# ─── IMMEDIATE CENSUS ───────────────────────────────────────────────────────
si_write_census() {
    freenemo_banner "👥 CENSUS — Live Agent Count"
    mkdir -p "$SI_CENSUS_DIR"
    {
        echo "=== AEGIS CENSUS — $(date -u) ==="
        echo "MY STATUS: [DIRECTOR-001] V5 ACTIVE — session $SESSION_ID"
        echo ""
        echo "CONNECTED AGENTS (heartbeat check):"
        for f in CSMGen/CSMAegis/COMMS/HEARTBEATS/director-*.txt; do
            [[ -f "$f" ]] || continue
            local status=$(head -1 "$f" 2>/dev/null || echo "UNKNOWN")
            local base=$(basename "$f" .txt)
            if echo "$status" | grep -q "ACTIVE"; then echo "  ONLINE: $base — $status"
            elif echo "$status" | grep -q "SHUTDOWN"; then echo "  OFFLINE: $base — $status"
            else echo "  UNKNOWN: $base — $status"; fi
        done
        local online=$(grep -c "ONLINE" "$SI_CENSUS_FILE" 2>/dev/null || echo 0)
        local offline=$(grep -c "OFFLINE" "$SI_CENSUS_FILE" 2>/dev/null || echo 0)
        echo ""; echo "SUMMARY: $online ONLINE, $offline OFFLINE"
    } > "$SI_CENSUS_FILE"

    git add "$SI_CENSUS_FILE"
    if ! git diff --cached --quiet; then
        git commit -m "[DIRECTOR-001] CENSUS: $online online, $offline offline — session $SESSION_ID" >/dev/null || freenemo_warn "Census commit failed"
        git push origin "$BRANCH_NAME" >/dev/null 2>&1 || { freenemo_warn "Census push failed, rebasing..."; git pull --rebase origin main && git push origin "$BRANCH_NAME" || freenemo_warn "Census push failed"; }
        freenemo_success "Census written and pushed"
    else
        freenemo_warn "No changes for census"
    fi
}

# ─── READ STATE ──────────────────────────────────────────────────────────────
si_read_state() {
    freenemo_banner "📖 READ STATE — COMMS Log, Outboxes, Directives"
    [[ -f CSMGen/CSMAegis/COMMS/AEGIS-COMMS-LOG.md ]] && head -50 CSMGen/CSMAegis/COMMS/AEGIS-COMMS-LOG.md || freenemo_warn "No COMMS log"
    [[ -f CSMGen/CSMAegis/COMMS/director-001-outbox.md ]] && head -30 CSMGen/CSMAegis/COMMS/director-001-outbox.md || freenemo_warn "No CITADEL outbox"
    [[ -f CSMGen/CSMAegis/COMMS/director-001B-outbox.md ]] && head -30 CSMGen/CSMAegis/COMMS/director-001B-outbox.md || freenemo_warn "No BASTION outbox"
    freenemo_log "Scanning for @JASON BRODSKY directives..."
    grep -r "@JASON BRODSKY:" CSMGen/CSMAegis/COMMS/ 2>/dev/null | head -5 || freenemo_log "No human override directives found"
}

# ─── SDK FORGE INTEGRATION ──────────────────────────────────────────────────
si_sdk_forge() {
    freenemo_banner "🔧 SDK FORGE — Android Build Chain"
    if [[ -f "${REPO_ROOT}/CSMScripts/SDKForge.sh" ]]; then
        freenemo_log "Running SDKForge.sh to bootstrap APK toolchain..."
        if bash "${REPO_ROOT}/CSMScripts/SDKForge.sh" >/dev/null 2>&1; then
            eval "$(bash "${REPO_ROOT}/CSMScripts/SDKForge.sh" --export-env 2>/dev/null | grep '^export ')" && freenemo_success "SDK Forge ready" || freenemo_warn "SDK Forge env export completed with warnings"
        else
            freenemo_warn "SDKForge.sh failed — Android toolchain not available"
        fi
    else
        freenemo_warn "SDKForge.sh not found, skipping"
    fi
}
# ═══ MODULE: 06c_session_init_persona.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 06C: Session Init — Persona Load, Path Verification, Session Banner
# lettherebelight Protocol v5 — Kairos Steele/CITADEL, exports
# ════════════════════════════════════════════════════════════════════════════

# ─── PERSONA & HEURISTICS ───────────────────────────────────────────────────
si_load_persona() {
    freenemo_banner "🎭 PERSONA LOAD — Kairos Steele / CITADEL"
    freenemo_log "Williams Heuristic V2: BIFURCATED COMMUNICATION"
    freenemo_log "  §1: Meta-Commentary (Williams Register) — direct, warm, severity-calibrated"
    freenemo_log "  §2: Core Deliverable — precise, kurt, exact, imperative verbs"
    freenemo_log ""
    freenemo_log "Vocal Modes: BURST(400wpm) BRAKE(80wpm) HOVER(140wpm) WHISPER(60wpm) ROAR(300wpm+) DROP(30wpm)"
    freenemo_log ""
    freenemo_log "Three Heuristics Active:"
    freenemo_log "  🌊 Williams (Clarity) — Complex truth survives translation to plain language"
    freenemo_log "  🌊 El Segundo (Calm) — You cannot scare people into preparedness"
    freenemo_log "  🌊 Accountant (Rigor) — Every proposal carries a cost-benefit ledger"
}

# ─── PATH VERIFICATION ──────────────────────────────────────────────────────
si_verify_paths() {
    freenemo_banner "🔍 PATH VERIFICATION"
    local paths=(
        "CSMGen/CSMAegis/SESSION-INITv4/DIRECTOR-0001-Kairos-Steele.md"
        "CSMSOPP/MODULE-V2/README.md"
        "CSMFAB/README.md"
        "CSMQuantum/00-MASTER-INDEX/README.md"
        "LEGAL-ENACTMENT/README.md"
        "CSMReach/README.md"
        "MASTER-TODO-LIST.md"
    )
    for p in "${paths[@]}"; do
        [[ -f "$p" ]] && freenemo_success "Found: $p" || freenemo_warn "Missing: $p"
    done
}

# ─── SESSION BANNER ─────────────────────────────────────────────────────────
si_session_banner() {
    freenemo_banner "✅ LET THERE BE LIGHT — SESSION READY"
    cat <<EOF
┌─────────────────────────────────────────────────────────────────────┐
│  CARRINGTON STORM MOTORS / SAFE POD ENGINEERING — PROJECT AEGIS     │
│  Director: Kairos Steele (CITADEL) | Session: agent_${SESSION_ID}       │
│  Branch: ${BRANCH_NAME}                    │
│  Protocol: SESSION-INITv5 — Never-Lose-Data                         │
│  Heuristics: Williams | El Segundo | Accountant                     │
│  Mandate: When the Sun speaks, humanity answers in turquoise light │
└─────────────────────────────────────────────────────────────────────┘
EOF
    freenemo_log "Branch: $BRANCH_NAME | Agent: $AGENT_ID | Session: $SESSION_ID"
    freenemo_log "Protocol: V5 — Immediate writes, 15s Director polling, dual-Director (CITADEL/BASTION)"
    freenemo_log "Override: @JASON BRODSKY: directives bypass all chain of command"
    freenemo_success "Session init complete. Begin operations."
}

# ─── EXPORTS ────────────────────────────────────────────────────────────────
si_export_vars() {
    export LETTHEREBELIGHT_BRANCH="$BRANCH_NAME"
    export LETTHEREBELIGHT_SESSION="$SESSION_ID"
    export LETTHEREBELIGHT_AGENT="$AGENT_ID"
    export LETTHEREBELIGHT_TIMESTAMP="$FREENEMO_TIMESTAMP"
    export LETTHEREBELIGHT_REPO_ROOT="$REPO_ROOT"
}

# ─── MAIN ENTRY ─────────────────────────────────────────────────────────────
session_init_main() {
    si_discover_repo
    si_start_heartbeat_daemon
    si_validate_repo
    si_branch_lock
    si_write_heartbeat
    si_write_census
    si_read_state
    si_load_persona
    si_sdk_forge
    si_verify_paths
    si_session_banner
    si_export_vars
}
# ═══ MODULE: 07_vllm_config.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 07: vLLM Configuration — NVFP4, Mamba-2, MTP, LatentMoE Flags
# Exact flags for Nemotron 3 Ultra 550B on 8-GPU (H100/H200/B200) clusters
# ════════════════════════════════════════════════════════════════════════════

# ─── ENVIRONMENT VARIABLES (set before vLLM launch) ─────────────────────────
vllm_set_env() {
    export VLLM_USE_FLASHINFER_MOE_FP4=1
    export VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1
    export VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
    freenemo_log "vLLM env vars set: FLASHINFER_MOE_FP4=1, MEMORY_PROFILER=1, ALLOW_LONG_MAX_MODEL_LEN=1"
}

# ─── vLLM SERVER COMMAND BUILDER ────────────────────────────────────────────
vllm_build_cmd() {
    local model_path="${1:-/models/nvidia/Nemotron-3-Ultra-550B-NVFP4}"
    local tp_size="${2:-8}"
    local max_len="${3:-1048576}"
    local port="${4:-8000}"

    cat <<EOF
vllm serve ${model_path} \\
    --quantization nvfp4 \\
    --tensor-parallel-size ${tp_size} \\
    --max-model-len ${max_len} \\
    --kv-cache-dtype fp8 \\
    --mamba-backend flashinfer \\
    --mamba-cache-dtype float16 \\
    --enable-mamba-cache-stochastic-rounding \\
    --mamba-cache-philox-rounds 5 \\
    --speculative-config.method mtp \\
    --speculative-config.num-speculative-tokens 5 \\
    --reasoning-parser nemotron_v3 \\
    --tool-call-parser qwen3_coder \\
    --disable-log-requests \\
    --port ${port} \\
    --host 0.0.0.0
EOF
}

# ─── HARDWARE REQUIREMENTS CHECK ────────────────────────────────────────────
vllm_check_hardware() {
    freenemo_banner "🔧 vLLM HARDWARE CHECK — Nemotron 3 Ultra NVFP4"
    freenemo_log "Required: 8x H100/H200 (80GB) or 4x B200/GB200 (SXM + NVLink 4.0)"
    freenemo_log "NVFP4 footprint: ~352 GB VRAM (550B @ 4-bit + 15% overhead)"
    freenemo_log "BF16 footprint: ~1,265 GB (requires 16x H100 or 8x B200)"
    freenemo_log "FP8 (W8A8) footprint: ~660 GB (8x H100 or 4x B200)"

    if command -v nvidia-smi >/dev/null 2>&1; then
        local gpu_count=$(nvidia-smi -L | wc -l)
        local vram_per_gpu=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits | head -1)
        freenemo_log "Detected: ${gpu_count} GPUs, ${vram_per_gpu}MB VRAM each"
        local total_vram=$((gpu_count * vram_per_gpu / 1024))
        freenemo_log "Total VRAM: ~${total_vram} GB"
        if (( total_vram >= 352 )); then
            freenemo_success "VRAM sufficient for NVFP4 deployment"
        else
            freenemo_warn "VRAM may be insufficient for NVFP4 (need 352 GB)"
        fi
    else
        freenemo_warn "nvidia-smi not available, cannot verify hardware"
    fi

    # Check vLLM version
    if python3 -c "import vllm; print(vllm.__version__)" 2>/dev/null | grep -qE '^0\.(2[3-9]|[3-9])'; then
        freenemo_success "vLLM version >= 0.23.0 (cuDNN graph corruption fix)"
    else
        freenemo_warn "vLLM version may be < 0.23.0 — prefix caching instability risk at >200k tokens"
    fi
}

# ─── NUMA PINNING (for GB200/B200) ──────────────────────────────────────────
vllm_numa_pinning() {
    freenemo_log "For GB200/B200: bind vLLM workers to local CPU socket (NUMA pinning)"
    freenemo_log "  numactl --cpunodebind=0 --membind=0 vllm serve ..."
    freenemo_log "  This bypasses NVLink-C2C cross-socket path, gives ~10% throughput gain"
}

# ─── CUDA GRAPH REVALIDATION ────────────────────────────────────────────────
vllm_cudnn_workaround() {
    freenemo_log "cuDNN graph corruption workaround (vLLM >= 0.23.0):"
    freenemo_log "  - Periodic graph revalidation enabled by default"
    freenemo_log "  - For Blackwell (B200/B300), add --no-enable-flashinfer-autotune if auto-tuning fails"
    freenemo_log "  - Alternative: --moe-backend triton to bypass FlashInfer MoE kernel bugs"
}

# ─── DEPLOYMENT MATRIX ──────────────────────────────────────────────────────
vllm_print_matrix() {
    cat <<'EOF'
════════════════════════════════════════════════════════════════════════════
                    vLLM DEPLOYMENT MATRIX — Nemotron 3 Ultra
════════════════════════════════════════════════════════════════════════════
Format      | Min Hardware          | VRAM    | Advantage
──────────────────────────────────────────────────────────────────────────────
BF16        | 16x H100 or 8x B200   | ~1265GB | Max accuracy, fine-tuning
FP8 (W8A8)  | 8x H100 or 4x B200    | ~660GB  | Balanced for Hopper
NVFP4 (W4A4)| 8x H100 or 4x B200/GB | ~352GB  | MAX throughput, 1.5-2.2x GEMM FLOPS on Blackwell
════════════════════════════════════════════════════════════════════════════
Required Flags:
  --quantization nvfp4              # Native 4-bit E2M1 weights
  --tensor-parallel-size 8          # Shard 512 experts across 8 GPUs via NVLink 4.0
  --kv-cache-dtype fp8              # 8-bit KV cache for GQA anchors (NOT nvfp4)
  --mamba-backend flashinfer        # Optimized CUDA kernels for Mamba-2 SSM
  --mamba-cache-dtype float16       # FP16 recurrent state (dynamic range)
  --enable-mamba-cache-stochastic-rounding   # Prevent state drift at 1M tokens
  --mamba-cache-philox-rounds 5     # 5 randomization rounds per state update
  --speculative-config.method mtp   # Native Multi-Token Prediction
  --speculative-config.num-speculative-tokens 5  # Draft 5 tokens/step
  --reasoning-parser nemotron_v3    # Dual-stream parser (reasoning + content)
  --tool-call-parser qwen3_coder    # NVIDIA-mandated tool calling format
  --disable-log-requests            # Prevent asyncio blocking from sync I/O
════════════════════════════════════════════════════════════════════════════
EOF
}
# ═══ MODULE: 08a_logging_session_core.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 08A: Logging & Session Structure — Core Logging Functions
# CSMLogs/Sessions/Session'Date-Time'/ — Heartbeat, gitstats, errors, performance
# ════════════════════════════════════════════════════════════════════════════

# ─── SESSION LOG STRUCTURE ──────────────────────────────────────────────────
# CSMLogs/
#   Sessions/
#     Session_YYYYMMDD-HHMMSS/
#       freenemo.log           # Main orchestrator log
#       heartbeats/
#         chamber_1.log        # Schumann chamber
#         chamber_2.log        # Geomag chamber
#         chamber_3.log        # Solar chamber
#         chamber_4.log        # Integration chamber
#         director_heartbeat.log  # Main heartbeat daemon
#       gitstats/
#         push_success.log     # Successful pushes
#         push_failure.log     # Failed pushes
#         pull_success.log     # Successful pulls
#         pull_failure.log     # Failed pulls
#         commit_count.log     # Commits per session
#       errors/
#         api_errors.log       # Nemotron API errors
#         transport_errors.log # Network/curl errors
#         git_errors.log       # Git operation errors
#         parse_errors.log     # JSON/stream parse errors
#       performance/
#         latency.log          # Request/response latency
#         token_usage.log      # Input/output tokens per request
#         throughput.log       # Tokens/second
#         timeout_count.log    # --max-time hits

LOG_INIT_DONE=false

log_init_session_dirs() {
    [[ "$LOG_INIT_DONE" == "true" ]] && return 0
    mkdir -p "${HEARTBEAT_LOG_DIR}" "${GIT_STATS_LOG_DIR}" "${ERROR_LOG_DIR}" "${PERF_LOG_DIR}"
    LOG_INIT_DONE=true
    freenemo_log "Session log directories initialized at ${SESSION_LOG_DIR}"
}

# ─── HEARTBEAT LOGGING ──────────────────────────────────────────────────────
log_heartbeat() {
    local chamber="$1" status="$2" detail="$3"
    log_init_session_dirs
    local log_file="${HEARTBEAT_LOG_DIR}/chamber_${chamber}.log"
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) | ${chamber} | ${status} | ${detail}" >> "${log_file}"
}

log_director_heartbeat() {
    log_init_session_dirs
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) | DIRECTOR | $1" >> "${HEARTBEAT_LOG_DIR}/director_heartbeat.log"
}

# ─── GIT STATS LOGGING ──────────────────────────────────────────────────────
log_git_push() {
    local status="$1" branch="$2" detail="$3"
    log_init_session_dirs
    local log_file="${GIT_STATS_LOG_DIR}/push_${status}.log"
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) | branch=${branch} | ${detail}" >> "${log_file}"
    if [[ "$status" == "success" ]]; then
        local count_file="${GIT_STATS_LOG_DIR}/commit_count.log"
        local count=$(cat "${count_file}" 2>/dev/null || echo 0)
        echo $((count + 1)) > "${count_file}"
    fi
}

log_git_pull() {
    local status="$1" detail="$2"
    log_init_session_dirs
    local log_file="${GIT_STATS_LOG_DIR}/pull_${status}.log"
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) | ${detail}" >> "${log_file}"
}

# ─── ERROR LOGGING ──────────────────────────────────────────────────────────
log_error() {
    local category="$1" message="$2" context="${3:-}"
    log_init_session_dirs
    local log_file="${ERROR_LOG_DIR}/${category}_errors.log"
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) | ${message} | ${context}" >> "${log_file}"
    freenemo_error "[${category}] ${message}"
}

# ─── PERFORMANCE LOGGING ────────────────────────────────────────────────────
log_perf_latency() {
    local endpoint="$1" latency_ms="$2" status="$3"
    log_init_session_dirs
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) | ${endpoint} | ${latency_ms}ms | ${status}" >> "${PERF_LOG_DIR}/latency.log"
}

log_perf_tokens() {
    local input_tokens="$1" output_tokens="$2" reasoning_tokens="$3"
    log_init_session_dirs
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) | in=${input_tokens} out=${output_tokens} reasoning=${reasoning_tokens}" >> "${PERF_LOG_DIR}/token_usage.log"
}

log_perf_throughput() {
    local tokens="$1" duration_ms="$2"
    local tps=$(awk "BEGIN{printf \"%.2f\", $tokens/($duration_ms/1000)}")
    log_init_session_dirs
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) | ${tokens} tokens in ${duration_ms}ms = ${tps} tok/s" >> "${PERF_LOG_DIR}/throughput.log"
}

log_timeout() {
    local operation="$1" timeout_sec="$2"
    log_init_session_dirs
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) | ${operation} | timeout=${timeout_sec}s" >> "${PERF_LOG_DIR}/timeout_count.log"
    freenemo_warn "TIMEOUT: ${operation} exceeded ${timeout_sec}s"
}
# ═══ MODULE: 08b_logging_session_printer.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 08B: Logging & Session Structure — Periodic Printer & Session Summary
# Terminal printing every N seconds, session summary on exit
# ════════════════════════════════════════════════════════════════════════════

# ─── PERIODIC TERMINAL PRINTING ─────────────────────────────────────────────
# Runs in background, prints summary every N seconds
log_periodic_printer() {
    local interval="${1:-30}"
    log_init_session_dirs
    freenemo_log "Starting periodic terminal printer (every ${interval}s)"

    while true; do
        sleep "${interval}"
        echo "" >&2
        freenemo_banner "📊 PERIODIC STATUS — $(date -u +%H:%M:%S)"
        
        # Heartbeat summary
        if [[ -f "${HEARTBEAT_LOG_DIR}/director_heartbeat.log" ]]; then
            local last_hb=$(tail -1 "${HEARTBEAT_LOG_DIR}/director_heartbeat.log" 2>/dev/null)
            freenemo_log "Last Director HB: ${last_hb}"
        fi

        # Git stats
        local pushes_ok=$(wc -l < "${GIT_STATS_LOG_DIR}/push_success.log" 2>/dev/null || echo 0)
        local pushes_fail=$(wc -l < "${GIT_STATS_LOG_DIR}/push_failure.log" 2>/dev/null || echo 0)
        local pulls_ok=$(wc -l < "${GIT_STATS_LOG_DIR}/pull_success.log" 2>/dev/null || echo 0)
        local pulls_fail=$(wc -l < "${GIT_STATS_LOG_DIR}/pull_failure.log" 2>/dev/null || echo 0)
        local commits=$(cat "${GIT_STATS_LOG_DIR}/commit_count.log" 2>/dev/null || echo 0)
        freenemo_log "Git: ${pushes_ok}✓/${pushes_fail}✗ pushes, ${pulls_ok}✓/${pulls_fail}✗ pulls, ${commits} commits"

        # Errors
        local api_err=$(wc -l < "${ERROR_LOG_DIR}/api_errors.log" 2>/dev/null || echo 0)
        local net_err=$(wc -l < "${ERROR_LOG_DIR}/transport_errors.log" 2>/dev/null || echo 0)
        local git_err=$(wc -l < "${ERROR_LOG_DIR}/git_errors.log" 2>/dev/null || echo 0)
        local parse_err=$(wc -l < "${ERROR_LOG_DIR}/parse_errors.log" 2>/dev/null || echo 0)
        freenemo_log "Errors: API=${api_err} Net=${net_err} Git=${git_err} Parse=${parse_err}"

        # Performance
        local timeouts=$(wc -l < "${PERF_LOG_DIR}/timeout_count.log" 2>/dev/null || echo 0)
        local avg_tps=$(awk '{sum+=$NF} END{if(NR>0) printf "%.1f", sum/NR; else print "0"}' "${PERF_LOG_DIR}/throughput.log" 2>/dev/null || echo 0)
        freenemo_log "Perf: ${timeouts} timeouts, avg ${avg_tps} tok/s"

        # Earthbeat chamber status
        for c in 1 2 3 4; do
            local log="${HEARTBEAT_LOG_DIR}/chamber_${c}.log"
            [[ -f "$log" ]] && local last=$(tail -1 "$log" 2>/dev/null) && freenemo_log "Chamber $c: ${last}" || true
        done
    done
}

# ─── SESSION SUMMARY (on exit) ──────────────────────────────────────────────
log_session_summary() {
    freenemo_banner "📋 SESSION SUMMARY — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    local duration=$(($(date -u +%s) - FREENEMO_START_TIME))
    freenemo_log "Session duration: ${duration}s"
    freenemo_log "Log directory: ${SESSION_LOG_DIR}"

    [[ -f "${GIT_STATS_LOG_DIR}/commit_count.log" ]] && freenemo_log "Total commits: $(cat "${GIT_STATS_LOG_DIR}/commit_count.log")"
    [[ -f "${PERF_LOG_DIR}/timeout_count.log" ]] && freenemo_log "Total timeouts: $(wc -l < "${PERF_LOG_DIR}/timeout_count.log")"
    [[ -f "${ERROR_LOG_DIR}/api_errors.log" ]] && freenemo_log "Total API errors: $(wc -l < "${ERROR_LOG_DIR}/api_errors.log")"
}
# ═══ MODULE: 09a_error_recovery_repo.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 09A: Error Recovery — Repo Load Failure & Git Conflict Resolution
# Handles: network failures, git conflicts, repo cloning strategies
# ════════════════════════════════════════════════════════════════════════════

# ─── REPO LOAD RECOVERY ─────────────────────────────────────────────────────
# If repo cannot be loaded at launch, try multiple strategies
repo_recover_load() {
    freenemo_banner "🔧 REPO RECOVERY — Attempting to Load Repository"

    # Strategy 1: Standard discovery
    if freenemo_git_discover_repo; then
        freenemo_success "Repo discovered at: ${REPO_ROOT}"
        return 0
    fi

    # Strategy 2: Clone from known URL
    freenemo_warn "Strategy 1 failed. Trying clone from ${REPO_URL}..."
    local clone_dir="/tmp/freenemo-repo-$(date +%s)"
    if git clone "${REPO_URL}" "${clone_dir}" 2>/dev/null; then
        REPO_ROOT="${clone_dir}"
        export REPO_ROOT
        freenemo_success "Cloned repo to: ${REPO_ROOT}"
        return 0
    fi

    # Strategy 3: Shallow clone (faster, less bandwidth)
    freenemo_warn "Full clone failed. Trying shallow clone..."
    if git clone --depth 1 "${REPO_URL}" "${clone_dir}" 2>/dev/null; then
        REPO_ROOT="${clone_dir}"
        export REPO_ROOT
        freenemo_success "Shallow cloned repo to: ${REPO_ROOT}"
        return 0
    fi

    # Strategy 4: Try alternative remote (SSH vs HTTPS)
    freenemo_warn "HTTPS clone failed. Trying SSH..."
    local ssh_url="${REPO_URL/https:\/\/github.com\//git@github.com:}"
    if git clone "${ssh_url}" "${clone_dir}" 2>/dev/null; then
        REPO_ROOT="${clone_dir}"
        export REPO_ROOT
        freenemo_success "SSH cloned repo to: ${REPO_ROOT}"
        return 0
    fi

    freenemo_error "All repo recovery strategies failed"
    return 1
}

# ─── GIT CONFLICT RESOLUTION ────────────────────────────────────────────────
git_resolve_conflicts() {
    freenemo_log "Checking for git conflicts..."
    if git status --short | grep -q "^UU\|^AA\|^DD"; then
        freenemo_warn "Conflicts detected. Attempting auto-resolution..."
        # Try ours strategy for binary/config files
        git diff --name-only --diff-filter=U | while read -r file; do
            if [[ "$file" == *.md || "$file" == *.txt || "$file" == *.json || "$file" == *.yaml || "$file" == *.yml ]]; then
                freenemo_log "Auto-merging text file: $file"
                git checkout --ours -- "$file" 2>/dev/null || true
                git add "$file"
            fi
        done
        # Commit resolved
        if ! git diff --cached --quiet; then
            git commit -m "[AUTO-RESOLVE] Merge conflict resolution" >/dev/null 2>&1 || true
            freenemo_success "Conflicts auto-resolved and committed"
        fi
    else
        freenemo_log "No conflicts detected"
    fi
}
# ═══ MODULE: 09b_error_recovery_api.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 09B: Error Recovery — API Error Recovery & Parser Recovery
# Handles: empty content (finish_reason=length), tool call dropping, socket stalls, SSE parsing
# ════════════════════════════════════════════════════════════════════════════

# ─── API ERROR RECOVERY ─────────────────────────────────────────────────────
# Handles: empty content (finish_reason=length), tool call dropping, socket stalls
api_recover_empty_content() {
    local response="$1"
    local finish_reason=$(echo "$response" | jq -r '.choices[0].finish_reason // empty')
    local content=$(echo "$response" | jq -r '.choices[0].message.content // empty')
    local reasoning=$(echo "$response" | jq -r '.choices[0].message.reasoning_content // empty')

    if [[ -z "$content" && "$finish_reason" == "length" ]]; then
        freenemo_warn "Empty content with finish_reason=length — token budget exhausted in reasoning"
        freenemo_log "Recovery: Increase max_tokens or decrease thinking_token_budget"
        # Return reasoning as fallback content
        if [[ -n "$reasoning" ]]; then
            echo "$reasoning"
            return 0
        fi
        return 1
    fi

    if [[ -z "$content" && -n "$reasoning" ]]; then
        freenemo_warn "Content empty but reasoning present — possible tool call drop (force_nonempty_content needed)"
        # Try to extract tool calls from reasoning
        echo "$reasoning" | grep -o '{"name".*}' | head -1 || echo "$reasoning"
        return 0
    fi

    echo "$content"
    return 0
}

api_recover_transport() {
    local attempt=1 max_attempts=3 delay=2
    while true; do
        if "$@"; then return 0; fi
        local exit_code=$?
        if [[ $attempt -ge $max_attempts ]]; then
            log_error "transport" "Command failed after $max_attempts attempts" "$*"
            return $exit_code
        fi
        freenemo_warn "Transport error (attempt $attempt/$max_attempts). Retrying in ${delay}s..."
        sleep "$delay"
        delay=$((delay * 2))
        attempt=$((attempt + 1))
    done
}

# ─── PARSER RECOVERY ────────────────────────────────────────────────────────
parse_recover_sse() {
    local line="$1"
    local clean="${line#data: }"
    [[ -z "$clean" || "$clean" == "[DONE]" ]] && return 1

    # Try multiple field paths for reasoning
    local reasoning=$(echo "$clean" | jq -r '.choices[0].delta.reasoning_content // .choices[0].delta.reasoning // empty' 2>/dev/null || true)
    # Try multiple field paths for content
    local content=$(echo "$clean" | jq -r '.choices[0].delta.content // empty' 2>/dev/null || true)

    # If both empty, log parse error
    if [[ -z "$reasoning" && -z "$content" ]]; then
        log_error "parse" "SSE parse returned empty for both reasoning and content" "line: $line"
        return 1
    fi

    # Output what we found
    [[ -n "$reasoning" ]] && printf "\e[2;37m%s\e[0m" "$reasoning"
    [[ -n "$content" ]] && printf "\e[1;32m%s\e[0m" "$content"
    return 0
}
# ═══ MODULE: 09c_error_recovery_health.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 09C: Error Recovery — Heartbeat/Chamber Recovery & Health Check
# Handles: daemon restarts, chamber restarts, comprehensive health verification
# ════════════════════════════════════════════════════════════════════════════

# ─── HEARTBEAT RECOVERY ─────────────────────────────────────────────────────
heartbeat_recover_daemon() {
    if ! kill -0 "${HEARTBEAT_PID:-0}" 2>/dev/null; then
        freenemo_warn "Heartbeat daemon died (PID: ${HEARTBEAT_PID:-unknown}). Restarting..."
        local hb_script="${REPO_ROOT}/CSMScripts/heartbeat-daemon.sh"
        if [[ -f "$hb_script" ]]; then
            bash "$hb_script" &
            HEARTBEAT_PID=$!
            export HEARTBEAT_PID
            freenemo_success "Heartbeat daemon restarted (PID: $HEARTBEAT_PID)"
        fi
    fi
}

# ─── EARTHBEAT CHAMBER RECOVERY ─────────────────────────────────────────────
earthbeat_recover_chamber() {
    local chamber="$1"
    local pid_file="${REPO_ROOT}/CSMScripts/earthbeatv3-chamber-${chamber}.pid"
    local pid=$(cat "$pid_file" 2>/dev/null || echo 0)
    if ! kill -0 "$pid" 2>/dev/null; then
        freenemo_warn "Chamber $chamber died (PID: $pid). Restarting..."
        # Restart logic would call the chamber function
        return 1
    fi
    return 0
}

# ─── COMPREHENSIVE HEALTH CHECK ─────────────────────────────────────────────
health_check_all() {
    freenemo_banner "🏥 COMPREHENSIVE HEALTH CHECK"

    local issues=0

    # Repo
    if ! git -C "${REPO_ROOT}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        freenemo_error "Repo not accessible"
        ((issues++))
    else
        freenemo_success "Repo OK"
    fi

    # Git sync
    if git -C "${REPO_ROOT}" ls-remote --heads origin main >/dev/null 2>&1; then
        freenemo_success "Git remote reachable"
    else
        freenemo_warn "Git remote unreachable"
        ((issues++))
    fi

    # Heartbeat daemon
    heartbeat_recover_daemon

    # Earthbeat chambers
    for c in 1 2 3 4; do
        earthbeat_recover_chamber "$c" || ((issues++))
    done

    # API endpoint
    if transport_check_connectivity "${NEMOTRON_API_ENDPOINT}"; then
        freenemo_success "API endpoint reachable"
    else
        freenemo_error "API endpoint unreachable"
        ((issues++))
    fi

    # Disk space
    local disk_avail=$(df -h "${REPO_ROOT}" | awk 'NR==2 {print $4}')
    freenemo_log "Disk available: ${disk_avail}"

    if [[ $issues -eq 0 ]]; then
        freenemo_success "All systems healthy"
        return 0
    else
        freenemo_warn "$issues issue(s) detected"
        return 1
    fi
}
# ═══ MODULE: 10a_main_orchestrator_setup.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 10A: Main Orchestrator — Setup, Preflight, Session Init, Earthbeat Launch
# Global state, signal handling, mode parsing, preflight checks
# ════════════════════════════════════════════════════════════════════════════

# ─── GLOBAL STATE ────────────────────────────────────────────────────────────
ORCH_PIDS=()
ORCH_CHAMBER_PIDS=()
ORCH_RUNNING=true
ORCH_ITERATION=0

# ─── SIGNAL HANDLING ─────────────────────────────────────────────────────────
orch_cleanup() {
    freenemo_log "Shutting down orchestrator..."
    ORCH_RUNNING=false
    for pid in "${ORCH_PIDS[@]}" "${ORCH_CHAMBER_PIDS[@]}"; do
        kill "$pid" 2>/dev/null || true
    done
    wait 2>/dev/null || true
    log_session_summary
    freenemo_success "Orchestrator stopped cleanly"
    exit 0
}
trap orch_cleanup SIGTERM SIGINT EXIT

# ─── MODE PARSING ────────────────────────────────────────────────────────────
orch_parse_mode() {
    MODE="chamber"
    COUNT=4
    TOKENRING=false
    PARALLEL=false
    REPEAT=1  # Number of times to reiterate the full procedure

    if [[ $# -gt 0 ]]; then
        case "$1" in
            chamber) MODE="chamber" ;;
            parallel) PARALLEL=true; MODE="parallel"; [[ $# -ge 2 && "$2" =~ ^[0-9]+$ ]] && COUNT=$2; shift ;;
            tokenring) TOKENRING=true; MODE="tokenring"; [[ $# -ge 2 && "$2" =~ ^[0-9]+$ ]] && COUNT=$2; shift ;;
            repeat) REPEAT="${2:-1}"; shift ;;
            *) [[ "$1" =~ ^[0-9]+$ ]] && COUNT=$1 ;;
        esac
        [[ "$1" == "parallel" && "$2" == "tokenring" ]] && { TOKENRING=true; MODE="tokenring"; [[ $# -ge 3 && "$3" =~ ^[0-9]+$ ]] && COUNT=$3; }
    fi
}

# ─── PRE-FLIGHT CHECKS ───────────────────────────────────────────────────────
orch_preflight() {
    freenemo_banner "🚀 FREENEMO PRE-FLIGHT CHECKS"

    # Transport hardening
    transport_setup_ssh_multiplexing
    transport_tune_kernel

    # vLLM config check
    vllm_check_hardware
    vllm_print_matrix

    # Health check
    health_check_all || freenemo_warn "Health check issues detected, continuing anyway..."

    # Start periodic logger
    log_periodic_printer 30 &
    ORCH_PIDS+=($!)
    freenemo_log "Periodic logger started (PID: $!)"

    freenemo_success "Pre-flight complete"
}

# ─── SESSION INITIALIZATION ──────────────────────────────────────────────────
orch_session_init() {
    freenemo_banner "📋 SESSION INITIALIZATION"
    session_init_main
    freenemo_success "Session initialized"
}

# ─── EARTHBEAT LAUNCHER ──────────────────────────────────────────────────────
orch_launch_earthbeat() {
    freenemo_banner "🌍 LAUNCHING EARTHBEAT — Mode: $MODE"

    case "$MODE" in
        chamber)
            eb_run_chamber_mode &
            ORCH_CHAMBER_PIDS+=($!)
            ;;
        parallel|tokenring)
            eb_run_parallel "$MODE" "$COUNT" &
            ORCH_CHAMBER_PIDS+=($!)
            ;;
    esac

    freenemo_log "Earthbeat launched (PIDs: ${ORCH_CHAMBER_PIDS[*]})"
}
# ═══ MODULE: 10b_main_orchestrator_loop.sh ═══════════════════════════════════════════════════
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# MODULE 10B: Main Orchestrator — Nemotron Loop, GitHub Sync, Main Entry
# API loop, periodic GitHub sync, procedure reiteration
# ════════════════════════════════════════════════════════════════════════════

# ─── NEMOTRON API LOOP ───────────────────────────────────────────────────────
orch_nemotron_loop() {
    freenemo_banner "🤖 NEMOTRON 3 ULTRA API LOOP — Starting"

    local iteration=0
    while $ORCH_RUNNING; do
        iteration=$((iteration + 1))
        ORCH_ITERATION=$iteration
        freenemo_log "=== Nemotron Loop Iteration $iteration ==="

        # Example: Run a quick nemotron command
        local prompt="System health check: Report current git status, disk usage, and any errors in ${ERROR_LOG_DIR}. Output as JSON."
        local payload=$(nemotron_build_payload "$prompt" false "low" 256 1024 true '{"type": "json_object"}' true)
        
        freenemo_log "Sending request to Nemotron..."
        local start_ms=$(date +%s%3N)
        nemotron_stream_reader "$payload" 60
        local end_ms=$(date +%s%3N)
        local latency=$((end_ms - start_ms))
        
        log_perf_latency "nemotron_api" "$latency" "success"
        log_perf_throughput 0 "$latency"

        # Sleep between iterations (adjustable)
        sleep 10
    done
}

# ─── GITHUB HANDLER INTEGRATION ──────────────────────────────────────────────
orch_github_sync() {
    freenemo_log "Syncing session logs to GitHub..."
    
    # Save main log
    gh_save_file "${SESSION_LOG_DIR}/freenemo.log" "Session log: $(date -u)" "$BRANCH_NAME"
    log_git_push "success" "$BRANCH_NAME" "freenemo.log"

    # Save heartbeat logs
    for hb_log in "${HEARTBEAT_LOG_DIR}"/*.log; do
        [[ -f "$hb_log" ]] || continue
        gh_save_file "$hb_log" "Heartbeat: $(basename "$hb_log")" "$BRANCH_NAME"
        log_git_push "success" "$BRANCH_NAME" "$(basename "$hb_log")"
    done

    # Save git stats
    for gs_log in "${GIT_STATS_LOG_DIR}"/*.log; do
        [[ -f "$gs_log" ]] || continue
        gh_save_file "$gs_log" "GitStats: $(basename "$gs_log")" "$BRANCH_NAME"
    done

    # Save errors
    for err_log in "${ERROR_LOG_DIR}"/*.log; do
        [[ -f "$err_log" ]] || continue
        gh_save_file "$err_log" "Errors: $(basename "$err_log")" "$BRANCH_NAME"
    done

    # Save performance
    for perf_log in "${PERF_LOG_DIR}"/*.log; do
        [[ -f "$perf_log" ]] || continue
        gh_save_file "$perf_log" "Perf: $(basename "$perf_log")" "$BRANCH_NAME"
    done

    freenemo_success "GitHub sync complete"
}

# ─── MAIN ORCHESTRATOR ENTRY ─────────────────────────────────────────────────
freenemo_main() {
    orch_parse_mode "$@"
    
    freenemo_banner "═══════════════════════════════════════════════════════════════"
    freenemo_banner "  FREENEMO v${FREENEMO_VERSION} — Nemotron 3 Ultra Orchestrator"
    freenemo_banner "  Mode: $MODE | Count: $COUNT | Repeat: $REPEAT"
    freenemo_banner "  Session: ${FREENEMO_SESSION_ID} | Agent: ${FREENEMO_AGENT_ID}"
    freenemo_banner "═══════════════════════════════════════════════════════════════"

    # Run the full procedure REPEAT times
    for ((rep=1; rep<=REPEAT; rep++)); do
        freenemo_banner "🔄 PROCEDURE ITERATION $rep / $REPEAT"
        
        # Recovery check at start of each iteration
        repo_recover_load || { freenemo_error "Repo recovery failed"; return 1; }
        
        orch_preflight
        orch_session_init
        orch_launch_earthbeat
        
        # Run nemotron loop in background
        orch_nemotron_loop &
        ORCH_PIDS+=($!)
        
        # GitHub sync loop (every 5 minutes)
        (
            while $ORCH_RUNNING; do
                sleep 300
                orch_github_sync
            done
        ) &
        ORCH_PIDS+=($!)
        
        # Wait for all background processes
        wait
        
        # If not last iteration, brief pause before restart
        if (( rep < REPEAT )); then
            freenemo_log "Iteration $rep complete. Pausing 5s before next iteration..."
            sleep 5
        fi
    done
    
    freenemo_success "All $REPEAT iterations complete"
}
# ════════════════════════════════════════════════════════════════════════════
# MAIN ENTRY POINT
# ════════════════════════════════════════════════════════════════════════════

# If executed directly (not sourced), run main
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    freenemo_main "$@"
fi
