#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# FREENEMO CONCATENATION SYSTEM
# Glues ~100-line modules into larger deployable scripts
# Usage: bash concat.sh [--output freenemo_deploy.sh] [--verify]
# ════════════════════════════════════════════════════════════════════════════

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULE_DIR="${SCRIPT_DIR}/../freenemo_modules"
OUTPUT_FILE="${SCRIPT_DIR}/../freenemo_deploy.sh"
VERIFY=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output) OUTPUT_FILE="$2"; shift 2 ;;
        --verify) VERIFY=true; shift ;;
        *) echo "Unknown: $1"; exit 1 ;;
    esac
done

# Module order (dependency sequence)
MODULES=(
    "00_core_config.sh"
    "01a_nemotron_payload_core.sh"
    "01b_nemotron_payload_advanced.sh"
    "02_transport_hardening.sh"
    "03a_github_handler_core.sh"
    "03b_github_handler_strategies.sh"
    "04a_earthbeat_chambers_core.sh"
    "04b_earthbeat_chambers_modes.sh"
    "05a_sdk_forge_core.sh"
    "05b_sdk_forge_install.sh"
    "06a_session_init_repo.sh"
    "06b_session_init_heartbeat.sh"
    "06c_session_init_persona.sh"
    "07_vllm_config.sh"
    "08a_logging_session_core.sh"
    "08b_logging_session_printer.sh"
    "09a_error_recovery_repo.sh"
    "09b_error_recovery_api.sh"
    "09c_error_recovery_health.sh"
    "10a_main_orchestrator_setup.sh"
    "10b_main_orchestrator_loop.sh"
)

concat_header() {
    cat <<'EOF'
#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# FREENEMO — Nemotron 3 Ultra Unified Orchestration Launcher (CONCATENATED)
# Auto-generated by concat.sh — DO NOT EDIT DIRECTLY
# Edit modules in freenemo_modules/ then re-run concat.sh
# ════════════════════════════════════════════════════════════════════════════

set -euo pipefail

EOF
}

concat_module() {
    local module="$1"
    local module_path="${MODULE_DIR}/${module}"
    if [[ -f "${module_path}" ]]; then
        echo "# ═══ MODULE: ${module} ═══════════════════════════════════════════════════"
        # Include full module (shebang in middle becomes comment)
        cat "${module_path}"
        echo ""
    else
        echo "# WARNING: Module not found: ${module_path}" >&2
    fi
}

# Build concatenated script
{
    concat_header
    for module in "${MODULES[@]}"; do
        concat_module "${module}"
    done
    # Add main entry point
    cat <<'EOF'
# ════════════════════════════════════════════════════════════════════════════
# MAIN ENTRY POINT
# ════════════════════════════════════════════════════════════════════════════

# If executed directly (not sourced), run main
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    freenemo_main "$@"
fi
EOF
} > "${OUTPUT_FILE}"

chmod +x "${OUTPUT_FILE}"
echo "Concatenated ${#MODULES[@]} modules into ${OUTPUT_FILE} ($(wc -l < "${OUTPUT_FILE}") lines)"

# Verify syntax if requested
if [[ "$VERIFY" == "true" ]]; then
    echo "Verifying syntax..."
    bash -n "${OUTPUT_FILE}" && echo "Syntax OK" || { echo "Syntax ERROR"; exit 1; }
fi