package com.carrpod.bounce;

import android.Manifest;
import android.app.Activity;
import android.bluetooth.BluetoothAdapter;
import android.content.SharedPreferences;
import android.bluetooth.BluetoothDevice;
import android.bluetooth.le.BluetoothLeScanner;
import android.bluetooth.le.ScanCallback;
import android.bluetooth.le.ScanSettings;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.hardware.SensorManager;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.net.wifi.rtt.WifiRttManager;
import android.net.wifi.rtt.RangingResult;
import android.net.wifi.rtt.RangingRequest;
import android.net.wifi.ScanResult;
import android.net.wifi.WifiManager;
import android.net.wifi.p2p.WifiP2pConfig;
import android.net.wifi.p2p.WifiP2pManager;
import android.net.wifi.p2p.nsd.WifiP2pDnsSdServiceInfo;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.os.HandlerThread;
import android.os.Looper;
import android.os.PowerManager;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowInsets;
import android.webkit.JavascriptInterface;
import android.webkit.WebChromeClient;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;
import com.carrpod.bounce.wifi.RssiKalmanFilter;
import com.carrpod.bounce.wifi.Trilateration;
import com.carrpod.bounce.wifi.PositionEKF;
import com.carrpod.bounce.wifi.ParticleFilter;
import com.carrpod.bounce.wifi.ZoneHMM;
import com.carrpod.bounce.wifi.WifiRttRanging;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import android.util.Log;
import java.net.HttpURLConnection;
import java.net.URL;

public class MainActivity extends Activity {

    private static final int PERM_REQ = 1001;
    private WebView webView;
    private LinearLayout headerOverlay;
    private SharedPreferences prefs;
    private String latestVersion = null;
    private boolean cleanMode = false;
    private Button cleanBtn;
    private TextView tagTextView;
    private WifiManager wifiManager;
    private WifiP2pManager p2pManager;
    private WifiP2pManager.Channel p2pChannel;
    private LocationManager locationManager;
    private SensorManager sensorManager;
    private BluetoothAdapter bluetoothAdapter;
    private BluetoothLeScanner bleScanner;
    private boolean btScanning = false;
    private PowerManager.WakeLock wakeLock;
    private HandlerThread sensorThread;
    private Handler sensorHandler;
    private final float[] accelData = new float[3];
    private final float[] magnetData = new float[3];
    private final float[] gyroData = new float[3];
    private boolean hasAccel = false, hasMagnet = false, hasGyro = false;
    private int stepCount = 0;
    private float accelMagnitude = 0f;
    private float altitude = 0f;
    private float vertVelocity = 0f;
    private long lastMovementTime = 0;
    private boolean scanning = false, broadcasting = false;
    private final Handler scanHandler = new Handler(Looper.getMainLooper());
    private int scanCount = 0;
    private long lastScanTime = 0;
