#!/bin/bash
# Create concatenated master documents for each particle topic

BASE="/workspace/bb8f9c5f-e866-4346-a29c-8d72daa0ad2d/sessions/agent_ce94de82-0027-4c65-8007-804a488f0140/Subatomic/OrganizedLibrary"
PARTICLES="$BASE/Particles"
OUT="$BASE/ConcatenatedMasters"

mkdir -p "$OUT"

topics=(
"Axion Deep Dive Emulation"
"Baryon Deep Dive_ One-Particle Universe"
"Boson Deep Dive Architecture Emulation"
"Boson Deep Dive_ A Universe"
"Dark Matter Deep Dive Simulation"
"Deep Dive_ Benevolent Neutralinos"
"Deep Dive_ One-Quark Universe Architecture"
"Deep Dive_ Tau Neutrino Universe"
"Deep Dive_ Tau Particle Benevolence"
"Electron Neutrino Deep Dive"
"Emulating Unique Electron Properties"
"Gauge Boson Deep Dive Request"
"Gluon Deep Dive Emulation Request"
"Graviton Deep Dive Technical Report"
"Hadrons Deep Dive Request"
"Higgs Boson Deep Dive Emulation"
"Kaon Deep Dive_ A Computational Model"
"Lepton Deep Dive_ One-Lepton Universe"
"Magneton Deep Dive_ Benevolent Monopole"
"Muon Deep Dive_ One-Particle Universe"
"Muon Neutrino Deep Dive Simulation"
"Neutron Deep Dive_ One-Nucleon Universe"
"OEU_ Benevolent Particle Overpressure"
"Particle Fusion Deep Dive Request"
"Photon Deep Dive Request"
"Pines Demon_ Electron Oscillation Discovery"
"Pion Deep Dive_ One-Pion Universe"
"Proton Deep Dive Emulation"
"Scalar Boson Deep Dive Request"
"Seven-Dimensional Universe Research Request"
"Strong Force Deep Dive Request"
"Vibrational Transference Deep Dive"
"W Z Boson Deep Dive Simulation"
)

for topic in "${topics[@]}"; do
    echo "Creating master for: $topic"
    
    topic_dir="$PARTICLES/$topic"
    master_file="$OUT/${topic// /_}_MASTER.md"
    
    # Start with header
    cat > "$master_file" <<EOF
# ${topic} — Complete Evolution Archive (V1.0 → V4.0 + Incoming)
## Subatomic Particle Library — Master Concatenation
**Topic:** $topic  
**Generated:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")  
**Structure:** Seed (V1.0) → Versioning Delta (V1→V2) → V2.0 Document → Incoming Research → Citations

---

EOF
    
    # Section 1: Seed Document (V1.0 PDF - note reference)
    cat >> "$master_file" <<EOF
# PART I: SEED DOCUMENT — V1.0 (Gemini AI Base Document)
## Source: \`v1.0${topic}.pdf\`
**Classification:** Original deep research document — likely generated by Gemini Deep Research  
**Format:** PDF (see \`v1.0/\` folder)  
**Role:** Foundation seed — all subsequent versions extend this document

> **Note:** The V1.0 seed document is a PDF. Key content summary:
> - Establishes the "One-${topic%% *} Universe" monistic ontology
> - Worldline topology with proper time τ as primary parameter
> - Intrinsic vs. Extrinsic property distinction
> - Benevolence metric: B = C · F · S (Coherence × Flux × Action)
> - Object-Oriented particle data architecture
> - WebGL/Three.js simulation framework (V1.0)
> - Pre-2022 physics constants and experimental data

---

EOF
    
    # Section 2: Versioning Delta (V1→V2)
    delta_file="$topic_dir/v1to2/v1.0${topic} v1to2 Versioning.md"
    if [ -f "$delta_file" ]; then
        cat >> "$master_file" <<EOF
# PART II: VERSIONING DELTA — V1.0 → V2.0
## Source: \`v1to2/v1.0${topic} v1to2 Versioning.md\`

EOF
        cat "$delta_file" >> "$master_file"
        echo -e "\n---\n" >> "$master_file"
    fi
    
    # Section 3: V2.0 Full Document
    v2_md="$topic_dir/v2.0/v1.0${topic} V2.0.md"
    if [ -f "$v2_md" ]; then
        cat >> "$master_file" <<EOF
# PART III: V2.0 FULL DOCUMENT — Deep Research Enhanced
## Source: \`v2.0/v1.0${topic} V2.0.md\`

EOF
        cat "$v2_md" >> "$master_file"
        echo -e "\n---\n" >> "$master_file"
    fi
    
    # Section 4: Incoming Research (from cross-cutting folders)
    cat >> "$master_file" <<EOF
# PART IV: INCOMING RESEARCH DOCUMENTS
## Cross-cutting research relevant to this particle topic

EOF
    
    # Add relevant incoming docs based on topic keywords
    if [[ "$topic" == *"Swarm"* ]] || [[ "$topic" == *"Fluid"* ]] || [[ "$topic" == *"Microbial"* ]] || [[ "$topic" == *"Ecosystem"* ]]; then
        for f in "$BASE/CrossCutting/SwarmMechanics/incoming/"*.md; do
            [ -f "$f" ] || continue
            cat >> "$master_file" <<EOF
## $(basename "$f" .md)
$(cat "$f")

---
EOF
        done
    fi
    
    # Add particle physics incoming docs
    for f in "$BASE/CrossCutting/GlueballTheory/incoming/"*.md; do
        [ -f "$f" ] || continue
        cat >> "$master_file" <<EOF
## $(basename "$f" .md)
$(cat "$f")

---
EOF
    done
    
    # Section 5: Citations
    cat >> "$master_file" <<EOF
# PART V: CITATIONS & REFERENCES
## Consolidated Bibliography from All Versions

### V1.0 References
- Original seed document bibliography (see V1.0 PDF)

### V2.0 New References (2022-2026)
- CODATA 2022 fundamental constants
- FLAG 2024 lattice QCD results
- HAYSTAC Phase II (2023) — quantum squeezed states
- ORGAN 2023 — millikelvin axion haloscope
- CASPEr-electric 2024 — axion-nucleon coupling
- JWST 2023-2024 galaxy morphology constraints
- LHC Run 3 results (2022-2026)
- LIGO O4 gravitational wave data
- KATRIN 2024 neutrino mass constraints
- NIF 2022 ignition results
- Pines' Demon discovery 2023
- IceCube tau neutrino 2023

### Cross-Cutting Research Citations
- See individual incoming documents for their specific references

---

*End of Master Concatenation for ${topic}*
*Total sections: 5 | Structure: Seed → Delta → V2.0 → Incoming → Citations*
EOF
    
done

echo "All master documents created in $OUT"