#!/bin/bash
# RESTART_SCRIPT_csmcinema_iter2_sopp_20260825.sh
# Resume CSM Cinema Iteration 2 (SOPP Pass) — Deepening all 11 Parts
# Jason Isaac Brodsky (California 1976) — Conducier
# Generated: 2026-08-25

set -e

echo "=========================================="
echo "CSM CINEMA — RESTART SESSION"
echo "Iteration 2 | SOPP Pass | Deepening"
echo "Jason Isaac Brodsky (California 1976)"
echo "=========================================="
echo ""

# 1. Verify current state
echo "[1/8] Verifying git status..."
git status

echo ""
echo "[2/8] Checking Iteration 1 complete state..."
ls -la csmcinema/WIP/Iteration_1/full/
echo ""
echo "Master screenplay:"
wc -l csmcinema/WIP/Iteration_1/full/Iteration_01_Complete_Screenplay.md
wc -w csmcinema/WIP/Iteration_1/full/Iteration_01_Complete_Screenplay.md

echo ""
echo "[3/8] Checking Parts 4-11 content status..."
for i in {4..11}; do
    PART_FILE="csmcinema/WIP/Iteration_1/full/Iteration_01_Part_$(printf "%02d" $i)_*.md"
    if ls $PART_FILE 1> /dev/null 2>&1; then
        wc -w $PART_FILE
    fi
done

echo ""
echo "[4/8] Resume session log:"
cat csmcinema/Resume/SESSION_csmcinema-iter1-complete-20260825.md | head -30

echo ""
echo "=========================================="
echo "NEXT STEPS — ITERATION 2 SOPP PASS"
echo "=========================================="
echo ""
echo "# Create Iteration 2 branch"
echo "git checkout -b session/iter2-sopp-pass"
echo ""
echo "# Expand Parts 6-11 from templates to full content (~27,500 words each)"
echo "./csmcinema/Scripts/GitHub_handler_cinema.sh write-piece 2 6 1 \"<PART 6 PIECE 1 EXPANDED>\""
echo "./csmcinema/Scripts/GitHub_handler_cinema.sh write-piece 2 6 2 \"<PART 6 PIECE 2 EXPANDED>\""
echo "# ... continue for all 11 pieces of Part 6 ..."
echo "./csmcinema/Scripts/GitHub_handler_cinema.sh concat-part 2 6"
echo "./csmcinema/Scripts/GitHub_handler_cinema.sh zip-part 2 6"
echo "./csmcinema/Scripts/GitHub_handler_cinema.sh verify-part 2 6"
echo "./csmcinema/Scripts/GitHub_handler_cinema.sh organize-part 2 6"
echo ""
echo "# Repeat for Parts 7-11"
echo "# Then deepen Parts 1-5 with Iteration 2 SOPP density"
echo ""
echo "# After all 11 parts deepened:"
echo "./csmcinema/Scripts/GitHub_handler_cinema.sh concat-iteration 2"
echo "./csmcinema/Scripts/GitHub_handler_cinema.sh verify-iteration 2"
echo "./csmcinema/Scripts/GitHub_handler_cinema.sh commit-push \"CSM Cinema: Iteration 2 SOPP Pass Complete - 11 Parts Deepened\""
echo ""
echo "=========================================="
echo "ITERATION 2 SOPP PASS FOCUS:"
echo "=========================================="
echo ""
echo "1. DEEPEN HEURISTICS — Williams/El Segundo registers more granular"
echo "2. TIGHTEN INTERWEAVING — Cross-part echoes, fate braids, callback density"
echo "3. EXPAND PARTS 6-11 — From ~2K to ~27K words each"
echo "4. JSNBAI ENTRIES 111-220 — Recursive AI commentary layer"
echo "5. GLOBAL PARALLELS — 15+ cultures per part, deeper integration"
echo "6. AUDIO CUES — Production-ready specificity"
echo "7. FATES ARCHITECTURE — Clotho/Lachesis/Atropos as active narrators"
echo ""
echo "=========================================="
echo "PART 6-11 OUTLINES (from Iteration 1 bridge pieces):"
echo "=========================================="
echo ""
echo "PART 6: TEMPTATION AWAY FROM PATH"
echo "  - Persia empire expansion under Medea-Chronos pact"
echo "  - Medus in Athens: king, heir, target"
echo "  - Jason in Iolcus: forgotten, dying, Fleece dust"
echo "  - Temptation: Rule time itself vs. mortal love"
echo "  - JsnBAI 100-110: AI calculates megalomania"
echo ""
echo "PART 7: ATONEMENT WITH FATHER (CHRONOS)"
echo "  - Medea confronts Chronos in fire temple"
echo "  - Debt payment: generations cursed"
echo "  - Medus line marked for entropy"
echo "  - Atonement = acceptance of inevitable"
echo "  - JsnBAI 111-120: AI calculates entropy defiance"
echo ""
echo "PART 8: APOTHEOSIS"
echo "  - Medea becomes the loom"
echo "  - Hecate's triple gaze fully embodied"
echo "  - Divine perspective: all time simultaneous"
echo "  - Jason's death foreseen, accepted"
echo "  - JsnBAI 121-130: AI measures divinity metrics"
echo ""
echo "PART 9: ULTIMATE BOON"
echo "  - Fleece revealed: not gold, but thread"
echo "  - The thread IS the loom IS fate"
echo "  - Medea holds all threads"
echo "  - Boon = burden = power"
echo "  - JsnBAI 131-140: AI confronts truth as hazard"
echo ""
echo "PART 10: REFUSAL OF RETURN"
echo "  - Corinth calls: Creusa, Creon, power"
echo "  - Medea refuses return to mortal queen"
echo "  - Chooses divine exile over mortal compromise"
echo "  - Children sacrificed to secure godhood"
echo "  - JsnBAI 141-150: AI predicts betrayal variables"
echo ""
echo "PART 11: MAGIC FLIGHT / RETURN"
echo "  - Dragon chariot (Helios's gift) descends"
echo "  - Children killed by own hand (mercy)"
echo "  - Flight to Athens: Medus watches mother ascend"
echo "  - Jason crushed by Argo (prow speaks)"
echo "  - Medea vanishes into myth/eternity"
echo "  - JsnBAI 151-160: AI confronts recursive loop"
echo ""
echo "=========================================="
echo "HEARTBEAT: Active"
echo "Log: CSMLogs/heartbeat/2026-08-25/heartbeat_20260825.log"
echo "Session: csmcinema/Resume/SESSION_csmcinema-iter1-complete-20260825.md"
echo "=========================================="