#!/bin/bash
# Phase 3: Integrate Caldera Sections into Canonical Article Structure
# Project 10: Prime Electron Caldera Synthesis
# Run from: CSMWip/10_Prime_Electron_Caldera_Synthesis/

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CALDERA_SECTIONS="$PROJECT_DIR/Caldera_Prime_Pi_Electron/sections"
CALDERA_PIECES="$PROJECT_DIR/Caldera_Prime_Pi_Electron/pieces"

echo "=========================================="
echo "PHASE 3: Integrate Caldera Sections into Articles"
echo "Project 10: Prime Electron Caldera Synthesis"
echo "=========================================="
echo ""

# Section-to-Article mapping
declare -A SECTION_MAP=(
    ["01"]="A_Article01_Worldline"
    ["02"]="A_Article02_CausalGeometry"
    ["03"]="C_Article03_HilbertSpace"
    ["04"]="A_Article20_Worldline"
    ["05"]="C_Article01_HilbertSpace"
    ["06"]="F_Article01_TranscendentPhysics"
    ["07"]="F_Article01_TranscendentPhysics"
    ["08"]="C_Article03_HilbertSpace"
    ["09"]="F_Article01_TranscendentPhysics"
    ["10"]="D_Article04_Couplings"
    ["11"]="S_Article01_Synthesis"
    ["12"]="R_Article01_MathCompendium"
)

# Article titles for README
declare -A SECTION_TITLES=(
    ["01"]="π(x) Axiomatic Foundation"
    ["02"]="Discrete Causal Geometry"
    ["03"]="SJ Vacuum & QFT"
    ["04"]="Topological Graph Invariants"
    ["05"]="Spinor Double Covers"
    ["06"]="Riemann Zeros & Chaos"
    ["07"]="SFF & Holographic Wormholes"
    ["08"]="NCG, Bost-Connes & Adeles"
    ["09"]="p-adic AdS/CFT & Adelic Bulk"
    ["10"]="Gauge Couplings, Koide & 426-Gen"
    ["11"]="Unified Synthesis"
    ["12"]="Mathematical Compendium"
)

echo ">>> Integrating 12 Caldera sections into Canonical article structure..."
echo ""

for sec in {01..12}; do
    target="${SECTION_MAP[$sec]}"
    title="${SECTION_TITLES[$sec]}"
    
    echo "--- Processing Section $sec: $title -> $target ---"
    
    # Create directory structure
    mkdir -p "$PROJECT_DIR/$target"/{full,pieces,zip,intros}
    
    # 1. Copy section master (with COMBINED_INTRO prepended)
    echo "  Copying section master..."
    cp "$CALDERA_SECTIONS/Section_${sec}_"*.md "$PROJECT_DIR/$target/full/" 2>/dev/null || true
    
    # 2. Copy piece files (13 pieces)
    echo "  Copying 13 piece files..."
    cp "$CALDERA_PIECES/article*"${sec}"*_piece_"*.md "$PROJECT_DIR/$target/pieces/" 2>/dev/null || true
    
    # Count pieces copied
    PIECE_COUNT=$(ls "$PROJECT_DIR/$target/pieces/"*.md 2>/dev/null | wc -l)
    echo "    Pieces copied: $PIECE_COUNT"
    
    # 3. Copy zip archive
    echo "  Copying zip archive..."
    cp "$CALDERA_PIECES/article*"${sec}"*_pieces.zip" "$PROJECT_DIR/$target/zip/" 2>/dev/null || true
    
    # 4. Copy intro files (4 files)
    echo "  Copying 4 intro files..."
    cp "$CALDERA_SECTIONS/Section_${sec}_intro_williams.md" "$PROJECT_DIR/$target/intros/" 2>/dev/null || true
    cp "$CALDERA_SECTIONS/Section_${sec}_intro_keymaker.md" "$PROJECT_DIR/$target/intros/" 2>/dev/null || true
    cp "$CALDERA_SECTIONS/Section_${sec}_intro_elsegundo.md" "$PROJECT_DIR/$target/intros/" 2>/dev/null || true
    cp "$CALDERA_SECTIONS/Section_${sec}_COMBINED_INTRO.md" "$PROJECT_DIR/$target/intros/" 2>/dev/null || true
    
    INTRO_COUNT=$(ls "$PROJECT_DIR/$target/intros/"*.md 2>/dev/null | wc -l)
    echo "    Intros copied: $INTRO_COUNT"
    
    # 5. Create README.md
    echo "  Creating README.md..."
    cat > "$PROJECT_DIR/$target/README.md" <<READMEEOF
# $target — Prime Electron Caldera Integration

**Source:** Caldera Prime Pi Electron, Section $sec  
**Title:** $title  
**Heuristic Intros:** Williams (3¶) + Keymaker (3¶) + El Segundo (3¶) = 9 paragraphs  
**Pieces:** 13 pieces concatenated  
**Compilations:** Clean, ReadAloud (full/intros/sections)

## Contents
- \`full/\` — Complete section with combined intro prepended
- \`pieces/\` — 13 individual piece files
- \`zip/\` — Zipped pieces archive
- \`intros/\` — 4 intro files (williams, keymaker, elsegundo, combined)

## Heuristic Structure
1. **Williams** (¶1-3): Constraint → Necessity → Commitment
2. **Keymaker** (¶4-6): Lock → Key → Turn  
3. **El Segundo** (¶7-9): Mirror → Participation → Protocol

## Cross-References
- Previous section: $((sec - 1))
- Next section: $((sec + 1))
- Section 11 (Unified Synthesis) integrates all domains
- Section 12 (Mathematical Compendium) provides computational protocols

## Source Files
- Section master: \`Caldera_Prime_Pi_Electron/sections/Section_${sec}_*.md\`
- Pieces: \`Caldera_Prime_Pi_Electron/pieces/article*${sec}*_piece_*.md\`
- Intros: \`Caldera_Prime_Pi_Electron/sections/Section_${sec}_intro_*.md\`

---
*Generated by Phase 3 integration script*
READMEEOF

    echo "  ✅ Section $sec integrated into $target"
    echo ""
done

echo ">>> Verification Summary:"
for sec in {01..12}; do
    target="${SECTION_MAP[$sec]}"
    FULL_COUNT=$(ls "$PROJECT_DIR/$target/full/"*.md 2>/dev/null | wc -l)
    PIECE_COUNT=$(ls "$PROJECT_DIR/$target/pieces/"*.md 2>/dev/null | wc -l)
    ZIP_COUNT=$(ls "$PROJECT_DIR/$target/zip/"*.zip 2>/dev/null | wc -l)
    INTRO_COUNT=$(ls "$PROJECT_DIR/$target/intros/"*.md 2>/dev/null | wc -l)
    echo "  $target: full=$FULL_COUNT, pieces=$PIECE_COUNT, zip=$ZIP_COUNT, intros=$INTRO_COUNT"
done

echo ""
echo ">>> Phase 3 Complete. All 12 sections integrated."
echo "=========================================="